### ISSUE TITLE
ToDo: Finalise initial repository and add members/admins

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#1]
Some things to tidy up

### Done
* [x] **org members & repo collaborators** (will handle it on a case by case basis from here on in)
* [x] **license**
* [x] **tags** on the repository
* [x] **versioning** - change to match FF stable, and do a 51 release
* [x] **authors & home url** - update to github but keep <51 info
* [x] **tags** for issues - set them up
* [x] **repo description** - needs something better
* [x] **avatar** for ghacksuser.js organisation - don't care about an org avatar, but if someone made one, would *consider* it
* [x] **js** - move `palemoon` to archive issue
* [x] **js** - move `to investigate - tor uplift` to sticky issue
* [x] **js** - replace `https://bugzil.la/xxxxxx` with official `bugzilla.mozilla.org/*`
* [x] **js** - move `site tests` and `firefox add-ons` to wiki
* [x] **js** - move `to investigate` to sticky issue, add outstanding items from local "to look at" list
* [x] **js** - see #30 
* [x] **wiki** - create a wiki stiki: ideas, drafts, guest wiki articles
* [x] **wiki** - wiki quickie: do the parts required by the readme needs - see #52 
* [x] **readme** - simplify it, use wiki links for all the technical stuff

**Comment by licaon-kter** [comment]
License: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by nodiscc** [comment]
> This is public so anyone should be able to post issues etc - right?

Yes anyone with a github account can use the issue tracker.

> License. Do I need one?

#2

**Comment by Atavic** [comment]
@Roman-Nopantski actually you have set your own membership to private, so your own user page doesn't have the shiny organization badge on the left column.

**Comment by Roman-Nopantski** [comment]
@Atavic Thanks. I think I am now public .. did I fix it alright? Also .. how come my comments show me as a member and not an owner? nodiscc there shows as a collaborator.

**Comment by Atavic** [comment]
The badge is there and maybe you appear as a member due to your previous privacy choices. 
Once you logout it will be sorted IMHO

**Comment by Roman-Nopantski** [comment]
Logged out and back in .. still show as a member. Did a google search on github, nada - oh well .. always a bridesmaid...

Logo - Martin Brinkmann (ghacks website) has said we can use his logo, but the quality is not great (didn't ask it he had a master high def vector). While I will make it clear in the readme that his site is not directly involved but rather the origin (I am keeping the name ghacks because this user.js is well known by it now), I think a decent new logo would be better. I see dimensions are recommended 500x500. Might make something.

**Comment by pyllyukko** [comment]
> Logged out and back in .. still show as a member.

Well at least it shows you as the owner of the organization:

![ghacksuserjs](https://cloud.githubusercontent.com/assets/1058704/23084163/b3c3b900-f569-11e6-8b44-382f2dfb0732.png)

It's probably just the way it works. The organization "owns" the repo and we're all members of that organization.

**Comment by atomGit** [comment]
> License. Do I need one?

NO <-- that's my answer because i think copyrights and patents and licenses and lawyers are utter bullshit (which they are)

YES <-- that's everyone else's answer - i might suggest going with GPL and keeping it simple

**Comment by Roman-Nopantski** [comment]
@atomGit Agreed. I went with MIT which is as simple as it gets. Thanks

**Comment by atomGit** [comment]
so are you 'Pants'?

**Comment by Roman-Nopantski** [comment]
Sure am, it's no secret :)

**Comment by atomGit** [comment]
well hello there - i'm 12bytes :)

**Comment by Roman-Nopantski** [comment]
@atomGit Well hey there :) Hope you like all the parrots :squawk:

**Comment by nodiscc** [comment]
Test.

**Comment by Roman-Nopantski** [comment]
@nodiscc : I got a bit carried away :)

- The organization has 4 people (1 is me as owner, and 3 members) and two invites which have been sitting there for a couple of days which I just cancelled (one of them was you nodiscc - if you want to be a member speak up). So myself, pyllyukko (for his master github skills if needed), earthlng (my VP from ghacks) and Atavic. We show as `members`

- The repo I will add people as `collaborators` if they wish (the default is read permissions), and I trust their name, such as yourself - regulars from pyllyukko's. I don't want to go overboard. All one has to do is ask. So far there is pyllyukko and nodiscc, and earthlng (who is pending). All are marked as "admin" and I can assign write permissions. I want and need earthlng to have full on permissions - seems if you are in both groups, "member" ranks higher than "collaborator"

@nodiscc : do you want me to invite you as a member (org)?

I'll have to tidy this up at some stage and exactly check what permissions are being assigned here. I'm still not 100% sure what a collaborator gains when permissions are read only.

**Comment by Atavic** [comment]
@Roman-Nopantski Last @Gitoffthelawn listed activity was in January.
As amember of the organization I can open new projects that will be eventually added to the org project list. Other orgs have forks listed.

**Comment by Roman-Nopantski** [comment]
@Atavic : ToDo list in post1 has a wiki item in it, listing those exact things :)

**Comment by Roman-Nopantski** [comment]
Tags: I just quickly stuck in the same as pyllyukko's, but you're right Atavic, this has a different purpose.

currently: privacy, firefox, security, customize, settings, anti-fingerprinting

I also need a decent description: currently it says "user.js -- making Firefox more secure, private and 'quiet'", which is a bit lame. Maybe something more along the lines of "a comprehensive user.js template for privacy, security and anti-fingerprinting" - what does everyone else think?

**Comment by Atavic** [comment]
##### desc
Customize your Firefox or Pale Moon user.js for privacy and security.

**Comment by fmarier** [comment]
@Roman-Nopantski I'm happy to be a collaborator. I'm watching the repo anyways :)

**Comment by Roman-Nopantski** [comment]
Collaborator it is, invite on the way

**Comment by Roman-Nopantski** [comment]
A mock up (not entirely sure if that M and eye is a copyright issue). I have all the elements on different layers and can change the colors, and my master/source is a much higher resolution. I'm thinking of looking up the Mozilla and Firefox colors.
![ghacks inc mockup](https://cloud.githubusercontent.com/assets/16656956/23099180/afe799a2-f6c5-11e6-8ec3-69583a567390.png)

An alternative would be possibly using this guy with his "privacy" shades on, keep the transparency and circle and university font, but use his head and glasses instead of the M and eye. I think that may violate terms (I have no idea): http://www.impawards.com/2001/monsters_inc_ver5.html

**Comment by earthlng** [comment]
_investigate replacing as many bugzilla.mozilla.org urls with the much shorter bugzil.la_
that domain is not associated with mozilla but is registered by a Reed Loden.
IMO replacing the direct mozilla URLs with a shorter redirection-url via someone else' server is a bad idea.

**Comment by licaon-kter** [comment]
> An alternative would be possibly using this guy with his "privacy" shades on

Better, this on referenced the movie right away for me.

**Comment by Atavic** [comment]
@Roman-Nopantski A lot of issues on github are about _Your tool breaks my Youtube, Twitter, Facebook_ etc.

I suggest to create a Saved reply to use in such cases with the following content:

_Better safe than sorry._

**Comment by Roman-Nopantski** [comment]
@earthlng : ok, we have one bugzil.la - we should revert that to bugzilla.
@Atavic : I'll wait for users to post issues - there is already a troubleshooting list which includes 20 odd prefs that cover 99% of breakage. People should learn to read. There will also be a troubleshooting wiki on how to narrow down a pref causing issues on a site

**Comment by Roman-Nopantski** [comment]
@Atavic : I have a plan to add some specific wiki pages for common fixes (sub pages under troubleshooting) - such as re-enabling suggestions (5 prefs), or getting video to work (GMPs, CDMs, EMEs etc), or re-enabling tracking protection and updates, or re-enabling all safebrowsing and updates etc. Simple step by steps lists. Then if someone says "Issue: Can't play video", we can just point them at the solution.

**Comment by Gitoffthelawn** [comment]
@Atavic @Roman-Nopantski @earthlng @licaon-kter @pyllyukko @nodiscc 

Hello everyone.  Sorry for my absence.  Very busy and dealing with some (hopefully temporary) health issues.

Feel free to add me as a member if you like.  As things mellow out for me, I'll be glad to lend a hand.

**Comment by Roman-Nopantski** [comment]
@Gitoffthelawn Take care of yourself bro :) Eat, drink, be merry ... but keep taking those meds xD - invite as repo collaborator on the way

@Atavic - please, don't take offense. I am going to remove you from the organisation level, and re-invite you at the repo level. ***No one needs org level*** to function in the repo. It's not about not trusting anyone, it's just standard operating procedure.

I need to review the whole org members (1 level besides owner) and repo collaborators (three levels - read, write, admin).

**Comment by Atavic** [comment]
@Roman-Nopantski No problems at all. At org level you can add more repositories (forked or not), while pinning the main repo on top of the list. I thought about adding a _legacy-user.js_.

**Comment by Gitoffthelawn** [comment]
@Roman-Nopantski Thanks Pants.  I'm hoping the tests come back negative.  I'm concerned, but I'm an optimist. :)

**Comment by Atavic** [comment]
- Talk about the Repo on places as _Wilders Security_. 
- Create Github Pages.

**Comment by Roman-Nopantski** [comment]
@Atavic Martin Brinkmann ( ghacks.net ) is going to do an article, after I give him the go ahead. First, I want to get the readme and a couple more topics done in the wiki (backup methods, implementation eg new proifle, test in portable), and to clean up the js (remove all the crap in the header section, do that formatting change).

TheWindBringeth keeps tabs on ghacks, he will find out on his own, and if he has a github account, I would actually expect him to pop in and say hi ;)

**Comment by earthlng** [comment]
@Roman-Nopantski please ignore the header/referrer section for now. I have some ideas to make it really great IMHO, kind of like a referrer-policy with changing only one or two values and enforce the rest to the default, so they don't interfere with what we want to achieve with it.
I want to do it when FF52 gets released, perhaps earlier if I find the time to do it.

**Comment by Roman-Nopantski** [comment]
You know, I'm just about ready to walk away from all this. I'm feeling a bit pissed off and depressed about the whole thing

**Comment by crssi** [comment]
@Roman-Nopantski OMG, please don't. You all have done such a lot in a such a short time. Maybe you need few days off and/or a truck of a beer.

**Comment by Thorin-Oakenpants** [comment]
@earthlng and others: OK, so now I'm being spammed by github with this ON EVERY PAGE

![issues_ _ghacksuserjs_ghacks-user js_-_2017-03-27_21 58 17](https://cloud.githubusercontent.com/assets/16656956/24348595/b8633aac-1338-11e7-8205-58890951de9d.png)

I even went to the survey site, allowed JS etc and quickly filled the whole thing in with bogus BS. And I still get it. EVERY. SINGLE. PAGE. and in the wiki edits it sits right over the save button. Starting to really annoy me. uBo filter only seems to apply to specific pages. How can I kill this thing?

**Comment by earthlng** [comment]
lol, you're such a noob :) hard to help you here without getting that shit myself. I had it once but clicked it away and never seen it since. See if it has an id in Inspector or otherwise you need to do some xpath-Fu

**Comment by Thorin-Oakenpants** [comment]
I aint got time .. just tell me

**Comment by earthlng** [comment]
I would but I don't get the message, nothing I can do

**Comment by crssi** [comment]
Just create uBo filter with context menu option... then edit it in uBo -> "My Filters" to be "more general" and not just for this page.

**Comment by Thorin-Oakenpants** [comment]
Its suddenly gone. @crssi tried that. Wonder if my bitch had anything to do with it. Probably didn't leak my github ID to the survey or something.

**Comment by Thorin-Oakenpants** [comment]
For the record: none of my cookie/dom/uBo/uMatrix/NS rules have changed one iota

**Comment by Thorin-Oakenpants** [comment]
@earthlng et al: The readme will be updated in the next 24 hrs from the garbled random thoughts I jotted down 5 or 6 weeks ago. Martin at ghacks is publishing an article on Saturday "ghacks user.js goes github and ramps it into space" or something like that (we've timed it so it maximizes weekend traffic/exposure). The article is written by me, but Martin will do an introductory paragraph or two, and he will source and grab any images he wants to insert. He will also do articles (reposts with a foreword) for every changelog we do titled "What's new in ghacks user.js XX", hopefully we can push these out within a few days of FF stable landing.

**Comment by Thorin-Oakenpants** [comment]
readme is done: comments welcome

**Comment by Gitoffthelawn** [comment]
Looks wonderful!  Great job!  👍 

Other feedback:
 1. *"But six monthly updates are problematic."*  Do you mean one update every month, or updates every six months?
 2. In the formula, it's supposed to be cube root, not square root. ;)
 3. "Web Extensions" should be "WebExtensions".

Again, great job!

**Comment by Gitoffthelawn** [comment]
BTW, I thought internet traffic, especially for tech sites, was the lowest on the weekends, not the other way around.  Is there now more traffic on the weekends?

**Comment by Thorin-Oakenpants** [comment]
1. `six monthly` -> `six-monthly` - i did 3 updates over a year and a half at ghacks
2. You need to drink more, it really opens the mind
3. `Web Extensions` -> `WebExtensions`

Cheers

**Comment by earthlng** [comment]
Very nice indeed! Not exactly "short" but I like it. But it looks more like the article you want to write for ghacks tbh. Idk if a readme needs a foreword for example. And as Gitoffthelawn's comment shows, the foreword is slightly confusing for people who didn't follow this on ghacks. I know what you mean by "six-monthly" updates but most people probably won't. IMO it should focus more on the here and now.

Since we now also have an Addons, Test sites and Userscripts section it would be nice to incorporate a mention of those as well, with links to each section in the wiki. And maybe also something about the TOR Uplift project and our 3 issues where we track the progress would be nice.
And also fe. [changelogs](https://github.com/ghacksuserjs/ghacks-user.js/search?q=label%3Achangelog&type=Issues&utf8=%E2%9C%93)

"Expanding heavily on the Scripts section" - Idk about "heavily" - IMO those scripts complement the user.js for problems where no pref can currently help with and I don't see that too many scripts are needed for that atm. With the TOR Uplift project progressing it should be even less. You mentioned you had some ideas for more scripts but is "heavily" really necessary, especially given the context of "Nothing is ever set in concrete, but we have a few ideas." ? "heavily" sounds like a promise that we may or may not be able to fulfill so I'd drop that word.

**Comment by Thorin-Oakenpants** [comment]
I'm going to push the ghacks article back a few days. I'm pushed for time anyway, plus I want earthlng to check it out first. Also, not publishing it on April 1st.

- I am so crap at writing :)
- Nothing tech in the readme reduces it, but pretty hard to keep it super short. it packs a lot.
- It's nothing like the article for ghacks. This is more of a mission statement/goals with a little feature itemizing to back that up. Speaking of which, yeah - I will edit that a little by mentioning extra (wiki) items and linking things (eg changelog etc).
- Don't want to overdo the links, especially if and when we end up with branches, so am quite happy to leave the "user.js" as text only. I'll see what it looks like when I edit
- "Expanding heavily" - yeah, a bit over the top, will simplify that. By Scripts I mean the entire section, not just "user scripts" (greasemonkey), which I think we actually do an awful lot with
- I used "simple" and "simplicity" in the same sentence which looks dorky. I'll fix that.

And last but not least the foreword. Just rambling here: Its personal and sets a tone, rather than diving in and saying what does this do, although that could be tweaked? It gives relevance and context and history - especially important since we are using the name ghacks, and Martin deserves a special mention. I am also trying to make it painfully clear that this was my/our work and not copied from anywhere - when people start using words like "the ghacks user.js was modeled on someone else's" it starts to really piss me off. I want to set that perception straight. I got a few ideas from there, I contributed as much and now many more since, and am happy to continue doing so. I just want to set the record straight. I'm not actually linking to the original article(s)
- So, I could move it to the end as an Afterword, and remodel the what does it do first line. Yes/No?

**Comment by Atavic** [comment]
Yes, that seems a good ending for the article, while the foreword is optimal on the GH page.

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants wrote: *I am so crap at writing :)*

Quite the opposite!  I find your writing to be humorous and enjoyable.  The grammar isn't superb, but geniuses rarely have good grammar.

Besides, anyone writing under the pseudonym **Thorin Oaekenpants** immediately has my attention.  I ROFLed when you switched to that name.  Is there any historical document in which the switch was discussed?  I could use some extra smiles... 😃

**Comment by Thorin-Oakenpants** [comment]
Damnit .. venn diagram time ... i am not in the circle marked geniuses .. cogito ergo sum .. I could be a good writer, but there's another circle overlapping ... now I'm confused.

Well it was either that or Otto von Pantsmark, and no one likes marks on their pants .. I also considered Ichapants Crane (itchy pants?), Know-Nothing Bozo the Non-Wonder Pants, William Makepants Fappery, Ernest Hemingpants, Pantz Kafka, Benedict Cumberpants, Obi-Pants Kenobi and SupercalifragilisticPANTSpialidocious...

got a few thousand more here without even raising a sweat

**Comment by Gitoffthelawn** [comment]
**Benedict Cumberpants** ***+1000 👍***

Infinite possibilities regarding a bunch in your pants... 

Oh, and you clearly forgot the French favorite, **Napoleon Bonapants** ;)

**Comment by Thorin-Oakenpants** [comment]
OK, so I've redone it due to the ~~incessant criticism xD~~ excellent feedback. Hopefully no more changes are required.

**Comment by earthlng** [comment]
Hey, IMO it misses something essential and that is what this whole github page is about.
I know it's in the Overview but it should also be mentioned at the top of the Readme.
Something similar like PK has:
```
Firefox configuration hardening

A user.js configuration file for Mozilla Firefox designed to harden Firefox settings and make it more secure.
```

**Comment by earthlng** [comment]
`our awesome Wiki.` - you really like to blow your own horn don't you? ;)

**Comment by Thorin-Oakenpants** [comment]
IDK .. it says that in the next line, except it doesn't mention Firefox at all. I can only say what it does so many times. How about:

"A `user.js` is a Firefox configuration file that can control hundreds of settings. For a more technical breakdown and explanation, check out the Overview in our awesome Wiki."

Are you saying I should remove the word awesome? Do you not think out wiki is awesome? I'm showing self belief and instilling that in the plebs and dirty masses xD. They'll hang on my every word :)

Either I use (only "Overview" is linked)
- "explanation, you can read more in our Overview"
- "explanation, check out the wiki Overview"
- "explanation, check out the Overview in our awesome Wiki."

^^ Which one

**Comment by earthlng** [comment]
> A user.js is a Firefox configuration file that can control hundreds of settings

No, IMO it should be like a sub-title/description instead of an explanation. Not what a user.js is but what THIS is. fe `A comprehensive user.js template for Firefox to enhance security & privacy`

And the project name as a title would also not be bad IMO, basically make the readme like a stand-alone readme that you could post anywhere

> Do you not think out wiki is awesome?

I think it's pretty neat but "awesome work" should speak for itself IMHO

Don't take this the wrong way, but if you compare PK's page with ours, theirs is very professional and objective while ours here is more on the funny side and bragging how awesome we are.
If they are the "hackers" we are the "script-kiddies". where would you prefer to get your infos from?

**Comment by Thorin-Oakenpants** [comment]
I am not going to say "privacy and security" yet again for a third time in three paragraphs

I will remove all the humor and picture and everything else

**Comment by earthlng** [comment]
Hey Pants, fantastic changes to the Readme - I love it! I hope you're not mad at me because you removed all the comments? :(
One remaining thing I don't understand is why you don't want to link to the 3 articles on ghacks? I mean, jeez, you had a tech site write articles about your work! That's something worth linking to.
I'd link the 1st article in this sentence:
`was first published at ghacks in August 2015` - because the ghacks main domain is already linked to anyway and then link to the other 2 articles in here:
`with three major updates and articles`

I really like pyllyukko's [References](https://github.com/pyllyukko/user.js/#references) - it would be nice to also link to some of those sites/resources somewhere. Or just link to pylly's References idk.

**Comment by Thorin-Oakenpants** [comment]
continuing on .... (and I am far from finished..)

:small_orange_diamond: TOR

https://blog.torproject.org/category/tags/tbb
https://trac.torproject.org/projects/tor/report/38
https://trac.torproject.org/projects/tor/query?keywords=~tbb-fingerprinting
https://www.torproject.org/projects/torbrowser/design/index.html.en

:small_orange_diamond: Mozilla

DXR: https://dxr.mozilla.org/mozilla-central/source/

Security Advisories: https://www.mozilla.org/en-US/security/advisories/
Security Blog: https://blog.mozilla.org/security/

Tor Uplift Project: https://wiki.mozilla.org/Security/Tor_Uplift/Tracking

:small_orange_diamond: Other

Portable Firefox: http://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./

and from earthlng:
https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/
https://blog.mozilla.org/security/category/security/
https://www.mozilla.org/en-US/firefox/releases/
https://developer.mozilla.org/en-US/Firefox/Releases
https://www.fxsitecompat.com/en-CA/
https://www.fxsitecompat.com/en-CA/docs/

**Comment by Thorin-Oakenpants** [comment]
so which one is better?
- https://www.mozilla.org/en-US/security/advisories/  (this one also has ESR and thunderbird, I think that's the only diff)
- https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/

**Comment by earthlng** [comment]
http://portableapps.com/apps/internet/firefox_portable

**Comment by earthlng** [comment]
the first I think

**Comment by Thorin-Oakenpants** [comment]
I changed my https://www.mozilla.org/en-US/security/advisories/ to your https://blog.mozilla.org/security/category/security/  as yours is snippets and shows more per page

I already have portable apps sourceforge link, do we really want the portableapps.com one?

**Comment by earthlng** [comment]
TOR should be listed after Mozilla stuff

**Comment by earthlng** [comment]
> do we really want the portableapps.com one?

yes, I'd say so, it's the main page from portableapps and also lists other versions like ESR etc while your sourceforge link goes directly to the stable files

**Comment by earthlng** [comment]
you mean this https://blog.mozilla.org/security/ to this https://blog.mozilla.org/security/category/security/ - right?

**Comment by Thorin-Oakenpants** [comment]
^^see above

yes, tor section to the bottom, was just pasting what I was adding at random from all my speed dials and I happened to have tor at the start

**Comment by earthlng** [comment]
IMO the first is better and people can click on "category security" if they want to limit the blog posts. Or we add the category security link in brackets behind the first link

**Comment by Thorin-Oakenpants** [comment]
@earthlng : updated .. scroll up. thoughts? - comment in the original post

**Comment by earthlng** [comment]
Mozilla Security Advisories: wrong link
and I was wrong about the sourceforge link - it also lists the ESR versions under that folder, so maybe rename that to `Stable/ESR releases`

**Comment by Thorin-Oakenpants** [comment]
Mozilla Security Advisories: wrong link ????  What is it meant to be?

**Comment by Thorin-Oakenpants** [comment]
^^ done https://www.mozilla.org/en-US/security/advisories/

**Comment by Thorin-Oakenpants** [comment]
> don't want to link to the 3 articles on ghacks

It was four articles, and i linked the first one

**Comment by Thorin-Oakenpants** [comment]
Right, spose I better sent Martin that article then
