### ISSUE TITLE
ToDo: compare ghacks vs pyllyukko user.js, decide on additions

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#10]
/******
  ghacks user.js * date: 18 Feb 2017 vs pyllyukko user.js
  what pyllyukko has that ghacks doesn't
 ******/

* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/fe50cf94b5524ad38b11a69e013d0de4c2c15910
user_pref("browser.privatebrowsing.autostart", true);
* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/4d0e5825a27ca5a899cad8bb00e8bddd84650940
user_pref("network.IDN_show_punycode", true);
* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/b73324e39122282b4150979b10f1164a36da8170
user_pref("browser.ssl_override_behavior", 1);
* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/df1e1e42e8aa57148b78cdc613133f9371dd6d0c
user_pref("security.csp.enable", true);
* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/e0e7fc4c32a18a4d3cd8e552ae5f893bb61e4030 (added to deprecated (48+))
user_pref("dom.mozTCPSocket.enabled", false);
* [x] DONE: https://github.com/ghacksuserjs/ghacks-user.js/commit/de21ffd178b3d9106de55de0216b4455e4b73ffb
user_pref("security.csp.experimentalEnabled", true);
* [x] WILL BE DONE: #32 
user_pref("browser.formfill.expire_days", 1);
* [x] WILL BE DONE: #32 
user_pref("browser.download.manager.retention", 0); // (hidden pref)
==
* [x] WONTFIX (I am not messing with people's search engines)
// user_pref("browser.search.defaultenginename", "DuckDuckGo");
* [x] WONTFIX: deprecated approx FF29
user_pref("browser.sessionstore.postdata", 0);
* [x] WONTFIX: deprecated approx FF32
user_pref("network.seer.enabled", false);
* [x] WONTFIX: deprecated approx FF33
user_pref("plugins.hide_infobar_for_outdated_plugin", false);
* [x] WONTFIX: both deprecated, the first approx FF37
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1", false);
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1-https", false);
* [x] WONTFIX: deprecated approx FF41 (note: still two returns in DXR, not used)
user_pref("browser.newtab.url", "about:blank");
* [x] WONTFIX: deprecated (not sure when)
user_pref("browser.sessionstore.enabled", false);
* [x] WONTFIX: https://github.com/pyllyukko/user.js/commit/ac0cd4bd4a6ebeeeb8039efa9820b3bc3526f34c
user_pref("javascript.options.methodjit.chrome", false);
user_pref("javascript.options.methodjit.content", false);
* [x] WONTFIX: same as default
user_pref("devtools.debugger.force-local", true);
* [x] WONTFIX: no longer in DXR
user_pref("plugin.state.libgnome-shell-browser-plugin", 0);

---original post--
See: https://github.com/pyllyukko/user.js/issues/205#issuecomment-280842731

I will compare ghacks to pyllyukko and output
- What ghacks has that pyllyukko doesn't (large list to dump on pastebin, keep ghacks numbering/order/comments to help with dissection and analysis of it)
- What pyllyukko has that ghacks doesn't (small list, I can paste the items here)
Results given to each party to work through.
 
Then we can decide what to add/discard

**Comment by Roman-Nopantski** [comment]
/******
  ghacks user.js * date: 18 Feb 2017 vs pyllyukko user.js
  what pyllyukko has that ghacks doesn't
 ******/

- [ ] // Disable dom.mozTCPSocket.enabled (raw TCP socket support)
// https://trac.torproject.org/projects/tor/ticket/18863
// https://www.mozilla.org/en-US/security/advisories/mfsa2015-97/
// https://developer.mozilla.org/docs/Mozilla/B2G_OS/API/TCPSocket
user_pref("dom.mozTCPSocket.enabled", false);

- [ ] // Default search engine
// user_pref("browser.search.defaultenginename", "DuckDuckGo");

- [ ] // https://secure.wikimedia.org/wikibooks/en/wiki/Grsecurity/Application-specific_Settings#Firefox_.28or_Iceweasel_in_Debian.29
user_pref("javascript.options.methodjit.chrome", false);
user_pref("javascript.options.methodjit.content", false);

- [ ] // disable Gnome Shell Integration
user_pref("plugin.state.libgnome-shell-browser-plugin", 0);

- [ ] // disable remote debugging
// https://developer.mozilla.org/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop#Enable_remote_debugging
// https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox#Advanced_settings
user_pref("devtools.debugger.remote-enabled", false);

- [ ] // https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop#Firefox_37_onwards
user_pref("devtools.debugger.force-local", true);

- [ ] // https://wiki.mozilla.org/Privacy/Reviews/Necko#Principle:_Real_Choice
user_pref("network.seer.enabled", false);

- [ ] // Disallow NTLMv1
// https://bugzilla.mozilla.org/show_bug.cgi?id=828183
user_pref("network.negotiate-auth.allow-insecure-ntlm-v1", false);
// it is still allowed through HTTPS. uncomment the following to disable it completely.
// user_pref("network.negotiate-auth.allow-insecure-ntlm-v1-https", false);

- [ ] // https://bugzilla.mozilla.org/show_bug.cgi?id=855326
user_pref("security.csp.experimentalEnabled", true);

- [ ] // CSP https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy
user_pref("security.csp.enable", true);

- [ ] // http://kb.mozillazine.org/Browser.sessionstore.postdata
// NOTE: relates to CIS 2.5.7
user_pref("browser.sessionstore.postdata", 0);

- [ ] // http://kb.mozillazine.org/Browser.sessionstore.enabled
user_pref("browser.sessionstore.enabled", false);

- [ ] // Always use private browsing
user_pref("browser.privatebrowsing.autostart", true);

- [ ] // CIS Version 1.2.0 October 21st, 2011 2.5.5 Delete Download History
// Zero (0) is an indication that no download history is retained for the current profile.
user_pref("browser.download.manager.retention", 0);

- [ ] // CIS Version 1.2.0 October 21st, 2011 2.5.6 Delete Search and Form History
user_pref("browser.formfill.expire_days", 0);

- [ ] // https://support.mozilla.org/en-US/kb/new-tab-page-show-hide-and-customize-top-sites#w_how-do-i-turn-the-new-tab-page-off
user_pref("browser.newtab.url", "about:blank");

- [ ] // CIS Version 1.2.0 October 21st, 2011 2.1.3 Enable Information Bar for Outdated Plugins
user_pref("plugins.hide_infobar_for_outdated_plugin", false);

- [ ] // CIS Mozilla Firefox 24 ESR v1.0.0 - 3.6 Enable IDN Show Punycode
// http://kb.mozillazine.org/Network.IDN_show_punycode
user_pref("network.IDN_show_punycode", true);

- [ ] // http://kb.mozillazine.org/Browser.ssl_override_behavior
// Pre-populate the current URL but do not pre-fetch the certificate.
user_pref("browser.ssl_override_behavior", 1);

**Comment by crssi** [comment]
I am almost 100% sure that "browser.newtab.url" is deprecated for FF 41 on.

**Comment by Roman-Nopantski** [comment]
I've checked out some of these before - that punycode one comes up all. the. time. It's just a list of everything we didn't have, and we can work through it. Poor old pyllyukko has 356 preferences to go through - not that he will want a lot of it, but he's missing some quite a few that I would expect to be there.

**Comment by crssi** [comment]
I am wrong, but default for "browser.ssl_override_behavior" is now 2, at least in FF 51.

**Comment by crssi** [comment]
You already have setting "devtools.debugger.remote-enabled" set to false ;)

**Comment by Roman-Nopantski** [comment]
Removed it from the list. I manually compared the two files because they were so different. I would copy a pref name from pyllyukko's, search for it in ghacks - if we both had it, I would remove it from both sides. At the end I had two files: pyllyukko's one left with stuff ghacks didn't have, and the ghacks one the reverse. I guess all that ctrl-c, ctrl-v, search and select/delete got to me :) Haven't heard back from https://github.com/pyllyukko/user.js/issues/205 , I think they're all sleeping.

**Comment by crssi** [comment]
Deprecated:
dom.mozTCPSocket.enabled (FF48)
network.seer.enabled (FF32)
network.negotiate-auth.allow-insecure-ntlm-v1-https (FF37)
browser.sessionstore.postdata (FF29)
browser.download.manager.retention (FF28)
browser.newtab.url (FF41)
plugins.hide_infobar_for_outdated_plugin (FF33)

;)
Do a check or remove or strike over on your upper list, then I will go over the updated list again.
If you wish, of course.

**Comment by Roman-Nopantski** [comment]
> Deprecated (taken from "linux" list"):

Do mean these 7 are all Linux specific? Or just `dom.mozTCPSocket.enabled` ?

I think some of them (maybe all of them) could be added to the deprecated section. And the method would be to check them and add a note, after committing all the changes. Might hold off until we decide what to do with them all, and I'll do a single commit.

eg:
- [x] // added to deprecated
      // Disallow NTLMv1.. etc

**Comment by crssi** [comment]
All...
but I am not sure its "Linux specific".
I have just noted that this was taken from the list on https://www.wilderssecurity.com/threads/firefox-lockdown.368003/page-10#post-2633173.

I am sure that "browser.newtab.url" if not linux pecific, but it is removed/deprecated over all.

I will try to find some good source for deprecated stuff, if you don't have any already?

**Comment by Roman-Nopantski** [comment]
@crssi : always check DXR - browser.download.manager.retention wasn't deprecated, it was switched to a hidden pref. In fact TheWindBringeth actually says

> Due to several factors, these entries may not accurately represent which prefs are no longer checked for by the application code you are using.  Consult the source code/ when in doubt:  https://dxr.mozilla.org

I have a speed dial for DXR set to land on mozilla central which earthling and I have worked out is the best branch: https://dxr.mozilla.org/mozilla-central/source/

**Comment by crssi** [comment]
Noted... thx for source... will do better next time. :)

**Comment by earthlng** [comment]
@Pants, ROFL, even the syntax error pref is now properly sourced, gj! xD

Browser.sessionstore.enabled - Has an effect in
    Mozilla Firefox 3.0 and below. Since Firefox 3.5 this preference is superseded with setting browser.sessionstore.max_tabs_undo and browser.sessionstore.max_windows_undo to 0.

I disagree about 'network.IDN_show_punycode'.
https://www.ubuntu.com/usn/usn-3175-1/
"Armin Razmjou discovered that certain unicode glyphs do not trigger
punycode display. An attacker could potentially exploit this to spoof the
URL bar contents. (CVE-2017-5383)"
-> also noted here: https://www.mozilla.org/en-US/security/advisories/mfsa2017-02/
---> and the 2 bugzilla's are still Access Denied!
Here are a few more links discussing IDN/punycode exploits:
https://en.wikipedia.org/wiki/IDN_homograph_attack
http://blog.trendmicro.com/trendlabs-security-intelligence/can-idn-use-open-a-can-of-unicode-worms/
https://www.bluecoat.com/security-blog/2014-05-22/bad-guys-using-internationalized-domain-names-idns

'browser.formfill.expire_days' - I like this one, it gives users who want to use formfill better control.
-> I'd set it to 1 day and probably comment it out, and add it as 0812a or so.

**Comment by Roman-Nopantski** [comment]
`browser.formfill.expire_days`  .. use the lowercase tilde at both ends (I forget what its called), not an apostrophe: ` this symbol ` `  .. that pref is actually in the to investigate section at a suggested value of 1.

Write up the punycode and commit it then :) Then write up the formfill and commit that too, don;t forget to remove it from the to investigate section as well. I think individual commits is best practice - make sure to add a description when you do them, and edit my list up there to match what's happened :)

**Comment by earthlng** [comment]
Okay boss, better now?
While I'm at it, do you also have some shoes you want me to polish, or some pants to wash or something? xD
If I modify the master branch without any discussion, is that really what you want me to do?
I guess I could make a few forked branches and submit pull requests but just changing the master branch here doesn't feel right.

**Comment by Roman-Nopantski** [comment]
IDK .. I trust you but then I agree any pref changes should be handled by one person. I prefer your pull requests where we can discuss it. So yeah: Assigned to you - but submit a patch :)

**Comment by Roman-Nopantski** [comment]
> @Pants, ROFL, even the syntax error pref is now properly sourced, gj! xD

Who needs a canary .. when you can have a f**kn parrot, mate! :bworrkkkk: :)

**Comment by earthlng** [comment]
`browser.ssl_override_behavior`
I agree with setting this to 1, but what I don't understand is: wouldn't the cert have been loaded at that point already, anyway?

**Comment by crssi** [comment]
I have `browser.ssl_override_behavior = 2`
In that case we need `browser.xul.error_pages.enabled = true` (but this is a default now anyway).
Additonally, I have `browser.xul.error_pages.expert_bad_cert = true`

**Comment by Atavic** [comment]
`browser.ssl_override_behavior = 2`
This makes the browser get the certificate without having to click on _Get Certificate_.

**Comment by earthlng** [comment]
@crssi Thank you!! `browser.xul.error_pages.expert_bad_cert` is exactly what I wanted to start looking for in DXR, right now!

@Atavic but doesn't the browser have the cert loaded and checked already at that point?
I mean, how can it detect a faulty cert otherwise? It's weird.
Anyway, 1 is definitely better than 2, that's all I need to know atm

**Comment by Atavic** [comment]
There's a Crypto-Key exchange. LOng read [here](https://www.zscaler.com/blogs/research/%e2%80%98ssl-encryption-without-authentication%e2%80%99-debate).

**Comment by Roman-Nopantski** [comment]
@earthlng The difference between 1 & 2 *used* to be different, you *used* to have to click "Get Certificate" if 2 was the value. At least that's the way pyllyukko remembers it - I assume you read the issue linked to. Maybe go fire up an old FF version and check it out :) Or you could just read [this](https://bugzilla.mozilla.org/show_bug.cgi?id=413861#c1) from 2008 .. or get a time machine ;)

I don't think we need to add `browser.xul.error_pages.expert_bad_cert` at all

Now `browser.xul.error_pages.expert_bad_cert` has potential. I actually started to write it up as 1222 (my understanding is at false it hides the add exception button. I think this may be what you are looking for. Not sure if can be bypassed via Options>Advanced>Certs> .I ended up  deleting the whole thing. Feel free to bring up an issue on adding this and we can discuss the benefits and draft something

**Comment by earthlng** [comment]
`browser.xul.error_pages.expert_bad_cert` - as far as I can tell, when changed to true from default false, it opens the advanced explanation by default instead of you having to click it.
False doesn't hide the button - the default value is false.

**Comment by crssi** [comment]
True, the `browser.xul.error_pages.expert_bad_cert = true` just eases my laziness to spare me one more click when I know the site (some internal testing sites) with temporary self-signed cert and where I don't like to end up with a cert store full of a few times only used certs.

**Comment by Roman-Nopantski** [comment]
@earthlng I didn't research it and I do NOT take the mozillazine seriously (it is not maintained, I think it stopped around FF4?), but I do read it, and that was far as I had gotten before I dropped the whole thing: http://kb.mozillazine.org/Browser.xul.error_pages.expert_bad_cert - but clearly 50 years ago it did hide the button :)

**Comment by earthlng** [comment]
@Roman-Nopantski
_Unhide the “add exception” button on the SSL error page_ - it's not totally incorrect though - it makes the add exception button directly visible/clickable without needing to click on "advanced" first.

**Comment by crssi** [comment]
@Roman-Nopantski The other "my modus operandiy: I like to see the error message provided without clicking "advanced" first.
But anything you decide, its fine with me. ;)

**Comment by earthlng** [comment]
I wanted to title the pref as something like "blabla on **Insecure Connection** warning pages".
To make sure that's correct, I clicked all insecure links on badssl.com, and turns out it's not 100% correct.
There's one exception with HSTS:

https://subdomain.preloaded-hsts.badssl.com/
_This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. **As a result, it is not possible to add an exception for this certificate.**_

In those cases the pref doesn't display the advanced info.

Damn, now I have to incorporate that somehow :(

```
// 12xx: display Advanced information on Insecure Connection warning pages (thanks @crssi)
   // only works when it's possible to add an exception, fe. doesn't work for HSTS (https://subdomain.preloaded-hsts.badssl.com/)
   // testpage: https://expired.badssl.com/
user_pref("browser.xul.error_pages.expert_bad_cert", true);
```

@Roman-Nopantski how is that?

**Comment by Roman-Nopantski** [comment]
@pyllyukko Question: Does `security.csp.experimentalEnabled` -> true harden security? I bet you say yes, because that's what you have :). I won't profess to understanding it, but the "experimental" part of it I guess allows you to use new features if available, right? Any downsides?

**Comment by earthlng** [comment]
@Roman-Nopantski
I'm not going to create a PR for browser.formfill.expire_days. 0812 already says "You can clear formdata on exiting Firefox" and IMO we don't need another pref that does the same thing.

**Comment by Roman-Nopantski** [comment]
@fmarier @pyllyukko 

```
* [ ] enable CSP 1.1 experimental hash-source directive (FF29+)
// https://bugzilla.mozilla.org/show_bug.cgi?id=855326
// https://bugzilla.mozilla.org/show_bug.cgi?id=883975
user_pref("security.csp.experimentalEnabled", true);
```

Can someone tell me why this increases security/privacy? The best I can come up with is trying to read and understand this: https://www.w3.org/TR/2014/WD-CSP11-20140211/ .. and searching for hash-source

**Comment by Atavic** [comment]
It's a proposed security implementation, it's [there](https://www.w3.org/TR/2014/WD-CSP11-20140211/#content-security-policy-header-field), scroll down to:
_3.2.2 Source List_

**Comment by pyllyukko** [comment]
> Can someone tell me why this increases security/privacy?

The hashing improves security when sites are using e.g. third party JS scripts. As the site owner has no visibility on what kind of scripts the users have had at any given moment, the site owner can validate/verify certain version of the script, include it's hash and make sure the users only use the whitelisted one if any.

There has been many cases for instance where ad sites have had malicious content because of some breach and the site owners have had zero control over that and of course the users experience that those sites are attacking your browser.

**Comment by Roman-Nopantski** [comment]
Yeah, my eyes glazed over a bit in that doc - I could find strings like nonce etc, but I dinnae understand it - I get that it's a hash check value, hence it must be doing something extra (the experimental part sounded a bit strange, and it's old, so the experiment must be over, and the code still exists in DXR, and I looked at the code and couldn't make any sense of it).  I never want to just throw prefs in without understanding them. It's easier and quicker to ask someone in this case - and voila, you both answered. So thanks guys. I'm not going to bother to try and explain it the js - lulz.

@pyllyukko - Yes. That answers the question on how it increases security, with a real world example. Perfect. Thank you. I have questions such as who maintains these hash lists for verification, etc .. but don't answer that :) I'm adding it and that will be the end of the mini diff.

**Comment by earthlng** [comment]
> > Can someone tell me why this increases security/privacy?
> 
> The hashing improves security when sites are using e.g. third party JS scripts. As the site owner has no visibility on what kind of scripts the users have had at any given moment, the site owner can validate/verify certain version of the script, include it's hash and make sure the users only use the whitelisted one if any.
> 
> There has been many cases for instance where ad sites have had malicious content because of some breach and the site owners have had zero control over that and of course the users experience that those sites are attacking your browser.

@fmarier
* do you know why `security.csp.experimentalEnabled` is still disabled by default in FF?
* Is this safe to use in your opinion?

I feel like there have to be downsides to this or it would have been enabled by now, right?

**Comment by Atavic** [comment]
>For each request, the server generates a unique value at random, and includes it in the Content-Security-Policy header.

Par.
3.2.5.17.1

>who maintains these hash lists for verification. 

Once randomly generated, they stay in the HTML meta Element.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by fmarier** [comment]
> do you know why security.csp.experimentalEnabled is still disabled by default in FF?
> Is this safe to use in your opinion?

Right now, `security.csp.experimentalEnabled` only controls a single directive: [require-sri-for](https://w3c.github.io/webappsec-subresource-integrity/#request-verification-algorithms). It's disabled by default because it's a new feature which hasn't been standardized yet.

I don't think there's a lot of risk in enabling it because it's probably not used very much. For that same reason, there's probably not much point in enabling it either.

**Comment by earthlng** [comment]
> For that same reason, there's probably not much point in enabling it either.

Pants, I'd say we disable it again and wait until mozilla enables it by default
