### ISSUE TITLE
ToDo: compare active values ghacks vs pyllyukko user.js

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#18]
After #10 ghacks mini diff and [#208](https://github.com/pyllyukko/user.js/issues/208) pyllyukko monster diff ToDo's ae finished, do a diff of active values and investigate

## DONE
* [x] pref("network.stricttransportsecurity.preloadlist", true); '' ghacks: false and commented out
  * https://github.com/ghacksuserjs/ghacks-user.js/commit/2fcd21083ecafee0c4911bd211f8796e8ceef0fc
* [x] pref("network.cookie.cookieBehavior", 1); // ghacks: 2
  * no change. we choose to disallow all and tell users to use an extension for granular control
* [x] pref("pdfjs.disabled", true); // ghacks: false
  * no change. I would rather by default use the inbuilt reader. The info is all there in the pref number description, and informed users can change to external and use anything that they consider more secure/lightweight. We don't know what every end user has as a pdf app on their system - forcing an end user by default to this is a bad strategy **for us**. One word .. Acrobat.
* [x] pref("privacy.clearOnShutdown.cookies", true); // ghacks: false
  * no change: We do not want to destroy peoples cookies, especially when our default is block all and use an extension to control them. The only other thing we don't clear on shutdown is site preferences (which would upset a lot of users if sprung on them). The info is there if someone wants to clear absolutely everything
* [x] pref("privacy.clearOnShutdown.sessions", true); // ghacks: false
  * no change: see above
* [x] pref("extensions.update.enabled", true); // ghacks: false
  * no change: we think manual updates allow flexibility for reasons stated in the pref descriptions. Note for this and SB + TP, the readme and descriptions and js section header will point these particular pitfalls out (there will be iittle else in the section header, so it will stand out) - that's THREE places the user has been told in hard to miss terms, and the onus is on them
* [x] pref("browser.safebrowsing.malware.enabled", true); // ghacks: false
  * no change: we choose to -SB&TP and +uBo etc
* [x] pref("privacy.trackingprotection.enabled", true); // ghacks: false
  * no change: same as SB above
* [x] pref("privacy.trackingprotection.pbmode.enabled", true); // ghacks: false
  * no change: same as SB above
* [x] pref("browser.aboutHomeSnippets.updateUrl", ""); // ghacks: "https://127.0.0.1"
  * no change: pyllyukko should match .. use HTTPS re MiTM re as per TBB and discussions there over this in tor tickets
* [x] pref("browser.newtabpage.directory.source", "data:text/plain,{}"); // ghacks: "data:text/plain,"
  * no change: keep same as TBB, should never be used due to master switches
* [x] pref("media.gmp-manager.url", ""); // ghacks: "data:text/plain,"
  * no change: see above
* [x] pref("browser.newtabpage.directory.ping", ""); // ghacks: "data:text/plain,"
  * no change: see above
* [x] pref("security.ask_for_password", 0); // ghacks: 2
  * no change: it must be 2 for `security.password_lifetime` to apply
* [x] pref("signon.storeWhenAutocompleteOff", false); // ghacks true
  * see discussion here  https://github.com/pyllyukko/user.js/commit/5e2e5770c92d68fba9c59c0f15fd5624dca012c0
  * no change: pros and cons. Pros: possibly encourages more complex password use, is convenient,  and why should sites dictate when I can and can't remember passwords. Cons: some sites should never remember passwords, like bank sites (although I only have a few banks sites, I am yet to see this affect one). I'll add something to the description

**Comment by earthlng** [comment]
Oh, damn, so only when it's finished huh? Well I saw that too late so I adjusted my script, grabbed both versions latest master and compared them. The result is ... well, a lot of work still to be done....
```
combined prefs:  520
                          114 matching prefs
                          406 diffs
                          >     79 missing in ghacks
                          >   314 missing in pyllyukko
                          >     13 different values
```

**Comment by Roman-Nopantski** [comment]
It doesn't have to be when both sides work through their diffs, I just thought it would be better AFTER pyllyukko had added his (and when he adds his, he is looking at a gist of ours anyway, so he knows what we use). We can just  check our value against his commits as they work thru them, so no big deal.

Cool .. only 13 huh - so we might as well list them and re-assess their values match our purpose.

I did the mini and massive diffs manually, in order to keep everything in order and retain relevant comments. We ended up with 18 on here (check those 79, the vast bulk should be old cyphers), and pyllyukko got 360 (did you include the deprecated section?).

**Comment by earthlng** [comment]
I didn't look at the file-content tbh, my script parsed all active prefs, idk if deprecated are in there for pyllyukko's. here is the output: http://pasted.co/b0235e9e

**Comment by Roman-Nopantski** [comment]
I see now, your script doesn't discard the status of the pref
>>> missing in ghacks:
pref("security.tls.version.fallback-limit", 3);
pref("security.tls.version.max", 4);
pref("security.tls.version.min", 1);
^^ but they are there, along with more of them.  We just want to compare values, and we should also include the deprecated, because users may un-comment them for legacy versions.

I've dumped those 13 at the top, all seems to be OK at first glance. We advocate manual updates for everything, we advocate for using uBo and turning off TP and SB, the rest are url sanitizers, except for the password one where ours is hardened

Just in case, I will do my own diff compare - maybe today or tomorrow, and then we can close it.

**Comment by earthlng** [comment]
`I see now, your script doesn't discard the status of the pref`
No, of course not - you said `do a diff of active values and investigate`
I can adjust my script if you like, but I need to figure out how to best display that.

**Comment by earthlng** [comment]
_pref("browser.newtabpage.directory.source", "data:text/plain,{}"); // ghacks: "data:text/plain,"_
@Roman-Nopantski, @pyllyukko, we should both use "data:,{}" - the code expects a JSON and it complains otherwise, and with that format it defaults to "text/plain" and it also sets a charset that way, which again otherwise it can cause a warning in the console.
see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
ie. **data:,** is the short form for **data:text/plain;charset=US-ASCII,**

**Comment by Roman-Nopantski** [comment]
> _I_ see now, your script doesn't discard the status of the pref
No, of course not - you said do a diff of active values and investigate

I was just wondering why your counts were so different to the mini and massive diffs. It was OT anyway. Your diffs for values only is what matters here, but I still want to confirm deprecated was included for our benefit (not so much pyllyukko's who declined adding most of them in - but we do still have some in common).

re `data:text/plain,{}` vs `data:,{}` , let's see what @pyllyukko says. I am not a linux expert. But from Anonymous on ghacks: "Setting browser.newtabpage.directory.source to data:text/plain, creates an empty directoryLinks.json file in the appdata/local Mozilla folder.". Does using `data:,{}` still do this?

We have 5 `data:text/plain,{}` in total, in sync with TBB (but I should check, it's been 2 tor releases).

**Comment by earthlng** [comment]
`creates an empty directoryLinks.json file in the appdata/local Mozilla folder`
it creates that file with `{}` in it, but in the profile folder in my case. ie it's not an empty file and the folder is wrong afaik. everything after the comma is the file content. `data:text/plain,` **would** write an empty file, but it doesn't because it's not JSON while `data:text/plain,{}` creates a valid "empty" JSON file.
I think this behavior is preferable because it retro-actively overwrites the content of that file, while otherwise, the code fails, produces a warning in the console and doesn't write/overwrite that file at all, if I remember correctly.

We have 5 `data:text/plain,` and 0 `data:text/plain,{}` atm!

**Comment by Atavic** [comment]
- [ ] data:,
- [ ] data:text/plain,
- [ ] data:text/plain;charset=US-ASCII,

**Comment by Roman-Nopantski** [comment]
Sorry, overworked and not paying attention. Personally I couldn't care less about an empty or 2 byte file. And consoles are built to report errors :) I just brought up that comment from ghacks because I vaguely remembered something about a Linux issue with it - that one I quoted clearly wasn't it (not with /appdata/local). I'll just let you guys work it out.

**Comment by Roman-Nopantski** [comment]
first post edited with some talking points

**Comment by Roman-Nopantski** [comment]
@earthlng did you know you have two different values for values in your [js paste](http://pasted.co/5c0cfcc1) - pref 0360

**Comment by Roman-Nopantski** [comment]
We have five `"data:text/plain,"` values, so does TBB. One of ours is deprecated, but not in TBB due to ESR. And one of ours is a slightly different preference. TBB leaves `media.gmp-manager.url` at default and uses a TBB only pref called `media.gmp-manager.url.override` instead.

I am staying the same as TBB. I remember reading in one of their tickets about this that there were issues on Linux. I am not concerned about console errors .. that's what a console is for, to log everything, no big deal. All of these are already controlled by a master switch

browser.newtabpage.directory.ping -> newtab is disabled
browser.newtabpage.directory.source - newtab is disabled
datareporting.healthreport.about.reportUrl - healthreports are disabled
datareporting.healthreport.about.reportUrlUnified - is deprecated
media.gmp-manager.url - gmp is disabled

As for the https//:127.0.0.1 for snippets, we're cool, pyllyukko can do his own thing

**Comment by earthlng** [comment]
I don't understand why we should use the worst of the 3 possible ways. (see Atavic's comment)
Either use the shortest which sets a default (that I trust mozilla is not gonna change), or make it bullet-proof and use the long version. There are exploits that rely on a charset-missmatch and in the admittedly very unlikely case that the mozilla servers get hacked and could potentially abuse that, we wouldn't be vulnerable.
Yeah, I read the TBB ticket where they started using it, but they also don't want any console warnings/errors, and tbh it seemed kind of lazy. We shouldn't do something stupid just because TBB also does it. Maybe someone from their team will eventually see our better and improved way and change it in TBB too.
Just my 2 cents

**Comment by Roman-Nopantski** [comment]
But they never get used

**Comment by earthlng** [comment]
> But they never get used

Then why change them at all? But we do change them (and I think we should) so why not use the best possible way instead of the worst?
I'm not gonna argue anymore. I use the short form in my own user.js. Do what you want.

**Comment by Roman-Nopantski** [comment]
> Then why change them at all

Because like TBB, we cover our arses and futureproof. Now now, settle.
