### ISSUE TITLE
ToDo: Private Browsing PAF compare

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#183]
Take a look at [Private Browsing](https://portableapps.com/news/2017-07-26--private-browsing-by-portableapps.com-4.1-released) and compare preference differences. Bear in mind, that some of these are set internally by Firefox

:small_red_triangle_down: Prefs we don't have that exist in DXR and about:config

* [x] user_pref("browser.preferences.advanced.selectedTabIndex", 1);
   * WONTFIX: irrelevant, gets overwritten anyway
* [x] user_pref("browser.startup.homepage", "http://start.portableapps.com/");
   * WONTFIX: we could add this as `0103`, inactive with a value of `about:blank` maybe, but it's already mentioned in 0102. Also, I do not wish to mess with people's start pages.
* [x] user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
  * WONTFIX: hell no! default is 0, we have dataSubmission disabled, and 2 would mean we accepted Policy v2
* [x] user_pref("network.predictor.cleaned-up", true);
  * WONTFIX: probably irrelevant with network.predictor disabled ie nothing to clean up (Thorin, also I think this is set internally)
* [x] user_pref("plugin.importedState", true);
   * WONTFIX: all I see are [tests](https://dxr.mozilla.org/mozilla-central/search?q=plugin.importedState&redirect=false) .. the pref is deprecated, reset it
* [x] user_pref("privacy.sanitize.migrateFx3Prefs", true);
  * WONTFIX: https://dxr.mozilla.org/mozilla-central/search?q=migrateFx3Prefs - not actually used anywhere in nightly. It was still used in [ESR45](https://dxr.mozilla.org/mozilla-esr45/search?q=migrateFx3Prefs) and they probably just forgot to remove the pref. ESR52 already doesn't have the *real* code anymore
* [x] user_pref("browser.feeds.showFirstRunUI", false);
   * WONTFIX: it gets set internally by FF when you visit an RSS feed such as https://www.ghacks.net/feed/

:small_red_triangle_down: Prefs we don't have that exist in DXR but not about:config

* [x] user_pref("extensions.update.notifyUser", false);
   * WONTFIX: see comments below (deprecated old XUL legacy crap?)
* [x] user_pref("xpinstall.whitelist.add", "");
   * WONTFIX: see comments below (android only? testpilot only for now. No need to block)
* [x] user_pref("browser.feeds.handler.default", "bookmarks");
   * WONTFIX: see comments below
* [x] user_pref("browser.history_expire_days.mirror", 180);
   * WONTFIX: see comments below

:small_red_triangle_down: Prefs we have inactive

* [x] user_pref("app.update.enabled", false);
   * WONTFIX: we allow auto-check but block auto-install for a good balance (i.e 8 day reminder but manual update)
* [x] user_pref("extensions.update.enabled", false);
   * WONTFIX: we allow auto-check but block auto-install for a good balance
* [x] user_pref("network.cookie.lifetimePolicy", 0); // PB PAF: active with value: 2
   * WONTFIX: added for info, a value of 2 means clear cookies on close. This is already covered under items to clear on close (also inactive) and is at odds with block all, use an extension (whitelist, keep some, others session only=same as delete when close).
* [x] user_pref("browser.startup.page", 0);
   * WONTFIX: not messing with people's start pages
   * earthlng: I agree, inactive is fine (Thorin .. hey! we agree! holy shit :) )
* [x] user_pref("places.history.enabled", false);
   * someone once bitched about that we cleared his history on shutdown. IMO keeping this inactive is better (earthlng)
   * WONTFIX: agree with earthlng. It is extremely useful (forward/back etc) and we limit it to 10 per tab (down from 50). Its also cleared on close. This is a good balance. Users can always use some sort of cleaner extension or go all OCD like me and do a ctrl-shift-del every 10 minutes.
* [x] user_pref("browser.formfill.enable", false);
   * discussion on this taken to #186 

:small_red_triangle_down: Prefs we have active but a different value

* [x] user_pref("network.cookie.cookieBehavior", 2); // PB PAF: 1
   * This is debatable - no cookies (2) means no dom (without an extension or site exceptions) which means tons of the internet breaks, which is not good for a browser default to keep users. One issue I have is WebExts that use dom storage, you cannot set an exception for an extension - see eCleaner which fails to work at all. Personally I would rather block billions of cookies by default and work around WebExts. Value of 1 BTW means first party only.
   * Will open this as a new issue for discussion
* [x] user_pref("toolkit.telemetry.cachedClientID", "");
   // PB PAF: "4f09a401-a596-4868-9c22-7f4af9604292"
   * WONTFIX: we believe the ID stands for Identity xD

:small_red_triangle_down: The rest
The remaining 23 prefs are not in about:config (windows), not in DXR, not in our user.js (except three under our deprecated section), a couple of others we know are deprecated (eg `plugin.scan.SunJRE` went the same time as Acrobat etc, and `browser.sessionstore.enabled` was removed 8 years ago).

...

**Comment by Thorin-Oakenpants** [comment]
If you want to, earthlng. Just when you have time, no hurry. Always good to compare, maybe we'll find something, but I'm not hopeful - just pays to check

**Comment by Atavic** [comment]
Downloaded version 4.1 from Sourceforge. Prefs.js has 163 entries.

ghacksuserjs | PrivateBrowsing
------------ | -------------
... | user_pref("browser.cache.disk.filesystem_reported", 1);

It has adblockplus and flashblock.

**Comment by Thorin-Oakenpants** [comment]
`browser.cache.disk.filesystem_reported` is a cache observer set internally

So if that's all there is, then it offers nothing for us to pick up on

**Comment by Atavic** [comment]
It's an exe that requires firefox portable to work.

**Comment by earthlng** [comment]
I ran a nilla FF54.0.1 portable to get an untouched default prefs.js and compared that with the PB PAF prefs.js to get rid of all the prefs that are set by default anyway. Then I compared the rest with our latest master.js.
for starters IMHO it's a bit sloppy what they're doing, fe it has a bunch of `datareporting.sessions.*` prefs from the authors machine:
```js
user_pref("datareporting.sessions.previous.0", "{\"s\":1369764674505,\"a\":7,\"t\":40785,\"c\":true,\"m\":1874,\"fp\":3068,\"sr\":5719}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1369764714981,\"a\":2,\"t\":7191,\"c\":true,\"m\":696,\"fp\":2070,\"sr\":2117}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1369764726621,\"a\":5,\"t\":22364,\"c\":true,\"m\":55,\"fp\":1226,\"sr\":1246}");
// etc, etc, 15 or 16 of these in total
```
It also comes pre-configured with the authors `toolkit.telemetry.cachedClientID` and `security.sandbox.content.tempDirSuffix` which is probably not that great ;)

What remains is the following:
### prefs we don't have (or we have under deprecated):
```js
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.feeds.handler.default", "bookmarks");
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.places.createdDefaultQueries", true);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.startup.homepage", "http://start.portableapps.com/");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gfx.crash-guard.status.d3d11video", 2);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("plugin.default_plugin_disabled", false);
user_pref("plugin.importedState", true);
user_pref("plugin.scan.Acrobat", "999");
user_pref("plugin.scan.Quicktime", "999");
user_pref("plugin.scan.SunJRE", "999");
user_pref("plugin.scan.WindowsMediaPlayer", "999");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1390632291);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
```
### prefs that we have inactive by default
```js
user_pref("app.update.enabled", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.startup.page", 0);
user_pref("extensions.update.enabled", false);
user_pref("network.cookie.lifetimePolicy", 0); // PB PAF: active with value: 2
user_pref("places.history.enabled", false);
```
### active prefs with different values:
```js
user_pref("network.cookie.cookieBehavior", 2); // PB PAF: 1
user_pref("toolkit.telemetry.cachedClientID", ""); // PB PAF: "4f09a401-a596-4868-9c22-7f4af9604292"
```

**Comment by Thorin-Oakenpants** [comment]
OK .. so at some stage I guess we can trawl through these. I use portable (have done for IDK 4 or 5 years) .. there's very little set (like you said, the disk cache etc due to USB read/writes)

**Comment by Thorin-Oakenpants** [comment]
OT: speaking of data reporting sessions .. (well, those strings of numbers reminded me of this - https://trac.torproject.org/projects/tor/ticket/22919 - enjoy :)

**Comment by earthlng** [comment]
> I assume there's a whole heap of other prefs that match ours (wouldn't surprise me if they used our list)

No there isn't. I listed everything *important* from the prefs.js (= minus some timestamp + version info prefs, extension prefs etc.)

**Comment by Thorin-Oakenpants** [comment]
^^ Wow .. so many things controlled internally and they did almost nothing.

10 prefs : > EDIT: for completeness sake these are the prefs that match our values:
286 active prefs : > in the user.js up to 2800 inclusive minus the parrots

**Comment by earthlng** [comment]
> and they did almost nothing

instead they left the authors `toolkit.telemetry.cachedClientID` xD 🤦‍♂️ 
To be fair, maybe this is only the first version and they will improve and extend it a bit over time.

**Comment by Thorin-Oakenpants** [comment]
sheeshus ... I'm just going thru the items checking DXR to be thorough

They use `browser.sessionstore.enabled` which was deprecated back in 3.1a2. I have no respect for this project now, what little remained.

**Comment by earthlng** [comment]
Yeah, their prefs.js also still had gecko.mstone = 22 or something like that. I reckon most *semi*-interesting-looking prefs from my `prefs we don't have (or we have under deprecated):` list above, were removed/deprecated a long time ago

**Comment by Thorin-Oakenpants** [comment]
There's nothing here really, but I better tick them off and examine them properly. Feel free to chip in and edit the first post (if you hadn't already noticed it's overhaul). eg I'm 99% the rest of the first section is all set internally.

I also wanted to address form history. Personally, I use history a fair bit in the search bar to save me typing (nothing auto searches - I can select the text using up down keys but not hit enter). Other than that, I also clear forms/history/cache etc (ctrl-shift-del) maybe every 10 or 15 minutes - its like an OCD thing now :) man I'm fukked up due to the internet - thanks Obama!

**Comment by Thorin-Oakenpants** [comment]
browser.feeds.showFirstRunUI - for a laugh I reset mine (it was set as false at some stage by Firefox itself). It's a hidden pref. DXR: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser-feeds.js#13

**Comment by Thorin-Oakenpants** [comment]
`datareporting.policy.dataSubmissionPolicyAcceptedVersion` - mine is user set at a value of 2. I didn't do it, I guess FF did it internally at some stage. Moot point, we don't allow any telemetry of any sort because we kill the urls.

I reset it (to default 0), and had a play with Options>Advanced>Data Choices but couldn't seem to trigger it. I also clicked on and loaded the "Learn More" links, as the pref "records the version of the policy notified to the user" (see [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/docs/internals/preferences.rst#92) ). However it is set/triggered (note my datareporting.policy.currentPolicyVersion is 2 by default) it doesn't do anything (for us) IMO- but I was intrigued :)

**Comment by Thorin-Oakenpants** [comment]
`plugin.importedState` - all I see are [some tests](https://dxr.mozilla.org/mozilla-central/search?q=plugin.importedState&redirect=false) .. the pref is deprecated, reset it (I did) and it will vanish

**Comment by Thorin-Oakenpants** [comment]
`extensions.update.notifyUser` was introduced in FF 1.8.1beta1  (ahh the good old pre-australis days :trollface:  ) with [307358](https://bugzilla.mozilla.org/show_bug.cgi?id=307358). FYI here is the [DXR](https://dxr.mozilla.org/mozilla-central/search?q=extensions.update.notifyUser&redirect=false). Al I see are tests and marionette and addon sdk - I do not think it is used anymore (?).

**Comment by Thorin-Oakenpants** [comment]
[DXR](https://dxr.mozilla.org/mozilla-central/search?q=xpinstall.whitelist.add&redirect=false) for `xpinstall.whitelist.add` (default is value "https://addons.mozilla.org,https://testpilot.firefox.com") looks like it's only used on Android. No need to block this

**Comment by Thorin-Oakenpants** [comment]
[DXR](https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/in-content-new/main.js#44) for `browser.feeds.handler.default` - we can ignore this.

**Comment by Thorin-Oakenpants** [comment]
[DXR](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/places/Database.cpp#1969) for `browser.history_expire_days.mirror` - its not used

```js
  // Remove some old and no more used Places preferences that may be confusing
  // for the user.
  mozilla::Unused << Preferences::ClearUser("places.history.expiration.transient_optimal_database_size");
  mozilla::Unused << Preferences::ClearUser("places.last_vacuum");
  mozilla::Unused << Preferences::ClearUser("browser.history_expire_sites");
  mozilla::Unused << Preferences::ClearUser("browser.history_expire_days.mirror");
  mozilla::Unused << Preferences::ClearUser("browser.history_expire_days_min");
```

**Comment by Thorin-Oakenpants** [comment]
`network.cookie.cookieBehavior` is moved to #188

**Comment by Thorin-Oakenpants** [comment]
PS: thanks @Atavic and @earthlng for completing this task for me :trollface:
