### ISSUE TITLE
ToDo: Telemetry prefs

### ISSUE THREAD

**Issue by grauenwolfe** [ghacksuserjs/ghacks-user.js#187]
Came across this earlier this morning which lists many Telemetry prefs that I've never seen before. Cross-checked with DXR and they are indeed there. I'm left to assume that they're more hidden prefs, which I'm not very fond of. Anyway, could be nothing but what do you guys think? Inconsequential?

https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/internals/preferences.html

--

[Edit, also note from 57 nightly]
- app.update.lastUpdateTime.telemetry_modules_ping
- browser.newtabpage.activity-stream.feeds.telemetry
- browser.newtabpage.activity-stream.telemetry
- browser.newtabpage.activity-stream.telemetry.log
- browser.newtabpage.activity-stream.telemetry.ping.endpoint
- devtools.telemetry.supported_performance_marks
- devtools.telemetry.tools.opened.version
- toolkit.telemetry.debugSlowSql
- toolkit.telemetry.previousBuildID
[end edit]

Lets itemize this sucker...

### Preferences

* [x] toolkit.telemetry.log.level - `default log to console only is fine - no action needed`
  This sets the Telemetry logging verbosity per Log.jsm, with Trace or 0 being the most verbose and the default being Warn. By default logging goes only the console service.
* [x] toolkit.telemetry.log.dump - `off by default, log only to console see above - no action needed`
  Sets whether to dump Telemetry log messages to stdout too.
* [x] toolkit.telemetry.shutdownPingSender.enabledFirstSession - `nothing to see, move along`
  Allow the shutdown ping to be sent using the ping sender from the first browsing session.
* [x] toolkit.telemetry.newProfilePing.delay - `is just a timer and covered by toolkit.telemetry.newProfilePing.enabled in 0330`
  Controls the delay after which the ../data/new-profile is sent on new profiles.
* [x] toolkit.telemetry.updatePing.enabled - `see my last` [comment](https://github.com/ghacksuserjs/ghacks-user.js/issues/187#issuecomment-321032174)
  Enable the “update” ping on browser updates.
* toolkit.telemetry.unified - `0330`
   This controls whether unified behavior is enabled. If true:
   > Telemetry is always enabled and recording base data. Telemetry will send additional main pings.
* toolkit.telemetry.enabled - `0330`
  If unified is off, this controls whether the Telemetry module is enabled. If unified is on, this controls whether to record extended data. This preference is controlled through the Preferences dialog.
  Note that the default value here of this pref depends on the define RELEASE_OR_BETA and the channel. If RELEASE_OR_BETA is set, MOZ_TELEMETRY_ON_BY_DEFAULT gets set, which means this pref will default to true. This is overridden by the preferences code on the “beta” channel, the pref also defaults to true there.
* datareporting.healthreport.uploadEnabled - `0333a`
  Send the data we record if user has consented to FHR. This preference is controlled through the Preferences dialog.
* toolkit.telemetry.archive.enabled `0330`
  Allow pings to be archived locally. This can only be enabled if unified is on.
* toolkit.telemetry.server - `0330`
  The server Telemetry pings are sent to.
* toolkit.telemetry.shutdownPingSender.enabled - `0330`
  Allow the shutdown ping to be sent when the browser shuts down, from the second browsing session
on, instead of the next restart, using the ping sender.
* toolkit.telemetry.newProfilePing.enabled - `0330`
  Enable the ../data/new-profile ping on new profiles.

### Data-choices notification

Thorin says: These are just notifications, timestamps, policy versions, etc. Internals, nothing to do with actual collection and sending of said data ,and they can all be ignored IMO (except  `0334` at the end which we have covered)

* [x] toolkit.telemetry.reportingpolicy.firstRun
  This preference is not present until the first run. After, its value is set to false. This is used to show the infobar with a more aggressive timeout if it wasn’t shown yet.
* [x] datareporting.policy.firstRunURL
  If set, a browser tab will be opened on first run instead of the infobar.
* [x] datareporting.policy.dataSubmissionPolicyNotifiedTime
  Records the date user was shown the policy. This preference is also used on Android.
* [x] datareporting.policy.dataSubmissionPolicyAcceptedVersion
  Records the version of the policy notified to the user. This preference is also used on Android.
* [x] datareporting.policy.dataSubmissionPolicyBypassNotification
  Used in tests, it allows to skip the notification check.
* [x] datareporting.policy.currentPolicyVersion
  Stores the current policy version, overrides the default value defined in TelemetryReportingPolicy.jsm.
* [x] datareporting.policy.minimumPolicyVersion
  The minimum policy version that is accepted for the current policy. This can be set per channel.
* [x] datareporting.policy.minimumPolicyVersion.channel-NAME
  This is the only channel-specific version that we currently use for the minimum policy version.
* datareporting.policy.dataSubmissionEnabled - `0334`
  This is the data submission master kill switch. If disabled, no policy is shown or upload takes place, ever.

### Testing [Ignore these]

The following prefs are for testing purpose only.

- toolkit.telemetry.initDelay
  Delay before initializing telemetry (seconds).
- toolkit.telemetry.minSubsessionLength
  Minimum length of a telemetry subsession and throttling time for common environment changes (seconds).
- toolkit.telemetry.collectInterval
  Minimum interval between data collection (seconds).
- toolkit.telemetry.scheduler.tickInterval
  Interval between scheduler ticks (seconds).
- toolkit.telemetry.scheduler.idleTickInterval
  Interval between scheduler ticks when the user is idle (seconds).
- toolkit.telemetry.idleTimeout
  Timeout until we decide whether a user is idle or not (seconds).
- toolkit.telemetry.modulesPing.interval
  Interval between “modules” ping transmissions.
- toolkit.telemetry.send.overrideOfficialCheck
  If true, allows sending pings on unofficial builds. Requires a restart.
- toolkit.telemetry.healthping.enabled
  If false, sending health pings is disabled. Defaults to true.

...

**Comment by Thorin-Oakenpants** [comment]
Lets itemize this sucker...

### Preferences

- toolkit.telemetry.unified
   This controls whether unified behavior is enabled. If true:
   > Telemetry is always enabled and recording base data. Telemetry will send additional main pings.
- toolkit.telemetry.enabled
  If unified is off, this controls whether the Telemetry module is enabled. If unified is on, this controls whether to record extended data. This preference is controlled through the Preferences dialog.
  Note that the default value here of this pref depends on the define RELEASE_OR_BETA and the channel. If RELEASE_OR_BETA is set, MOZ_TELEMETRY_ON_BY_DEFAULT gets set, which means this pref will default to true. This is overridden by the preferences code on the “beta” channel, the pref also defaults to true there.
- datareporting.healthreport.uploadEnabled
  Send the data we record if user has consented to FHR. This preference is controlled through the Preferences dialog.
- toolkit.telemetry.archive.enabled
  Allow pings to be archived locally. This can only be enabled if unified is on.
- toolkit.telemetry.server
  The server Telemetry pings are sent to.
- toolkit.telemetry.log.level
  This sets the Telemetry logging verbosity per Log.jsm, with Trace or 0 being the most verbose and the default being Warn. By default logging goes only the console service.
- toolkit.telemetry.log.dump
  Sets whether to dump Telemetry log messages to stdout too.
- toolkit.telemetry.shutdownPingSender.enabled
  Allow the shutdown ping to be sent when the browser shuts down, from the second browsing session on, instead of the next restart, using the ping sender.
- toolkit.telemetry.shutdownPingSender.enabledFirstSession
  Allow the shutdown ping to be sent using the ping sender from the first browsing session.
- toolkit.telemetry.newProfilePing.enabled
  Enable the ../data/new-profile ping on new profiles.
- toolkit.telemetry.newProfilePing.delay
  Controls the delay after which the ../data/new-profile is sent on new profiles.
- toolkit.telemetry.updatePing.enabled
  Enable the “update” ping on browser updates.

### Data-choices notification

- toolkit.telemetry.reportingpolicy.firstRun
  This preference is not present until the first run. After, its value is set to false. This is used to show the infobar with a more aggressive timeout if it wasn’t shown yet.
- datareporting.policy.firstRunURL
  If set, a browser tab will be opened on first run instead of the infobar.
- datareporting.policy.dataSubmissionEnabled
  This is the data submission master kill switch. If disabled, no policy is shown or upload takes place, ever.
- datareporting.policy.dataSubmissionPolicyNotifiedTime
  Records the date user was shown the policy. This preference is also used on Android.
- datareporting.policy.dataSubmissionPolicyAcceptedVersion
  Records the version of the policy notified to the user. This preference is also used on Android.
- datareporting.policy.dataSubmissionPolicyBypassNotification
  Used in tests, it allows to skip the notification check.
- datareporting.policy.currentPolicyVersion
  Stores the current policy version, overrides the default value defined in TelemetryReportingPolicy.jsm.
- datareporting.policy.minimumPolicyVersion
  The minimum policy version that is accepted for the current policy. This can be set per channel.
- datareporting.policy.minimumPolicyVersion.channel-NAME
  This is the only channel-specific version that we currently use for the minimum policy version.

### Testing

The following prefs are for testing purpose only.

- toolkit.telemetry.initDelay
  Delay before initializing telemetry (seconds).
- toolkit.telemetry.minSubsessionLength
  Minimum length of a telemetry subsession and throttling time for common environment changes (seconds).
- toolkit.telemetry.collectInterval
  Minimum interval between data collection (seconds).
- toolkit.telemetry.scheduler.tickInterval
  Interval between scheduler ticks (seconds).
- toolkit.telemetry.scheduler.idleTickInterval
  Interval between scheduler ticks when the user is idle (seconds).
- toolkit.telemetry.idleTimeout
  Timeout until we decide whether a user is idle or not (seconds).
- toolkit.telemetry.modulesPing.interval
  Interval between “modules” ping transmissions.
- toolkit.telemetry.send.overrideOfficialCheck
  If true, allows sending pings on unofficial builds. Requires a restart.
- toolkit.telemetry.healthping.enabled
  If false, sending health pings is disabled. Defaults to true.

...

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe - we have telemetry locked down AFAIK. Nothing is being recorded to disk (I have checked - real time monitoring - no crash reports, no health reports, no archived pings), and we certainly have no data being sent back to Mozilla that is not already controlled/explained (eg auto-update checks for app/add-ons, kinto checks etc). Especially when it has no idea where to send it (URLs are blanked). Been about a year, but I checked how quiet FF was with wireshark .. (back when TP+SB+auto-update checks were off) and it never made a single outbound connection over several hours (I left it idle and jumped around the UI for a while).

That said ... always good to go thru lists like this, but I suspect that there is nothing there to worry about

**Comment by Thorin-Oakenpants** [comment]
Two items left:

- `toolkit.telemetry.shutdownPingSender.enabledFirstSession` I think we can ignore - assuming this is just for a new profile first ever session
- `toolkit.telemetry.updatePing.enabled` might be good to add - not sure if covered by the two master switches

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe I asked you a Q about system add-ons - I'll repeat it here since I have your attention

> @grauenwolfe Can you please tell me where on a Mac are system add-ons stored?
> 
> FYI
> * Portable
>    * "...\App\Firefox64\browser\features\" (or "App\Firefox\etc" for 32bit)
> * Windows
>    * "...\Program Files\Mozilla\browser\features" (or "Program Files (X86)\etc" for 32bit)
> 
> At the very least you should have an `aushelper@mozilla.org.xpi` file (in case you want to search for it)

**Comment by grauenwolfe** [comment]
> @grauenwolfe - we have telemetry locked down AFAIK. Nothing is being recorded to disk (I have checked - real time monitoring - no crash reports, no health reports, no archived pings)...

This is what I suspected but a lot of you guys have greater depth of knowledge than I do.

> @grauenwolfe I asked you a Q about system add-ons - I'll repeat it here since I have your attention...

Never even saw this question, sorry about that.

Mozilla's own internal Firefox add-ons:
/Applications/Firefox**/Contents/Resources/browser/features

Only exception is the "Lightweight themes" add-on:
/Applications/Firefox**/Contents/Resources/browser/extensions

User installed add-ons default install location:
/Users/_user account name_/Library/Application Support/Firefox/Profiles

[**_On Mac you to right-click on the application (Firefox.app) then select "Show Package Contents" to access these files._]

**Comment by Theemim** [comment]
Not sure how comprehensive you want this to be, but from FF57 nightly:
```
app.update.lastUpdateTime.telemetry_modules_ping
browser.newtabpage.activity-stream.feeds.telemetry
browser.newtabpage.activity-stream.telemetry
browser.newtabpage.activity-stream.telemetry.log
browser.newtabpage.activity-stream.telemetry.ping.endpoint
devtools.telemetry.supported_performance_marks
devtools.telemetry.tools.opened.version
toolkit.telemetry.debugSlowSql
toolkit.telemetry.previousBuildID
```

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info on System Add-ons - I'll add the info to the js later. Comprehensive - no worries. We'll scope those out, but if they're new wew ould pick up on them from diffs for stable. Some of those for 57 might be specifically for Nightly, we'll have to check. The newtab ones look interesting

**Comment by Thorin-Oakenpants** [comment]
> It takes some massaging to diff against markdown

Great to know you're around for when I fire earthlng :trollface:  #RussiaGate

**Comment by grauenwolfe** [comment]
Quick question regarding: 

    0330: toolkit.telemetry.cachedClientID

I don't have an entry for this so I'm guessing that it's either (A) been deleted since there's no Telemetry data to associate it with or (B) it's hidden and just not marked as such. Also curious why it's on DXR but nowhere on Mozilla Source Tree Docs. I'm not particularly concerned, just curious.

**Comment by Theemim** [comment]
theemimDiff != earthlngDiff

https://gecko.readthedocs.io/en/latest/search.html?q=%22client+id%22

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe I think `toolkit.telemetry.cachedClientID` is set internally [ClientID.jsm](https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/ClientID.jsm). You may not have one because its never been triggered - proactively blanking it covers your butt (not that Mozilla would use it except for anonymized telemetry)

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe So does this look ok (last two lines to be added to the user.js). thumbs up if its all good

```js
/***
     Some system add-ons have no on-off prefs. Instead you can manually remove them. Note that app
     updates will restore them. They may also be updated and possibly restored automatically (see 0505)
     * Portable: "...\App\Firefox64\browser\features\" (or "App\Firefox\etc" for 32bit)
     * Windows: "...\Program Files\Mozilla\browser\features" (or "Program Files (X86)\etc" for 32bit)
     * Mac: "...\Applications\Firefox\Contents\Resources\browser\extensions\"
       [NOTE] On Mac you can right-click on the application and select "Show Package Contents"
***/
```

**Comment by grauenwolfe** [comment]
@Thorin-Oakenpants The Mac info for **system** add-ons in the user.js should be:

`/Applications/Firefox/Contents/Resources/browser/features`

This is where pocket, aushelper, webcompat, and all that other shit is located.

The directory you listed only contains the "Lightweight themes" add-on and probably isn't really worth mentioning in the user.js other than sheer thoroughness.

In other words,  just change `/extensions` to `/features`.

**Comment by Thorin-Oakenpants** [comment]
Thanks @grauenwolfe  - copypasta'd the wrong line. I think I'm overworked

**Comment by Thorin-Oakenpants** [comment]
@earthlng 

What is your take on wrapping this issue up

 - `toolkit.telemetry.updatePing.enabled`
   * I looked all over the telemetry jsms etc, followed code as best I could. I cannot work out if this respects the master switches, but as far as i'm concerned, it cannot archive them locally to send later, and it cannot send them because it has no url, so i think we can ignore it
- `toolkit.telemetry.shutdownPingSender.enabledFirstSession`
   * first session ping? after a new install/profile? I think we can ignore this
- a couple of "testing" prefs look dodgy
- items listed from 57 nightly - should we just wait until we pick up on them in diffs?

Question: when you do your diffs, do you include all the system addons?

**Comment by Thorin-Oakenpants** [comment]
!bump

go to about:telemetry and everything should be disabled and zero data collection

I think I can close this - yes/no?

**Comment by earthlng** [comment]
> Question: when you do your diffs, do you include all the system addons?

No, none of the prefs that SA's or FF itself sets during runtime are included in my diffs. If you want that info you can use @Theemim's script

**Comment by Thorin-Oakenpants** [comment]
I only asked because of

> browser.newtabpage.activity-stream.feeds.telemetry
browser.newtabpage.activity-stream.telemetry
browser.newtabpage.activity-stream.telemetry.log
browser.newtabpage.activity-stream.telemetry.ping.endpoint

but we disable newtabpage anyway

**Comment by KOLANICH** [comment]
I just leave this link here: https://dxr.mozilla.org/mozilla-central/source/modules/libpref/Preferences.cpp#3213
