### ISSUE TITLE
ToDo: create RFP Alternative [inactve] section[s]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#222]
These items are ALL redundant and some could even clash with how RFP works (depending exactly how they coded each one). The determination for `clash` below is based on their method only, not code (RFP or pref entanglement). Even items we think are redundant, may have an effect (in future). These items would form the basis of a RFP alternative section, and be made inactive. It is important that RFP behaves as expected with consistent responses across users.

:small_red_triangle_down: FF55
* [x] [1360039](https://bugzilla.mozilla.org/show_bug.cgi?id=1360039) - spoof navigator.hardwareConcurrency as 2 (`also see 2514`) (FF55+)
   * Redundant at best, clash at worst: there may be some difference - dom/navigator?

:small_red_triangle_down:  FF56
* [x] [1369303](https://bugzilla.mozilla.org/show_bug.cgi?id=1369303) - spoof/disable performance API (`see 2410-deprecated, 2411, 2412`) (FF56+)
   * Redundant: resource (pref 2411) and user timing (pref 2410-deprecated) are disabled
   * :x: Clash: RFP -> Performance is spoofed to zero but 2412 disables the API
* [x] [1333651](https://bugzilla.mozilla.org/show_bug.cgi?id=1333651) - spoof Navigator API (`see section 2697`) (FF56+)
   * Redundant: RFP solution is superior making 2697 entirely redundant, not that we use it
* [x] [1369319](https://bugzilla.mozilla.org/show_bug.cgi?id=1369319) - disable device sensor API (`see 2512`) (FF56+)
   * Redundant: same effect: RFP blocks events, 2512 disables the API
* [x] [1369357](https://bugzilla.mozilla.org/show_bug.cgi?id=1369357) - disable site specific zoom (`see 2515`) (FF56+)
   * Redundant: same effect
* [x] [1337161](https://bugzilla.mozilla.org/show_bug.cgi?id=1337161) - hide gamepads from content (`see 2501`) (FF56+) - https://github.com/ghacksuserjs/ghacks-user.js/commit/b6533689cfcccd8932467c408d70b35c340fa5ff
   * :x: Clash: RFP hides gamepads (returns empty array, just like if you never had one plugged in) whereas 2501 disables the API
* [x] [1372072](https://bugzilla.mozilla.org/show_bug.cgi?id=1372072) - spoof network information API as "unknown" (`see 2503`) (FF56+)
  * :x: Clash: RFP returns "unknown", 2503 it is undefined
* [x] [1372069](https://bugzilla.mozilla.org/show_bug.cgi?id=1372069) - disable geolocation API (`see 0201`) (FF56+)
   * :x: Clash: see [1403813](https://bugzilla.mozilla.org/show_bug.cgi?id=1403813)
* [x] [1333641](https://bugzilla.mozilla.org/show_bug.cgi?id=1333641) - reduce fingerprinting in WebSpeech API (`see 2021`) (FF56+) - https://github.com/ghacksuserjs/ghacks-user.js/commit/bb2325cad29ae411e500b08e9e24f6d627ca13b1
   * :x: Clash: RFP returns empty, blocks, and spoofs etc (see [1333641#c8](https://bugzilla.mozilla.org/show_bug.cgi?id=1333641#c8)), whereas 2021 disables the API

:small_red_triangle_down:  FF57
* [x] [1369309](https://bugzilla.mozilla.org/show_bug.cgi?id=1369309) - spoof media statistics (`see 2506`) (FF57+) - https://github.com/ghacksuserjs/ghacks-user.js/commit/b6533689cfcccd8932467c408d70b35c340fa5ff
   * :x: Clash: RFP spoofs media stats (dynamically if needed) whereas 2506 disables the API
* [x] [1382499](https://bugzilla.mozilla.org/show_bug.cgi?id=1382499) - reduce screen co-ordinate fingerprinting in Touch API (`see 2509`) (FF57+)
   * :x: Clash: RFP for touch API minimises/spoofs values whereas 2509 disables the API
* [x] [1217290](https://bugzilla.mozilla.org/show_bug.cgi?id=1217290) - enable fingerprinting resistance for WebGL (`see 2010-12`) (FF57+)
   * :x: Clash: definitely not the same as disabling WebGL outright. We will have to decide come 57 stable what to do with prefs `2010-12`
* [x] [1382533](https://bugzilla.mozilla.org/show_bug.cgi?id=1382533) - enable fingerprinting resistance for Presentation API (see `2513`) (FF57+)
   * Redundant at best: AFAICT it has the same affect as disabling the API by blocking requests etc

### Ignore these <sup>These items have no pref equivalent</sup>

* [418986](https://bugzilla.mozilla.org/show_bug.cgi?id=418986) - limit window.screen
* [1281949](https://bugzilla.mozilla.org/show_bug.cgi?id=1281949) - spoof screen orientation (FF50+)
* [1281963](https://bugzilla.mozilla.org/show_bug.cgi?id=1281963) - hide the contents of navigator.plugins and navigator.mimeTypes (FF50+)
* [1330890](https://bugzilla.mozilla.org/show_bug.cgi?id=1330890) - spoof timezone as UTC 0 (FF55+)
* [1217238](https://bugzilla.mozilla.org/show_bug.cgi?id=1217238) - reduce precision of time exposed by javascript (FF55+)
* [1382545](https://bugzilla.mozilla.org/show_bug.cgi?id=1382545) - reduce fingerprinting in Animation API (FF57+)
 * [1354633](https://bugzilla.mozilla.org/show_bug.cgi?id=1354633) - limit MediaError.message to a whitelist (FF57+)

### reminder <sup>after checking RFP wording, creating sections etc</sup>

* [x] update readme in user.js to re ESR & deprecated & non-RFP alts and resetting prefs in about:config
* [x] update wiki implementation - ^^ditto

...

**Comment by earthlng** [comment]
> 1337161 - disable gamepad API (see 2501) (FF56+)

Setting `dom.gamepad.enabled` to false disables the API and can be detected.
Starting with FF56, resistFingerprinting will provide a better solution by not disabling the API and instead "hiding" any connected gamepads from websites:
1. navigator.getGamepads() will always return an empty array
2. gamepadconnected and gamepaddisconnected events will not be fired

ps. "disable gamepad API" is incorrect because that's not what the patch does.

https://bugzilla.mozilla.org/show_bug.cgi?id=1337161#c2
https://bugzilla.mozilla.org/show_bug.cgi?id=1337161#c3
https://hg.mozilla.org/mozilla-central/rev/41a148dc837d

> 1369309 - spoof media statistics to 0 (see 2506) (FF57+)

they don't spoof to 0, see part 3 of that bug @ https://hg.mozilla.org/mozilla-central/rev/9afd71d7438c

When 57 lands we should probably add a note to `media.video_stats.enabled` and make it inactive.
People who don't want to use resistFingerprinting and/or ESR users can activate it in their own copies.

**Comment by Thorin-Oakenpants** [comment]
> When 57 lands we should probably add a note to

Screw all that. When 59 lands, we can make the stuff covered by resistFP => inactive, end of story (less breakage or same result), since ESR will have caught up. However, they fubars those hanging out until EOL ESR 52.x

As for what the zillas say, we'll have to pay more attention to what they eventually code (my fault at times) - they often change. Sometimes I pick them up, sometimes I don't. I see now that despite the patch names etc they actually went ahead with different values for various items rather than a blanket 0 (for 1369309)

> The three prefs are 'privacy.resistFingerprinting.video_frames_per_sec', 'privacy.resistFingerprinting.video_dropped_ratio' and 'privacy.resistFingerprinting.target_video_res'. The default values of them are 30, 5 and 480, which means 30 frames per second, 5 percent dropped ratio and 480p.

^^ Hidden prefs, no need to add, but interesting, so they can tweak it down the track. I never play video anyway .. unless it's m00sie porn

PS: Spoofing UA will revert to matching ESR .. good times

**Comment by Thorin-Oakenpants** [comment]
~~Maybe we need to create a section next to resistFP that is inactive as per release, with everything covered by resistFP - with a one char switch - so those on ESR can flip it on, and those on stable can ignore it?~~ that's so messy, I typed up a sample

Maybe we need to make prefs that are now covered INACTIVE, and simply add a note in 2699 that if you are on ESR 52.x you need to turn these pref numbers on (2506, 2021, 0201, 2503, etc)

Because seriously, now these are becoming built in, some of the solutions are far better and provide less breakage - eg video stats, gamepad, touch, network info (the old pref disabled, this one I think this returns "none", RFP returns "unknown") = spoof rather than disable. Big difference. Also WebGL looks like it could be OK now. We need to get on board with what resistFP does



```js
/*** 2699: privacy.resistFingerprinting
IMPORTANT: If you are on ESR 52.x, you need to un-comment out the following prefs blah blah
```

^^ thoughts. Because seriously, I now want to flip off the stuff covered by RFP

**Comment by Thorin-Oakenpants** [comment]
example tag/method
```js
/* 2501: disable gamepad API - USB device ID enumeration ***/
   // user_pref("dom.gamepad.enabled", false); // [COVERED BY privacy.resistFingerprinting FF56+]

/* 2506: disable video statistics ***/
   // user_pref("media.video_stats.enabled", false); // [COVERED BY privacy.resistFingerprinting FF57+]

/* 2512: disable device sensor API ***/
   // user_pref("device.sensors.enabled", false); // [COVERED BY privacy.resistFingerprinting FF56+]

/* 2515: disable site specific zoom ***/
   // user_pref("browser.zoom.siteSpecific", false);  // [COVERED BY privacy.resistFingerprinting FF56+]
```

etc, and users can simply search for "[covered by" to turn them back on? and to find them and make sure they are reset in about:config? What do you think?

**Comment by Thorin-Oakenpants** [comment]
^^ you'll have to scroll the content, the FF version is included in each tag to make it easy

**Comment by Thorin-Oakenpants** [comment]
^^ or we could just add an `[ENABLE IF ON ESR 52.x]`

**Comment by Theemim** [comment]
Do those prefs being active have any ill effects when privacy.resistFingerprinting is enabled?  Some may not enable RFP because they don't see it enabled by default (is code ready for prime time?).  Some may disable it if they run into a problem.  Doesn't matter if they are ESR or not.  If you decide to make the covered prefs inactive, maybe the note shouldn't be ESR specific?

BTW, one question I haven't looked into (but maybe you already know): does disabling the geolocation API prevent the backend communication with the geolocation provider?

**Comment by Thorin-Oakenpants** [comment]
I do not know for sure.
- Some are the same in effect eg 1369319 - disable device sensor API = 2512 = device.sensors.enabled = false
- For those that do something different, it would depend how they coded them . One would think, for example, that an API disable would trump a spoof value. eg 2506 disables the media stats API, so therefore the spoof values from resistFP shouldn't even get asked for
- Hence all the more reason to comment out (and reset) items now covered as per the release you are on.
- Meaning that the current js is marked v55, so nothing to do, but for 56 we would need to comment out prefs covered as FF56+ in RFP, add tags to those prefs, add a warning or something somewhere
- ESR is making life harder and messier, damnitt, we need an elegant solution.

---
Re Geo: I am not sure. See this comment - https://www.ghacks.net/2017/08/22/firefox-55-new-preferences-and-ghacks-user-js-changes/#comment-4221989 re the URL pref

> It should probably be removed from the user.js if we confirm that its not used anywhere else and is fully controlled by the `geo.enabled` as a master switch (like we did that removing some dead weight with a bunch of VR and pocket prefs). I'll keep that in mind 

We'd have to look at the code to see what else uses the API. The resistFP patch says it "disables" it  - whether than means block (and only for content) rather than disable the API, we are going thru the items now. That said, I would think if you kill the URL you'd be safe - fallback for fallout.

**Comment by 2glops** [comment]
FF56+
privacy.resistFingerprinting = true and all relative prefs inactive
User could make RFP false and activate only some relative prefs (yes, it loose benefits from RFP, user choice), 

ESR52+
User should have an easy way to find and activate all prefs handled by RFP.

From that, I don't see a solution for stable / ESR users to avoid resetting / uncommenting from about:config / user.js. A master could not fits all without user action.

[COVERED BY 2699 FF56+] : Good to see imediately the section number.

How will all prefs covered by RFP be handled after the end of ESR 52 series ? Inactive with a note "covered by RFP" or ignored and flipped out the user.js ?

**Comment by Thorin-Oakenpants** [comment]
^^ See :exclamation: `Step 4` in the first post. Before we decide anything, we need to confirm if there are any issues - i.e code inspection time! !find earthlng!. How do we know if the previous existing prefs have any effect, or that they clash. We do this after we confirm exactly what RFP does.

If there is an issue, then I actually believe the Tor Uplift should fix it in code, since it is meant to ENFORCE a same set of users .. cogito ergo sum .. we shouldn't have to do anything and we can leave it as is

**Comment by Thorin-Oakenpants** [comment]
> How will all prefs covered by RFP be handled after the end of ESR 52 series

Just like normal. If you are on ESR52 you won't get any benefits from RFP FF53+ or higher items. If on ESR59, you won't get any benefits from RFP FF60+ or higher items. The Tor Uplift will keep going for a long long time.

All the user.js needs to do is tag the version, and alert people to the tags. They can easily work out what to do from their own FF release, regardless of what it is.

Stable users should be able to just use the default js as is per release number. Nightly may have a couple of prefs active in common/clashing. It's just ESR users that it gets messy really. However, it **may** just be a few items that clash or can be made inactive (eg enable touch since co-ordinates are rounded/limited)

I'm thinking a tag as suggested, a note in 2699 header, and a warning/note in the user.js header for ESR users

**Comment by Thorin-Oakenpants** [comment]
@Theemim 
> maybe the note shouldn't only mention ESR

Absolutely. Users on stable still need to know what to reset in about:config

**Comment by savyajha** [comment]
I'm not sure if this would be a consideration, but [this issue](https://github.com/pyllyukko/user.js/issues/334#issuecomment-324219878) is caused by `privacy.resistFingerprinting` being true. This is a bit of a bummer, because while I like security, I love performance. If possible, it would be great if we can find a way to get each part of the master switch working.

**Comment by earthlng** [comment]
> Users on stable still need to know what to reset in about:config

we could highlight that in the changelogs IMO

For now I like your super early edit/draft but maybe over time it would be better to move them all to a new section and group them together similar to what we do in the deprecated section, with groups for each release and super-groups for ESR versions. I also think at a certain point RFP will have so many benefits that we no longer should cater for non-RFP users and simply remove the obsoleted prefs, for example when ESR52 reaches EOL.

**Comment by 2glops** [comment]
1369319 - disable device sensor API (see 2512) (FF56+)
Provide the similar behavior as 'device.sensors.enabled' = false (checked on Nightly)
So, with RFP = true :
  // user_pref("device.sensors.enabled", false);

**Comment by Thorin-Oakenpants** [comment]
> For now I like your super early edit/draft but maybe over time it would be better to move them all to a new section and group them together similar to what we do in the deprecated section, with groups for each release and super-groups for ESR versions. I also think at a certain point RFP will have so many benefits that we no longer should cater for non-RFP users and simply remove the obsoleted prefs, for example when ESR52 reaches EOL.

No time like the present - it would apply FOREVER .. i.e it would still apply after 59 lands, so users who do not want RFP can still tighten up. I actually typed up a draft to see what it would look like, but abandoned it. Its gets messy.

Two ways
- Section FPI and Section FPI Alternatives.
- Section FPI with alternatives sandwiched under bugzilla

**Comment by Thorin-Oakenpants** [comment]
>I'm not sure if this would be a consideration, but [this issue](https://github.com/pyllyukko/user.js/issues/334#issuecomment-324219878) is caused by `privacy.resistFingerprinting` being true. This is a bit of a bummer, because while I like security, I love performance. If possible, it would be great if we can find a way to get each part of the master switch working.

@savyajha - log a bugzilla. I am sure they will want to know about this. You have a replicable bug and no-one wants jank. There are more timing mitigations to come - animation API (landed), [This one](https://bugzilla.mozilla.org/show_bug.cgi?id=1393662), and I could have sworn there was another performance API somewhere being looked at

**Comment by Thorin-Oakenpants** [comment]
Lets Finish Step 1 (+2 if required). Lets not TAG stuff all over the place. I'm sold on the idea now of a companion RFP ALTernative section. No need to tag things, easy for RFP users + non RFP users + ESR users to find and action (yes we have the changelog, but its important for the info to be in the js). Once changes are FF60+, we simply create another one char switch section and keep going

--

2697: USER AGENT (UA) SPOOFING
2698: FIRST PARTY ISOLATION (FPI)
2699: privacy.resistFingerprinting
^^ renumber these, add in privacy.resistFingerprinting ALTERNATIVES

suggest

4000: privacy.resistFingerprinting
4001: privacy.resistFingerprinting ALTERNATIVES
4002: USER AGENT (UA) SPOOFING
4003: FIRST PARTY ISOLATION (FPI)
+ shove personal out to 5000

----

experimental draft (with the section flipped on for effect), line spaces would not be there, also I stripped a lot of extra info for this "example"
```js
/*** 4001: privacy.resistFingerprinting ALTERNATIVES [SETUP]
   * IF you USE privacy.resistFingerprinting (see 4000) then you do NOT need these
     prefs, some may even cause privacy.resistFingerprinting to not behave as you
     would expect. Make sure they are reset in about:config as per your Firefox version
   * IF you DO NOT USE privacy.resistFingerprinting or are on ESR... read on
***/
// [NOTE] ESR52.x replace the * with a slash on this line to enable these prefs
// FF55+
// 2514: spoof (or limit?) number of CPU cores (FF48+)
user_pref("dom.maxHardwareConcurrency", 2);

// FF56+
// 2515: disable site specific zoom
user_pref("browser.zoom.siteSpecific", false);
// 2501: disable gamepad API - USB device ID enumeration
   // [1] https://trac.torproject.org/projects/tor/ticket/13023
user_pref("dom.gamepad.enabled", false);
// 2503: disable giving away network info (FF31+)
user_pref("dom.netinfo.enabled", false);

// FF57+
// 2506: disable video statistics (FF25+)
  // [1] https://trac.torproject.org/projects/tor/ticket/15757
  // [2] https://bugzilla.mozilla.org/show_bug.cgi?id=654550
user_pref("media.video_stats.enabled", false);

// * * * /
// ***/
```

**Comment by Thorin-Oakenpants** [comment]
Right now we only need to do this up to and including FF55 - which is small. When we go 56-beta, then we do a commit (just like we do with deprecated) - `4001: move obsolete to RFP alternatives`. Also note, I had a concern over deprecated items, but that's already covered for ESR users if they flip the switch in deprecated which they should.

We should add a note to the user.js header eg

[ESR users] Please flip blah blah deprecated and blah blah section 4001

**Comment by Thorin-Oakenpants** [comment]
!bump

Am off for some zzz and away for a day on client site. What do you think of my idea for the section jiggling and one-char switch ALT section

**Comment by earthlng** [comment]
So far I've only found 1 pref that should be made inactive because the RFP code is superior (gamepads).
For media_stats a case can be made that maybe spoofing to 0 (by using the pref itself) is better in certain circumstances. The sensors and performance prefs are doing basically the same thing as RFP does and can therefore stay active to make it easier for ESR users. I haven't had time to look at the remaining ones because the UUID-leak came up and I was more interested in that. And I'm using ESR now so the problem here doesn't really affect me and thus I'm in no hurry to get this resolved tbh.
You open these massive todo issues and then expect it to get dealt with immediately. The issue here is about "confirm exact actions" and we haven't even done that but you're already thinking about re-structuring the user.js for it.
You don't need to be able to read the code to get an idea about what a certain patch does btw; the comments from the devs alone explain it pretty well most of the times.
If this is a high priority issue for you, you can help speed this up by reading their comments and quoting them here, which in turn helps me (and maybe others) because I won't have to read the whole bugzilla comment section and can just quickly look at the code to confirm that we either still need or don't need a certain pref anymore.
It takes time to do these things properly and our manpower here is pretty limited, so people either need to live with that and accept that we get to it when we get to it, or they need to step up and help out.

> What do you think of my idea for the section jiggling and one-char switch ALT section

IMO, for now we should just use `[COVERED BY 2699 FFxx+]` tags for the few prefs that we end up making inactive, and maybe something like `[INCLUDED IN 2699 FFxx+]` for the ones that we keep active. Eventually we can open another issue to create a new section for them. That way we also don't clutter the comments here with 2 separate issues. Yeah that sucks for ESR users but we can deal with that in the changelogs. We'll get to it when we get to it!

**Comment by Thorin-Oakenpants** [comment]
> I haven't had time to look at the remaining ones

There's no hurry. And I'm not ordering anyone - it was a Q about my suggestion. We have until 56 lands if ~~we~~ I do this. This (using issues) is **my** todo list. I haven't ticked off all the items (but already know the answers). Seems silly to me to create another issue, but yes, do the first things first. I just tend to throw my thoughts in here.

I can already say that there are at least seven items that conflict or are superfluous to RFP (and more to come). It makes sense to create the sections I described for the reasons I already outlined, but yeah .. first things first

**Comment by Thorin-Oakenpants** [comment]
> For media_stats a case can be made

Media stats, touch, etc .. it's not necessarily about a better solution, it's about buying into the RFP completely, otherwise your FP will differ

**Comment by earthlng** [comment]
> 2697: USER AGENT (UA) SPOOFING
> 2698: FIRST PARTY ISOLATION (FPI)
> 2699: privacy.resistFingerprinting
> ^^ renumber these, add in privacy.resistFingerprinting ALTERNATIVES
> 
> suggest
> 
> 4000: privacy.resistFingerprinting
> 4001: privacy.resistFingerprinting ALTERNATIVES
> 4002: USER AGENT (UA) SPOOFING
> 4003: FIRST PARTY ISOLATION (FPI)
> + shove shutdown out to 5000 & personal out to 6000 or something

shutdown is pretty important and shouldn't be moved too far down IMO, lets keep it 2800. Personal to 5000 or so is ok.
What to do with USER AGENT (UA) SPOOFING though? For starters we should probably rename it to NAVIGATOR SPOOFING. Although, does it even need to be its own section anymore when we create an RFP ALTERNATIVES? - IMO no, because 2697a-f are all covered by RFP and it should be in the RFP ALTZ section or completely removed.
And looking at the [patch](https://hg.mozilla.org/mozilla-central/rev/76040a8fabaa) => platform, appname + appversion cannot be overwritten anymore when RFP=true anyway.

Since FPI is almost done I think it should come first and can be its own, round-hundred number, 4000 for example. And then RFP = 4500 and RFP ALTZ 4600 or so.

**Comment by Thorin-Oakenpants** [comment]
We can think about it for 3 weeks, no hurry. I like startup and shutdown to be the first and last sections (with personal and deprecated after that), that's all. We don't need to do 4000+1's, we can go 4000, 4500 - as long as RFP+ALTZ (incl Navigator) are in order. Renaming UA to NAVIGATOR sounds fine. I quite like it in it's own section, since we recommend not to spoof, and its quite bulky.

- 4000: FPI
- 4500: privacy.resistFingerprinting
- 4600: privacy.resistFingerprinting ALTERNATIVES
- 4700: privacy.resistFingerprinting ALTERNATIVES - NAVIGATOR / USER AGENT (UA) SPOOFING

 I'm not in any hurry mate. Let's have a dozen sleeps on it.

PS: I'm quite keen to fire up a 57 and test this spoofing with previous leaks eg over iframes and some navigator items that were not properly covered. And I hope it covers headers, not just JS. Its been a while since I've looked at this. Can't remember if they included the build_id in it, because there is still a Tor Uplift ticket for that.

**Comment by Thorin-Oakenpants** [comment]
^^ * [1396468](https://bugzilla.mozilla.org/show_bug.cgi?id=1396468) Spoof navigator.oscpu - opened 22 hrs ago .. TOLD YA!

**Comment by Thorin-Oakenpants** [comment]
@earthlng I have redone the first post. Each ToDo:Diff, we should add a section like deprecated, but for redundant/clashing prefs now covered by RFP, and do a commit after stable lands just like we do for deprecated.

So far we've been fine, with 55 RFP only using concurrency, the corresponding pref was inactive anyway. But 56 on it is going to get complicated and too messy using tags. I think we should set up these new sections. About the only item in the first post that I would not include in the ALT section is WebGL - as I think we should disable it period. We can talk about that later. I will finish my analysis of the RFP patches first

**Comment by earthlng** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition#Browser_compatibility

> * [2] Can be enabled via the `media.webspeech.recognition.enable` flag in about:config **on mobile**. **Not implemented at all on Desktop Firefox** — see [bug 1248897](https://bugzilla.mozilla.org/show_bug.cgi?id=1248897).

Only `media.webspeech.synth.enabled` is now covered by RFP and our current approach to move more than just the prefs that are covered by RFP to the new section is not great IMO. Same for 4609.

**Comment by Thorin-Oakenpants** [comment]
> our current approach to move more than just the prefs that are covered by RFP to the new section is not great

Thats NOT our approach. I only want to move prefs that are redundant due to RFP. If I have moved some by accident then let me know

**Comment by earthlng** [comment]
I think we can remove media.webspeech.recognition.enable completely. The ticket mentions Q2 2018 when it should be ready and we will see it in the diffs. Then we can check if we even need that pref or if it's already covered by RFP.

> you said just the 4 geo.*

I said quote "geo.enabled only"! I like what pyllyukko does:
```js
// PREF: When geolocation is enabled, use Mozilla geolocation service instead of Google
user_pref("geo.wifi.uri", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");

// PREF: When geolocation is enabled, don't log geolocation requests to the console
user_pref("geo.wifi.logging.enabled", false); // (hidden pref)
```
and then we can drop `geo.wifi.xhr.timeout` and move the 2 `browser.search.geoip.` currently under 0201 to 0202 and add the link that pyllyukko also has, as well, like this:
```js
/* 0202: disable GeoIP-based search results
 * [NOTE] May not be hidden if Firefox has changed your settings due to your locale
 * [1] https://trac.torproject.org/projects/tor/ticket/16254
 * [2] https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections#w_geolocation-for-default-search-engine ***/
user_pref("browser.search.countryCode", "US"); // (hidden pref)
user_pref("browser.search.region", "US"); // (hidden pref)
user_pref("browser.search.geoip.url", "");
user_pref("browser.search.geoip.timeout", 1);
```
and the new 4609:
```js
// 4609: [0201] disable Location-Aware Browsing (geolocation)
   // [1] https://www.mozilla.org/en-US/firefox/geolocation/
user_pref("geo.enabled", false);
```

**Comment by Thorin-Oakenpants** [comment]
^^ well poop, I saw I read that as `geo only`, probably because I asked if was the `geo.* only`. Dude, I've had like 6 hrs sleep in 3 days. Next time I will just wait. Sorry for the fuckups. Go ahead and fix them all with direct commits - I've seriously almost had enough :)

**Comment by earthlng** [comment]
> Go ahead and fix them all with direct commits

done. https://github.com/ghacksuserjs/ghacks-user.js/commit/fec0c992873a417717d76dc20321c97b0c1e3de1 https://github.com/ghacksuserjs/ghacks-user.js/commit/bbb29237ccbbe96046b632812d0945d40a6f7e33

What do you think about keeping the previous number for items moved to 4600, as I did with 4609?
[02xx] would be another option to at least let users know under which section it was. (?)

**Comment by 2glops** [comment]
A good idea IMO.

**Comment by Thorin-Oakenpants** [comment]
every single numbered item starts with `xxxx: action` and the action word is lowercase not propercase - fixed - https://github.com/ghacksuserjs/ghacks-user.js/commit/6e2479dc0fbf030d34cd0c9746a5eee70ecc6474

**Comment by Thorin-Oakenpants** [comment]
These have been removed then - just so people are aware - i added them to the wiki scratchpad list
 - geo.wifi.xhr.timeout
 - browser.search.geoip.timeout
 - media.webspeech.recognition.enable

--
`geo.wifi.logging.enabled` has been changed from active false to inactive true: what is the default value of this hidden pref?

**Comment by Thorin-Oakenpants** [comment]
> What do you think about keeping the previous number 

More work, just another thing to have to do. What happens if we renumber a section later. Some sections may vanish, eg plugins, eg hardware FP. Also keep in mind that over time the RFP ALT section will just keep growing and cannibalizing existing prefs - slowly, but steadily. Imagine what it might look like in a years time.

If you want to add them, then go ahead and do a commit

**Comment by Thorin-Oakenpants** [comment]
^^ https://github.com/ghacksuserjs/ghacks-user.js/commit/ca1679272336d39f4049810bcf25d3bcabbd014c
