### ISSUE TITLE
ToDo: detect & fix broken links

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#224]
* [x] Check all links in user.js (& fix/remove/replace broken ones)
   * [x] http -> https
   * [x] remove mozilla.org `en-US`
* [x] Check all links in Wiki - same as we did for the js
   * [x] Add https://firefox-source-docs.mozilla.org/ to Wiki references section

List is at : https://pastebin.com/nTP00T8R (expires in a month) - get busy peoples

thanks Theemin

---
@Theemim said

Looks like gecko.readthedocs.io has moved to firefox-source-docs.mozilla.org (d2r03xnqvbcxrv.cloudfront.net).  There are two references in the user.js that should probably be updated.  Other pages continue to exist at *.readthedocs.io, including but not limited to:

```
autopush.readthedocs.io
bedrock.readthedocs.io
bleach.readthedocs.io
cornice.readthedocs.io
firefox-puppeteer.readthedocs.io
fxa.readthedocs.io
kinto.readthedocs.io
marionette-client.readthedocs.io
minion.readthedocs.io
moz-services-docs.readthedocs.io
mozdef.readthedocs.io
mozilla-balrog.readthedocs.io
mozilla-django-oidc.readthedocs.io
mozilla-push-service.readthedocs.io
mozilla-services.readthedocs.io
mozilla-version-control-tools.readthedocs.io
moztrap.readthedocs.io
```
Perhaps https://firefox-source-docs.mozilla.org/ should be in the Wiki references section?

**Comment by Thorin-Oakenpants** [comment]
List at : https://pastebin.com/nTP00T8R  ... self destructs in a month .. 364 links. Someone should auto-hyperlink that, add checkboxes and get clicking

As well as lets _try_ to **eliminate** all http in favor of https

**Comment by Theemim** [comment]
### URL changes ###

From: http://archive.is/DYjAM
To: https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/

From: https://gecko.readthedocs.io/en/latest/toolkit/mozapps/extensions/addon-manager/SystemAddons.html
To: https://firefox-source-docs.mozilla.org/toolkit/mozapps/extensions/addon-manager/SystemAddons.html

From: https://gecko.readthedocs.org/en/latest/browser/base/sslerrorreport/preferences.html
To: https://firefox-source-docs.mozilla.org/browser/base/sslerrorreport/preferences.html

From: https://gecko.readthedocs.org/en/latest/toolkit/components/telemetry/telemetry/preferences.html
To: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html

### Can convert to https ###

http://github.com/pyllyukko/user.js/issues/179#issuecomment-246468676
http://news.slashdot.org/story/15/08/14/2321202/how-to-quash-firefoxs-silent-requests
http://techcrunch.com/2015/08/04/battery-attributes-can-be-used-to-track-web-users/
http://www-archive.mozilla.org/projects/security/pki/nss/ssl/fips-ssl-ciphersuites.html
http://www.contextis.com/resources/blog/webgl-new-dimension-browser-exploitation/
http://www.howtogeek.com/195062/no-disabling-ipv6-probably-wont-speed-up-your-internet-connection
http://www.squarefree.com/2004/07/01/race-conditions-in-security-dialogs/
http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_img_src2

### HTTPS/Cert problems ###

https://expired.badssl.com/ (expected)
https://fiprinca.0x90.eu/poc/ (expired cert)
https://subdomain.preloaded-hsts.badssl.com/ (expected)

### 404 ###

https://wicg.github.io/IntersectionObserver/

**Comment by Theemim** [comment]
@Thorin-Oakenpants: How did you generate that list?  I was just looking at the references page and, at the bottom, there are the two links:

http://portableapps.com/apps/internet/firefox_portable 
http://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./

Which didn't appear in your pastebin list, and both can be made https.  Are there other links your process may have missed?

**Comment by Theemim** [comment]
Theemim initially thought that was all the links, including in wiki :cry:

**Comment by Just-me-ghacks** [comment]
Doesn't work / redirect to another URL / invalid security certificate:

https://wicg.github.io/IntersectionObserver/
https://privacytoolsio.github.io/privacytools.io/#webrtc
https://gecko.readthedocs.org/en/latest/browser/base/sslerrorreport/preferences.html
https://fiprinca.0x90.eu/poc/
https://gecko.readthedocs.io/en/latest/toolkit/mozapps/extensions/addon-manager/SystemAddons.html
https://gecko.readthedocs.org/en/latest/toolkit/components/telemetry/telemetry/preferences.html

**Comment by Thorin-Oakenpants** [comment]
Good stuff guys & gals :kiss:  - yeah that pastebin was just the user.js, not sure how to do the wiki except probably just clicking on hyperlinks in it which would be as fast as pissing around extracting the urls to a list somehow

Note: the archive urls were there as backup to the actual urls

**Comment by Thorin-Oakenpants** [comment]
can't believe you all missed the one I added to Theemin's list :sadpanda:

**Comment by Thorin-Oakenpants** [comment]
Wiki: can be https
> http://portableapps.com/apps/internet/firefox_portable
> http://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./

^^ DONE

**Comment by Theemim** [comment]
@Thorin-Oakenpants: But that is a 302!  Seriously, thanks to Just-me-ghacks alerting me to the fact that my scanner wasn't reflecting redirects, I rescanned and found some more for y'all to do.  Two things:

1. Leave out 302s?
2. Quite a few of the Mozilla URLs are en-US specific rather than generic.  If you take out that part it will 302 you to the correct language I guess.  Not sure what you want to do about that aspect.

**Comment by Thorin-Oakenpants** [comment]
302s: might as well, all i saw was one `bugs.torproject.org` and a ton of `trac.torproject.org` so I loaded it :) .. I'm off to watch some movies .. and let this all sit for a day for others to chime in

**Comment by crssi** [comment]
Gifted is nice movie

**Comment by Thorin-Oakenpants** [comment]
https://wicg.github.io/IntersectionObserver/ is 404. Possible alternatives:

If you load a WICG page still alive it redirects to w3c - so I guess it should be https://w3c.github.io/IntersectionObserver/

**Comment by Thorin-Oakenpants** [comment]
we have 48 `/en-US/` URLs and 1 `/en/`

- https://developer.mozilla.org/ = 39 (1 is `/en/`)
- https://support.mozilla.org/ = 5
- https://www.mozilla.org/ = 5

Considering these are ALL mozilla.org, I do not see a problem with removing the en-US part. I have done this with the AMO links in the Wiki.

Anyone see any issues with this?

**Comment by Atavic** [comment]
developer.mozilla links, without` en-US/` get redirected to an URL containing `en-US/`
+Top right option to use other languages is included.

**Comment by Thorin-Oakenpants** [comment]
^^ but what if your language is set as German . . doesn't it auto redirect to the German version etc. It's only redirecting to en-US for you Atavic because of your browser's language settings AFAIK

**Comment by Atavic** [comment]
Forgot localization :+1:

**Comment by Thorin-Oakenpants** [comment]
Does anyone want to enumerate the wiki links? If not I will do it tomorrow

**Comment by Atavic** [comment]
[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/2.1-Multiple-Profiles#small_orange_diamond-firefox-installed-method-1-profile-manager) on bottom there's a broken link now, but this one works: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/2.2-Multiple-Profiles-%5BFirefox-Portable%5D#small_orange_diamond-firefox-portable-method-2-firefox-portable-2ndprofile-app) there's a direct download from sourceforge, not portableapps site... a disambiguation?

[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.5-Request-Control) **Testing Page** link doesn't work... probably it's:
https://github.com/tumpio/requestcontrol/wiki/Testing-links

[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Firefox-Add-ons#small_orange_diamond-recommended-add-ons):

>:broken_heart: Cookie Controller 1 | Web Extension
:broken_heart: Self-Destructing Cookies 1 | Web Extension

...isn't very clear, maybe add question marks? 

>Web Extension ?

[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-D:-References#small_orange_diamond-other) there's a link to Firefox Site Compatibility (fxsitecompat) that's also listed on top of same page.

**Comment by Atavic** [comment]
[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites#small_orange_diamond-encryption--ciphers--ssltls--certificates) https://rc4.io/ seems gone.

[Here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites#small_orange_diamond-other) [Intermediate CA Cache Fingerprinting](https://fiprinca.0x90.eu/poc/) has expired cert and gives me errors when loaded.

By clicking on: CSS History Leak I get: **Defend Your Spaceship!** Is that OK?

Maybe I forgot some checks on Appendix B: All AMO and GH links do work btw

**Comment by Thorin-Oakenpants** [comment]
> already changed by someone

Soz guys. Super busy. I did a quick editing on the Addons page and removed "Web Extension" links to items we know are not being ported, changed the other ones to "Web Extension ***Info***" (i.e not linking to an actual WE on AMO), moved uBo up to WE section

The less info on that page the better

**Comment by Thorin-Oakenpants** [comment]
Checked every single link including all the ones linking to other wiki pages, checked every single non-hyperlinked "link"

* [x] 1.1: fixed hyperlinks for anchors (they need to include that orange diamond)
* [x] 1.4: portable apps => httpS
* [x] 3.1: greasemonkey AMO, removed `en-Us/`

.. am partway thru Appendix B - taking a break

**Comment by Thorin-Oakenpants** [comment]
While testing all the links in apendixes, I notice http://uniquemachine.org/ has been revamped
