### ISSUE TITLE
ToDo: rename => Extensions

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#231]
https://wiki.mozilla.org/Add-ons/Terminology

* [x] wiki page (new url as well)
* [x] wiki index link
* [x] wiki test sites
* [x] readme
* [x] sticky issue (and old sticky issue)
* [x] user.js
* [x] searched repo for "add-on"

Web Extensions => Extensions
Add-ons => Legacy Extensions (where appropriate)
