### ISSUE TITLE
reminder: privacy policies on Extensions

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#236]
as of current [Wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) page (in future all additions require policy vetting) - checklist to find privacy policy links

### Extensions

- [x] CanvasBlocker - https://addons.mozilla.org/firefox/addon/canvasblocker/privacy/
- [x] Cookie AutoDelete - https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/wiki/Privacy-Policy
- [x] Decentraleyes - https://addons.mozilla.org/firefox/addon/decentraleyes/privacy/
- [ ] Greasemonkey
- [ ] HTTPS by default
- [x] HTTPS Everywhere - https://www.eff.org/code/privacy/policy
- [ ] Link Cleaner - :small_orange_diamond: [requested](https://github.com/idlewan/link_cleaner/issues/29)
- [x] Neat URL - https://addons.mozilla.org/firefox/addon/neat-url/privacy/
- [x] NoScript - https://addons.mozilla.org/firefox/addon/noscript/privacy/
- [ ] QuickJava
- [x] Redirector - https://github.com/einaregilsson/Redirector/blob/master/privacy.md
- [ ] Request Control - :small_orange_diamond: [requested](https://github.com/tumpio/requestcontrol/issues/43)
- [ ] Smart Referer - :small_orange_diamond: [requested](https://github.com/meh/smart-referer/issues/64)
- [x] SSleuth - https://addons.mozilla.org/firefox/addon/ssleuth/privacy/
- [x] SSLPersonas - https://addons.mozilla.org/firefox/addon/sslpersonas/privacy/
- [x] uBlock Origin - https://github.com/gorhill/uBlock/wiki/Privacy-policy
- [x] uMatrix - https://github.com/gorhill/uMatrix/wiki/Privacy-policy

### don't care <sup>also obsolete at ESR52 EOL</sup>

* Cookie Controller
* Live HTTP Headers - earthlng clone
* No Redirect (Clone) - earthlng clone
* No Resource URI Leak (Clone) - earthlng clone
* Self-Destructing Cookies

---original post

this is a reminder for Thorin to do something about privacy policies for recommended addons - both in our wiki (I think we're good - eg gorhill, C-AD, Decentraleyes, etc - well known respected devs IMO, but we will check anyway), and those in the sticky

for example: here is an extension https://addons.mozilla.org/en-US/firefox/addon/popup_blocker/ .. 4th page of 57 compatible extensions sorted by popularity Now read the privacy policy - https://www.popup-blocker.com/privacypolicy.html How can 25K users be so naive

PS: Not that I think we need any sort of popup blocker
1. dom.popup_allowed_events", "click dblclick" (this does it for me)
2. overkill: breaks lots so u need to set quite a few exceptions: set uBo to use `no-popups: * true` (that's the icon of two pages, bottom left in your doorhanger) - it will not cover ALL popup events AFAIK. It is better to allow all and deny troublesome sites

That fixes 99.9% of them. I've yet to see one to be honest

**Comment by Thorin-Oakenpants** [comment]
Note sure how to do this for the Wiki, I do not want it to become too "busy". Note if you mouse over <sup>PP</sup> you get alt text `Privacy Policy`. Asterix is there to break the color. Does this look OK?

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>* [PP](https://github.com/gorhill/uBlock/wiki/Privacy-policy "Privacy Policy")</sup> | [GitHub](https://github.com/gorhill/uBlock)

**Comment by Atavic** [comment]
- Yes for uM: https://github.com/gorhill/uMatrix/wiki/Privacy-policy

- NoScript Security Suite has it on AMO

- Decentraleyes has it on AMO:

>Privacy Policy
>Privacy is a universal right.

>Decentraleyes does not collect any data of any kind. 

- [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/) hasn't. Hope @kkapsner can provide it.

- Same as above with [https-by-default](https://github.com/Rob--W/https-by-default)

- Greasemonkey does have it on AMO. They DO collect info.

- Same as CB with [QuickJava](https://github.com/ThatOneGuyDotNet/QuickJava), @ThatOneGuyDotNet please help.

- Same as above for  Cookie Controller by iann.

- Self-Destructing Cookies hasn't it, too.

**Comment by Thorin-Oakenpants** [comment]
privacy policy links that are on AMO, I added them as `/en-US/`. What happens when a localization isn't available? I guess it falls back to en-US? I suppose I should strip those out, right?

**Comment by Atavic** [comment]
Yes, it falls back on `%LOCALE%`

**Comment by Thorin-Oakenpants** [comment]
I spose I better clean up the `en-US` bits then

**Comment by Atavic** [comment]
Just do that.

**Comment by Thorin-Oakenpants** [comment]
these requests make me feel like a spammer :-(

**Comment by Thorin-Oakenpants** [comment]
Is it just me or is Smart Referer changing the AMO DL to and from Legacy to Extension to back and forth. I could have sworn a week or so ago it was 57+ compatible, now it seems to be back at legacy

**Comment by kkapsner** [comment]
Didn't feel like spam on the other side.

**Comment by Thorin-Oakenpants** [comment]
@kkapsner I'll get onto your icons later today/tomorrow - unfortunately the program I am using doesn't export in svg - in fact all it does is PNG (for transparent background), so I lose the vectors

**Comment by Thorin-Oakenpants** [comment]
Closing: have added privacy policy links where they exist, having one is up to the extension owners

**Comment by rekixex** [comment]
@Thorin-Oakenpants 

> in future all additions require policy vetting

It seems that **Skip Redirect** doesn't have a privacy policy - I may be wrong, just did a quick search.

**Comment by Atavic** [comment]
@rekixex Been asked [here](https://github.com/sblask/webextension-skip-redirect/issues/52).

**Comment by Thorin-Oakenpants** [comment]
> > in future all additions require policy vetting
>
> It seems that **Skip Redirect** doesn't have a privacy policy - I may be wrong, just did a quick search.

I also said
> Closing: have added privacy policy links where they exist, having one is up to the extension owners

I am no longer interested in chasing anyone up. I will check for a privacy policy when I add an item, but that's it.

**Comment by Atavic** [comment]
**Skip Redirect**: `[This extension does not collect or send data of any kind to third parties](https://github.com/sblask/webextension-skip-redirect/issues/52#issuecomment-333759979)`

**Comment by Atavic** [comment]
[Skip Redirect](https://github.com/sblask/webextension-skip-redirect/issues/52#issuecomment-333759979): `This extension does not collect or send data of any kind to third parties`

**Comment by Atavic** [comment]
There's a [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1464916) discussion about privacy labels for addons/webextensions:

> “privacy”: [ “sendsUsageDataToThirdParty”, “sendsUsageDataToDeveloper”,
> “sendsBrowsingData”, “sendsProfileData”, “collectsUserData” ]

Also related: https://github.com/pyllyukko/user.js/issues/365
