### ISSUE TITLE
ToDo: scratchpad prefs cleanup script(s)

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#242]
### :small_red_triangle_down: Thorin's ToDo list:

* [x] update wiki 1.1 to reflect that `user set` => `modified` in FF55+
* [x] add links to scratchpad js directory on wiki page, remove draft notice etc
* [x] scratchpad js files

--------
### :small_red_triangle_down: Original Post

WIKI draft: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Bulk-Pref-Resetting-[Scratchpad]

wanted to start a new, dedicated topic regarding this issue since we strayed way off the reservation [in the last one](https://github.com/ghacksuserjs/ghacks-user.js/issues/238)

important stuff from the old topic that still need to be addressed include...

atomGit: could the process of updating the user.js and the cleaning of prefs.js (equivalent to running the Scratchpad script) be totally automated by, say, a GM script that would prompt first and show a changelog perhaps?

new stuff...

how should the scratch-script be versioned?

how often will it need to be updated? i don't want to be re-editing the script at every commit, so what do you guys suggest?

for my sanity (and laziness) i'd prefer to reset ALL user.js prefs as Thorin-Oakenpants suggested, if that's ok with u dudes

i didn't see any feedback in web or browser console with this code - is it possible to pop a dialog box with "success!" or something?

```
  for (let i=0, len=ops.length; i < len; i++) {
    if (Services.prefs.prefHasUserValue(ops[i])) {
      Services.prefs.clearUserPref(ops[i]);
      if (!Services.prefs.prefHasUserValue(ops[i])) { console.log("reset", ops[i]); }
    }
```

**Comment by earthlng** [comment]
a bit more verbose:
```js
(function() {
  let ops = [
    '_user.js.parrot'
  ]

  if(typeof(Services) === "undefined") {
    alert("about:config needs to be the active tab!");
    return;
  }
  
  let c=0;
  for (let i=0, len=ops.length; i < len; i++) {
    if (Services.prefs.prefHasUserValue(ops[i])) {   
      Services.prefs.clearUserPref(ops[i]);
      if (!Services.prefs.prefHasUserValue(ops[i])) {
        console.log("reset", ops[i]);
        c++;
      } else { console.log("failed to reset", ops[i]); }
    }
  }
  
  focus();
  
  let d = (c==1) ? " pref" : " prefs";
  if (c > 0) {
    alert("successfully reset " + c + d + "\n\nfor details check the Browser Console (Ctrl+Shift+J)");
  } else { alert("nothing to reset"); }
  
})();
```

**Comment by earthlng** [comment]
> i'd prefer to reset ALL user.js prefs

then I'd recommend to advice your users to disconnect the network before running the script.

1. download the latest version of the scratchpad script to your desktop
2. close FF + backup your profile
3. disable the network connection
4. start FF, open about:config, press Shift+F4 and load + run the script
5. restart FF to re-apply your user.js + close FF again (because some prefs need a restart)
6. re-enable network connection

**Comment by Thorin-Oakenpants** [comment]
Noooo .. I do NOT want the huge list in the wiki - please revert it

**Comment by Thorin-Oakenpants** [comment]
I only want a small sample of the removed items. As for providing lists, I don;t really want to MAINTAIN anything, and I think it just adds overhead. The Wiki entry is good to llok up and users can do their own thing IMO

**Comment by atomGit** [comment]
@earthlng - nice sciript! `if (Services.prefs.prefHasUserValue(ops[i])) {` - what does it do? LOL i don't know JS well at all, but from what i'm seeing, this resets ALL user set prefs system-wide (prefHasUserValue), as in prefs.js as well? i've got to be wrong, but that's what i'm seeing

> then I'd recommend to advice your readers to disconnect the network before running the script.

yeah, i thought about that too - maybe resetting all isn't the best way to go

> Noooo .. I do NOT want the huge list in the wiki - please revert it

> I don't really want to MAINTAIN anything...

i'll maintain it - i thought the purpose was to make it as easy as possible for users by providing the entire script - that was my plan anyway - if the user has to sift through change logs and run RegEx's to pull prefs, and create the script, then what's the point? if that's the case i think it wouldn't be much extra work to do it all manually

i'll do whatever you want though

**Comment by atomGit** [comment]
... or, if you really don't want the full script here, i could stick on my repo - let me know your thoughts

**Comment by Thorin-Oakenpants** [comment]
> IF YOU HAVE EDITED THE GHACKS user.js INSTEAD OF CREATING AN override.js AS SUGGESTED, THEN YOU WILL LOSE ALL OF YOUR CUSTOM SETTINGS UPON RUNNING THIS SCRIPT! 

What? This is not true. As pointed out three times now - ACTIVE prefs get reapplied, the js files do not care WHERE they are

**Comment by Thorin-Oakenpants** [comment]
oh man.... not happy - reverting the whole thing which is not easy

**Comment by Thorin-Oakenpants** [comment]
> i'll maintain it - i thought the purpose was to make it as easy as possible for users by providing the entire script - that was my plan anyway - if the user has to sift through change logs and run RegEx's to pull prefs, and create the script - all of which most users probably won't do - then what's the point? if that's the case i think it wouldn't be much extra work to do it all manually

My stance has always been that I do not want to maintain this, I only want to provide documented info on how to do it

https://github.com/ghacksuserjs/ghacks-user.js/issues/238#issuecomment-331436625
> I didn't mean that we provide it (FukNo™)

https://github.com/ghacksuserjs/ghacks-user.js/issues/238#issuecomment-331436982
> sample would include non-existant pref names

https://github.com/ghacksuserjs/ghacks-user.js/issues/238#issuecomment-331505720
> I'm not saying we provide it AT ALL - the script is damn handy and I want it documented in the wiki with a tiny sample of made up pref names - but f**ked if I'm going to provide anyone with a list

**Comment by Thorin-Oakenpants** [comment]
> i didn't see any feedback in web or browser console with this code

Open the Developer>Browser Console>Logging for any output. I've run the [current script](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Bulk-Pref-Resetting-%5BScratchpad%5D#small_orange_diamond-the-script) and I get SyntaxError

```js
"SyntaxError: missing ] after element list .. followed by a whole ton of resources
```

**Comment by Thorin-Oakenpants** [comment]
@atomGit : The easiest way to do this is as follow

- we link to a `JS files repo` at the top of the page, and down in the solution part
- note, the wiki instructions say to open [a] script (.js file) OR paste
- we provide a `ghacks-clear-55-[absolutely-everything].js` file for download to reset everything, including the 13 removed items in our wiki example
- from now on all we need to provide is super easy small update .js files which only contain the removed/deprecated/redundant/made-inactive **changes**
   * `ghacks-clear-56-[changes-only].js`
   * `ghacks-clear-57-[changes-only].js`

This is trivial work after the main one is done (but it is something else we then have to remember to do). We could even post it as a comment in the changelogs. Thoughts on where to have this? Seems better to be this repo since it directly relates to our js

**Comment by Thorin-Oakenpants** [comment]
gone deadly quiet in here ...

Am back to a happy state, except for the syntax error, this is working perfectly. The wiki is short and sweet and how I like it. And the use of .js files in a sub folder for  people to download and "open in scratchpad" removes the need for any more articles/typing (except links in the wiki), and a one time catch up to date v55 everything removes the need to ever do it gain, meaning update is TINY in future

**Comment by Thorin-Oakenpants** [comment]
OK, so I didn't have a trailing comma after the first pref `_user.js.parrot` which I left in from the code above. This fixed the syntax error. But the script only produces a single pref change. I got an alert for changing 1 pref, and the console displays a single pref change `reset _user.js.parrot`. So something ain't looping

**Comment by earthlng** [comment]
> So something ain't looping

are you sure there were other prefs from the list that you had user-set?

**Comment by earthlng** [comment]
since apparently everyone can edit the wiki, please stop putting my name on scripts.

**Comment by Thorin-Oakenpants** [comment]
only collaborators with write access can edit the wiki. If you do not want your name on that script, then I will remove it

**Comment by Thorin-Oakenpants** [comment]
> are you sure there were other prefs from the list that you had user-set?

Ahhh, the penny drops. Noooo .. all of those were already reset. I get it now, it only counts if it needs resetting - cool. Hence I got zero changes besides the parrot

**Comment by earthlng** [comment]
> `if (Services.prefs.prefHasUserValue(ops[i])) {` - what does it do? LOL i don't know JS well at all, but from what i'm seeing, this resets ALL user set prefs system-wide (prefHasUserValue), as in prefs.js as well? i've got to be wrong, but that's what i'm seeing

`prefHasUserValue()` checks if a given pref is "user set" and returns either true or false.

@Thorin-Oakenpants great idea [there](https://github.com/ghacksuserjs/ghacks-user.js/issues/242#issuecomment-331662461)

> Thoughts on where to have this? Seems better to be this repo since it directly relates to our js

I agree it should be on our repo. Maybe in a new folder "reset-scripts" or so.

> The wiki is short and sweet and how I like it.

yeah it's great now. still needs a bit of updating after we put the scripts on the repo as js files but other than that - love it. The script(s) are also nice to be able to more easily find other pref-changes in about:config or prefs.js that were user-set and that one might want to put into his own user.js or override.js.

> But the script only produces a single pref change

the script only resets prefs that are both (a) in the ops array of prefnames AND (b) are "user-set" when running the script. I can add some comments to the script for all you JS illiterates if you want. ;) (?)

**Comment by earthlng** [comment]
> I was just giving credit where due

thanks I appreciate that but since there's no guarantee that the script will remain the same as originally posted, I'd prefer not to have my name associated with potentially broken scripts.
If you want to keep the author info, thats fine but then put an "edited by xyz" behind it if you're going to modify it. or "edited and broken by Thorin" or something like that :)

**Comment by Thorin-Oakenpants** [comment]
> the script only resets prefs that are both (a) in the ops array of prefnames AND (b) are "user-set" when running the script. I can add some comments to the script for all you JS illiterates if you want. ;) (?)

You didn't actually expect me to read or look at your script did you? lulz

**Comment by Thorin-Oakenpants** [comment]
PS: u have access to repo settings and permissions for members/collaborators - email me if you want. Since no-one does PRs (and I hate them anyway), it really comes down to the wiki and I would suggest we limit it to u+me+ theemin+atomGit ... been a while since I looked in there - go have a look

**Comment by earthlng** [comment]
> go have a look

there are quite a few with write access. why? have any of them ever needed to edit the wiki?
I think if someone wants something edited in a wiki page they should post a comment in the wiki sticky.
For everything else there are Pull Requests.

**Comment by earthlng** [comment]
> You didn't actually expect me to read or look at your script did you? lulz

I was hoping you'd at least try but I should've known better xD

**Comment by Thorin-Oakenpants** [comment]
^^ Look, I mastered FORTRAN but COBOL almost killed me .. literally (long story) .. after that I decided I was better off gardening

**Comment by Thorin-Oakenpants** [comment]
> there are quite a few with write access. why? have any of them ever needed to edit the wiki?
I think if someone wants something edited in a wiki page they should post a comment in the wiki sticky.
For everything else there are Pull Requests.

Look again, I think you looked just before I changed 5 of them

**Comment by earthlng** [comment]
> DONE: only u & me have write access

"edited and broken by Thorin" remains a problem though xD

**Comment by Thorin-Oakenpants** [comment]
^^ please add something in thew wiki about the script only changing "user_set" prefs

As for creating the clear prefs js repo and some scripts, we can do that after 56 lands - leave this issue open. Time to focus on 56 diffs I think

**Comment by publicarray** [comment]
Wile I respect the effort done here I use Mozilla's own facilities, I remove the prefs.js file and add a /preferences folder with my custom-user-prefs.js in it.

**Comment by Thorin-Oakenpants** [comment]
Huh? Why would you remove the prefs.js - that file contains a heap of internal prefs and values, some are OS specific. While some of know what we're doing, I would never recommend doing that

**Comment by publicarray** [comment]
> that file contains a heap of internal prefs and values
They get repopulated and re-saved on FF shutdown. The only down sides that I have noticed are that the next FF start takes a bit longer and the positioning of the extensions is lost (customisation).

**Comment by Thorin-Oakenpants** [comment]
> They get repopulated and re-saved on FF shutdown

So you're doing this when FF is open? Anyway, this is not how I would approach anything to do with settings

**Comment by publicarray** [comment]
@Thorin-Oakenpants Only when I forgot that I still had a window open 😓. I just do it because It gives be a blank slate to work from. i.e closer to a new profile. (also less of a chance to miss something)

**Comment by Thorin-Oakenpants** [comment]
That's interesting .. prefs in about:config no longer use `user set` but `modified` instead. I guess this was 55 when startup changes were made (no idea of the ticket now - I remember from one of those weekly Quantum blogs or something - prefs are lazy loaded. I'll fire up my 54 and see what they display as.

PS: I have no idea what other pref types display as - eg lockPref

**Comment by Thorin-Oakenpants** [comment]
@earthlng I added a comment to the top of https://github.com/ghacksuserjs/ghacks-user.js/blob/master/scratchpad-scripts/ghacks-clear-57-[changes-only].js  - I think that should be a sufficient prerequisite / compulsory line?

**Comment by Thorin-Oakenpants** [comment]
I have added the following [scripts](https://github.com/ghacksuserjs/ghacks-user.js/tree/master/scratchpad-scripts) so far and tested them in my own main everyday FF
- ghacks-clear-all-up-to-57-[deprecated].js
   * done in reverse order and users can easily remove the ESR section
- ghacks-clear-all-up-to-57-[removed].js
- ghacks-clear-all-up-to-57-[RFP-alternatives].js
- ghacks-clear-all-up-to-57-[the-rest-inactive].js
   * this excludes deprecated, removed ,RFP-alt sections and e10s ( see #306 )

I have one to go
- ghacks-clear-all-up-to-57-[the-rest-active].js
   * this will also exclude deprecated, removed ,RFP-alt sections and e10s

Note: I am using the 57-alpha release to generate these

My own results led to a couple of discoveries, so it's worthwhile doing
- removed didn't clear anything (except the parrot), I was already spot on
- ^^ same for deprecated
- ^^ same for RFP alternatives
- but ... the rest inactive..
   * highlighted a couple of items I did not have in my overrides section which I have now fixed
   * did this by looking at my overrides section vs the console output

console
![inactive-resets](https://user-images.githubusercontent.com/16656956/33757162-d4579796-dc5d-11e7-80d6-74b0e00df26a.png)
my revamped overrides section
![overrides](https://user-images.githubusercontent.com/16656956/33757171-dbc99bdc-dc5d-11e7-911e-20599a104893.png)

Note: the only item not covered in my overrides is `dom.storageManager.enabled` as that has been flipped back to active

**Comment by Thorin-Oakenpants** [comment]
@earthlng - I was wondering if it would be better for the parrot to be at the end, that way the last reset is always with no trailing comma, and it indicates the code reached the end - yes/no? I defer to your wisdom.

**Comment by earthlng** [comment]
^^ yes good idea. Nice work, thanks. I made one small fix: https://github.com/ghacksuserjs/ghacks-user.js/commit/d9e935de3c122dada644e4f63fe5cc295d1b6d93

**Comment by Thorin-Oakenpants** [comment]
wow, how did I miss that - did the code fail and stop for the last 3 prefs?

**Comment by earthlng** [comment]
I haven't tested it but I don't think it should fail, it just won't reset urlclassifier.trackingTable.

**Comment by Thorin-Oakenpants** [comment]
Yeah, it still produced the popup message at the end, so I think you're right

**Comment by Thorin-Oakenpants** [comment]
all done - ran the last one for `the-rest-active` - which holds 359 prefs + the parrot. I got a message saying 358 cleared .. so I wonder what the 2 difference is. I can't see any typos

**Comment by Thorin-Oakenpants** [comment]
The two prefs diff are (yet to work on the subsequent diff)

- `browser.newtabpage.enhanced` - console reports failure
- `browser.send_pings` - nothing in the console, no errors

**Comment by earthlng** [comment]
browser.send_pings is one of the few prefs that WEs can change. Maybe it's locked because of that?
IDK what the problem is with browser.newtabpage.enhanced

**Comment by Thorin-Oakenpants** [comment]
I was just gonna say, as I loaded a two pref script for testing in a restored profile, 

```js
/***
 houston, we have a problem
 MAKE sure the two prefs below are user-set
***/
 
(function() {
  let ops = [
    /* two tricky prefs */
    'browser.newtabpage.enhanced',
    'browser.send_pings',
    /* reset parrot: check your open about:config after running the script */
    '_user.js.parrot'
  ]
```

I looked up each pref and for me `browser.send_pings` is at default false - so it doesn't get included in the changes since it is not user-set/modified. Might be uBo or uM setting this.

browser.newtabpage.enhanced might be because I have activity stream xpi removed? maybe also because I am not using newtab etc but a replacement homepage (via extension) - might try this on a new profile+user.js

**Comment by Thorin-Oakenpants** [comment]
New FF57 profile (with zero system addons), added user.js and restarted. Applied above clear-2prefs - zero problems

So we're all done here then :)

**Comment by Thorin-Oakenpants** [comment]
Aww crap .. I need to investigate why the diff dropped another 1

**Comment by Thorin-Oakenpants** [comment]
The second run of reapply has three items not applied: these are
```
    'browser.urlbar.suggest.bookmark',
    'browser.urlbar.suggest.history',
    'browser.urlbar.suggest.openpage',
```
which are controlled by `browser.urlbar.autocomplete.enabled` and vice versa, kinda. Not worried about it

**Comment by Thorin-Oakenpants** [comment]
^^ yup if `browser.urlbar.autocomplete.enabled` (0850a) is inactive and at default true then the three prefs in 0850b `browser.urlbar.suggest.history/bookmark/openpage` are NOT applied from the user.js

Suggest we make 0850b -> inactive and 0850a -> active to fix this issue

**Comment by earthlng** [comment]
sounds good. Maybe change the note or remove it.

**Comment by Thorin-Oakenpants** [comment]
Or maybe combine them in to 0850

**Comment by earthlng** [comment]
yeah that's fine too

**Comment by Thorin-Oakenpants** [comment]
OK, I'll wrangle something up - but I guess the script for active stays as is?

**Comment by earthlng** [comment]
but it should note that browser.urlbar.autocomplete.enabled needs to be true if one wants to enable some of the other ones. It kinda does that without the need for a note with 0850a + b, so IDK, up to you.

**Comment by Thorin-Oakenpants** [comment]
^^ I know, that's why we made 0850a inactive so people wouldn't fukkup

**Comment by earthlng** [comment]
or we could just make all of them inactive. I think it's a pretty nice feature actually.

**Comment by Thorin-Oakenpants** [comment]
I'll document this in a new issue
