### ISSUE TITLE
ToDo: gunnersson's list

### ISSUE THREAD

**Issue by gunnersson** [ghacksuserjs/ghacks-user.js#247]
Dear all!

Great stuff you have! Some additional suggestions from my side...

Please, have a look at https://github.com/gunnersson and, to be more precise, at https://github.com/gunnersson/my_Mozilla_settings !

That's my repo and project. There's no intention of _bad_ **rivalry**, but just _good_ **competition** by me. In fact, there are many users and repos at GitHub of similar idea and content.

But it would be my intention to bring them all a bit together for sharing and collecting.

Maybe, in this way Mozilla Firefox and Mozilla Thunderbird could be a real joy for many people...

Thank you and kind regards,

Gunner

**Comment by gunnersson** [comment]
### Great stuff you have! Some additional suggestions from my side...

Dear all!

Great stuff you have! Some additional suggestions from my side...

Please, have a look at https://github.com/gunnersson and, to be more precise, at https://github.com/gunnersson/my_Mozilla_settings !

That's my repo and project. There's no intention of _bad_ **rivalry**, but just _good_ **competition** by me. In fact, there are many users and repos at GitHub of similar idea and content.

But it would be my intention to bring them all a bit together for sharing and collecting.

Maybe, in this way Mozilla Firefox and Mozilla Thunderbird could be a real joy for many people...

Thank you and kind regards,

Gunner

**Comment by gunnersson** [comment]
Well, I have to admit that your repo and project is probably the most professional and the most content rich one by far at GitHub and at least the best I have found so far.

But you just could have said something more than just "issue: closed".

Great job, anyway.

**Comment by Thorin-Oakenpants** [comment]
It would have been better if you said "here are some settings I use that you do not" rather than have me wading thru a list of prefs in alphabetical order. So far nothing sticks out, but I am way past dealing with other people's list

**Comment by gunnersson** [comment]
Your repo is even that professional and (in this case more important) content rich that I just don't know which settings I could have that you don't.

Maybe https://github.com/gunnersson/my_Mozilla_settings/blob/master/FYI.md could have been of interest for you.

Just to make it clear (if not): I don't want to criticise any one. But I have noticed that many people here at GitHub do a similar job on Mozilla settings. So, there's much done twice.

Sorry for any inconvenience.

**Comment by earthlng** [comment]
I ran it thru my script and here are the results (not including prefs he doesn't have)

stuff we don't have:
```js
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.startup.homepage", "https://duckduckgo.com/");
user_pref("layout.word_select.stop_at_punctuation", true);
user_pref("plugin.state.java", 0);
user_pref("security.OCSP.GET.enabled", false);
user_pref("security.ssl.enable_ocsp_must_staple", true);
user_pref("spellchecker.dictionary", "de-DE");
user_pref("view_source.editor.external", true);
user_pref("view_source.editor.path", "/usr/bin/geany");
```

inactive in ghacks, active in gunnersson's:
```js
user_pref("device.sensors.enabled", false);
user_pref("dom.gamepad.enabled", false);
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"); // gunnersson active with value: "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
user_pref("plugin.state.flash", 0);
user_pref("privacy.trackingprotection.enabled", true); // gunnersson active with value: false
user_pref("privacy.trackingprotection.pbmode.enabled", true); // gunnersson active with value: false
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.ssl.require_safe_negotiation", true);
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
user_pref("security.ssl3.rsa_aes_128_sha", false);
user_pref("security.ssl3.rsa_aes_256_sha", false);
user_pref("security.ssl3.rsa_des_ede3_sha", false);
```

different values:
```js
user_pref("browser.aboutHomeSnippets.updateUrl", "https://127.0.0.1"); // gunnersson: ""
user_pref("browser.search.countryCode", "US"); // gunnersson: "DE"
user_pref("browser.search.region", "US"); // gunnersson: "DE"
user_pref("browser.tabs.insertRelatedAfterCurrent", true); // gunnersson: false
user_pref("general.useragent.locale", "en-US"); // gunnersson: "de"
user_pref("layout.spellcheckDefault", 1); // gunnersson: 2
user_pref("network.cookie.cookieBehavior", 2); // gunnersson: 1
user_pref("network.http.referer.spoofSource", false); // gunnersson: true
user_pref("privacy.donottrackheader.enabled", false); // gunnersson: true
user_pref("security.pki.sha1_enforcement_level", 1); // gunnersson: 3
```

**Comment by gunnersson** [comment]
Well, sorry, that's due to the lack of my scripting skills. But thank you for that service. Interesting to look at.

Sorry for any inconvenience.

**Comment by earthlng** [comment]
no need to apologize xD Thanks for taking the time to comment here. Any input is welcome, well at least for me, I can't speak for Pants.

**Comment by earthlng** [comment]
Are you sure "de" is the correct value for `general.useragent.locale`? Shouldn't it be "de-DE"? Don't take my word for it though, idk, I'm just asking.

**Comment by gunnersson** [comment]
Thank you @earthlng that's nice. Maybe, @Thorin-Oakenpants was missing some post like https://github.com/ghacksuserjs/ghacks-user.js/issues/247#issuecomment-332568376 (expected it from my side but couldn't provide because of https://github.com/ghacksuserjs/ghacks-user.js/issues/247#issuecomment-332575089 ).

**Comment by gunnersson** [comment]
Good point. I know the difference between de and de-DE and such. I guess it works.

I have no experience if you have to use de-AT ode de-CH and such if there is really the need for. (But not for me with de in general and de-DE especially.)

**Comment by Thorin-Oakenpants** [comment]
AFAIK window.navigator.language (accessible via JS) is determined by the value of intl.accept_languages .. so general.useragent.locale ***may*** be a bit redundant in this regard.

@earthlng - you could test that with your JS skillz

**Comment by earthlng** [comment]
If you reset it in about:config is it "de" then?
From looking at the different locales available on mozilla's download page)[https://ftp.mozilla.org/pub/firefox/releases/55.0.3/win64/] it seems that "de" is probably correct.

**Comment by Thorin-Oakenpants** [comment]
stuff we don't have:

- user_pref("browser.startup.homepage", "https://duckduckgo.com/");
  - not messing with people's start pages
- user_pref("layout.word_select.stop_at_punctuation", true);
  - personal, nothing to do with privacy etc
- user_pref("plugin.state.java", 0);
  - obsolete. The only plugins allowed bow are flash
- user_pref("spellchecker.dictionary", "de-DE");
  - spellcheck is internal and not a privacy risk
- user_pref("view_source.editor.external", true); & user_pref("view_source.editor.path", "/usr/bin/geany");
  - not going to force someone to use an external editor - this actually breaks "state separation" of browser content (by sharing with OS, independent apps)

**Comment by gunnersson** [comment]
`general.useragent.locale;de` is standard setting here with me (just looked into about:config).

**Comment by gunnersson** [comment]
Regarding https://github.com/ghacksuserjs/ghacks-user.js/issues/247#issuecomment-332583061 and such: well, that is a big **+** of your repo/project, @Thorin-Oakenpants : many comments in your file like known from scientific work. Very good job.

I do pretend that my settings are good for every one. Some of them maybe without change. But sometimes you have to check and test if it fits for you...

**Comment by gunnersson** [comment]
@earthlng thank you for diplomacy
@Thorin-Oakenpants  thank you for your whole work and the ongoing communication

Maybe have a look at https://github.com/allo-/firefox-profilemaker/issues/93 . Then you could get an idea why I try to bring people together:

-  https://github.com/ghacksuserjs resp. https://github.com/ghacksuserjs/ghacks-user.js (you) and  https://github.com/pyllyukko resp. https://github.com/pyllyukko/user.js have really great lists. (Very impressive for "academic" reason, i.e. many comments.)
- https://github.com/allo- resp. https://github.com/allo-/firefox-profilemaker and https://github.com/Genbox resp. https://github.com/Genbox/HardenIT have nice GUI. (Some people just need something like that.)

My personal intention is just to get out the best of Mozilla Firefox (and Thunderbird) so that using it is a joy for many people ( --- many left and moved to Chrome  or if not moved are grumbling a lot).

**Comment by Thorin-Oakenpants** [comment]
OK, so now I have a few spare minutes, let's finish this off

### Nothing to see people <sup>move along people, nothing to see</sup>

* [x] inactive in ghacks, active in gunnersson's
   * check: all these are inactive for a reason
   * We just recently re-covered device sensors and gamepads, as well as all the ciphers
   * TP is at default (we already cover GA in addon discovery panel) so the DNT is consistent
   * We do not condone UA spoofing on your own - see RFP
   * We block FF from scanning for plugins on startup with `plugin.scan.plid.all` so the flash pref is moot
* [x] stuff we don't have
   * see earlier comment
   * browser.customizemode.tip0.shown - pretty sure 99.999% of users would have already manually caused this to be set
* [x] different values
   * 3 are language issues - we use en-US
   * snippets: we use `https://127.0.0.1` been over this 50 times in the last 3 years. Tor guys were concerned about it being at least https, but we could probably use data, http, https, or blank
   * spellcheck - we tend to use defaults in the personal section
   * insert tabs after current - ditto, default in personal
   * privacy.donottrackheader.enabled - totally covered, we use default false (this only covers normal windows). TP takes care of DNT in PB mode. We are at defaults for both DNT + TP = consistent for FP'ing (and we do not recommend PB mode except as one off windows)
   * network.cookie.cookieBehavior - hell no, we BLOCK all (although this is not everyone's choice, and it is now affecting Web Extensions. If we address it, it will a new topic and down the track
   * network.http.referer.spoofSource - we spent a lot of time going over referers including a lot of input from a Mozilla engineer who works in precisely this area. We recommend granular control via an extension - hopefully Smart Referrer WE
   * security.pki.sha1_enforcement_level - we block em all. Locally added roots such as AV can get stuffed, and if it's required (eg corporate sniffing) then the IT guys can deal with it

### To discuss
* [ ] 1201: `security.ssl.require_safe_negotiation`-`true`
   * Now that we have raised TLS to 1.2 minimum maybe we could make this active. The feeling has been for a long time that it broke too many websites.
* [ ] 1241: `security.mixed_content.block_display_content`-`true`
   * mixed PASSIVE content (images). I honestly feel that this is best left inactive due to too much visual breakage. I think earthling uses this as true.
* [ ] `security.OCSP.GET.enabled` - default is false - do we need to add this
* [ ] `security.ssl.enable_ocsp_must_staple` default is true - do we need to add this

So that covers it. Four items to consider. @earthlng - what say you?

**Comment by Thorin-Oakenpants** [comment]
^^ !bump

**Comment by earthlng** [comment]
1201: I've been using that for a long time and never encountered a site where it caused a problem. But you tested it in February and apparently it caused some problems for you. Maybe instead of enabling it for everyone you can add it to your override.js for a while and see how it goes.
1241: yes I'm using that one but it's probably a bit too much to enable for everyone by default.

for the other 2 I don't think we need to enforce the defaults.

**Comment by Thorin-Oakenpants** [comment]
FYI: I was reading about when cookies meet blockchain (scroll to the end for a list of papers - https://webtransparency.cs.princeton.edu/webcensus/index.html ) but the discussion on mixed passive content had me thinking

Jan 2016 top 1M sites (Alexa) under the "Third parties and HTTPS adoption" section

> Around 78,000 first-party sites currently support HTTPS by default on their home pages. Nearly of these 8% load with mixed content warnings, of which 12% are caused by third-party trackers. 

So if we take 12% (3rd parties) off the 8% (sites with mixed content warnings), we're left with 7% of sites. It's not scientific, because mixed content could be same domain and third party. The point is, at best, at least 7% of HTTPS sites have mixed content when 3rd party is eliminated. It also doesn't break down active and passive mixed content. Now that was 18 months ago, and the landscape is also changing with Zilla & Chrome roadmaps to display insecure/whatnot padlocks and warnings, and the drive to move to HTTPS. Considering Zilla and Chrome use a PKI of around 0.3% or lower to deprecate or flip things .. this will be a long time coming
