### ISSUE TITLE
ToDo: extensions and cookie exceptions

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#250]
### :small_red_triangle_down: Thorin's ToDo list:

* [x] https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Setting-Extension-Permission-Exceptions
* [x] add something to the Implementation page
* [x] add something to the js readme (see below)
* [x] test what happens when these cookies are deleted
   * on close, manually on Ctrl-Shift-Del, via CCleaner
      * NOTHING, they do not really exist and are instantly recreated
      * NOTE: internally these are not seen (eg in view>cookies) and firefox manual delete and on close seem to have no effect. CCleaner sees "something", but again, no effect as FF just recreates them on startup

NOTE: add something to the 2701 pref or 2700 header when we revamp that section

-------
### :small_red_triangle_down: Original Post

***cookies control local storage and IDB access*** (this is why I NEVER get any IDB entries!!! - I feel sorry for all you `suckers` who allow 1st party by default), including for Extensions - since we block all cookies by default (and why wouldn't you), then extensions such as VM, uBo, uM, Stylus etc WILL BREAK in some fashion.

this is a reminder to add something to the readme, to the js (at top and in cookie section), and on the wiki extensions page and the wiki implementation page maybe

It's pretty simple, you just go to about:debugging>add-ons, click on the manifest.json of your extension:  this loads a page with the uuid eg
- moz-extension://b334a4fa-1146-4489-ac23-2f92fcaa7ef3/manifest.json
- under cookie exceptions in prefs, you add an "ALLOW" exception for this part
   * moz-extension://b334a4fa-1146-4489-ac23-2f92fcaa7ef3

I could do this as a separate wiki page with some pictures - thoughts anyone?

Edit: Also - do not remove cookies with ccleaner (not sure what happens) - see subsequent post

Update: when in the manifest page, clicking the info icon in the address bar does not allow access to site permissions. But you still get to that from the page context menu - i.e right click in the page, choose `View Page Info` then `Permissions` .. etc (allow your cookie exception from here

**Comment by Atavic** [comment]
:+1: Webextensions need some whitelisting, like the sites one logs into.

**Comment by Thorin-Oakenpants** [comment]
^^ I do not understand what you mean by that Atavic

**Comment by Atavic** [comment]
EDIT: How many webwextensions need this to work?

**Comment by Atavic** [comment]
EDIT: How many webextensions need this to work?

**Comment by Thorin-Oakenpants** [comment]
So far 3: Stylus, VM, and uBo. note uM will need one too. The manifests use the UUID - so everyone will be unique

Here are my cookie exceptions
![cookies-exceptions](https://user-images.githubusercontent.com/16656956/31049192-96f216aa-a68a-11e7-865b-f2a98ddf706b.png)

Here are viewed cookies
![cookies-view](https://user-images.githubusercontent.com/16656956/31049199-a74d472c-a68a-11e7-9f6d-17570ab3dbdd.png)

Here is ccleaner
![cookies-ccleaner](https://user-images.githubusercontent.com/16656956/31049200-af31710c-a68a-11e7-818b-eed16de8bf5d.png)

Note that ccleaner sees a "cookie" but these are not shown in zilla's internal viewer. I have no idea what happens if it gets cleared. Stylus says/said on its repo that even thought it doesn't set a cookie, you need to allow it for local dom (but then they switched to IDB - AFAIK - anyway, same rule applies - cookies must be allowed for IDB too). I suspect that if the cookie is "removed" by ccleaner, it will just re-generate with no problems since nothing really exists - IDK, not willing to try it - done enough testing.

**Comment by grauenwolfe** [comment]
@Thorin-Oakenpants Thanks for posting this. Haven't been able to get uBo filter lists to stay collapsed. Adding moz-extension://string/ from uBo to the cookies exceptions has it functioning properly again.

**Comment by Thorin-Oakenpants** [comment]
uBo (and no doubt uM) have this issue for people in PB mode and gorhill is (I think) going to make it more robust and fall back to the old storage.

here's a trick from gwarser which does the reverse - https://github.com/gorhill/uBlock/issues/3071#issuecomment-333326484

We block cookies and then set an allow exception. People in PB mode who allow cookies, set a block exception. This is nuts. While we don't recommend **starting** in PB mode, we certainly do not object to using it for one-off windows/sites. High time Mozilla exempted internals and extensions from CONTENT

Yes, it complicated, but surely IDB, local dom, cookies, chrome workers used by extensions internally should not be influenced by settings designed to control websites

**Comment by Thorin-Oakenpants** [comment]
draft: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Extension-Exceptions

* [ ] better page title than `Extension Exceptions`
* [ ] add a couple of pics
* [ ] need to add something to the Implementation page
* [ ] need to add something to the js readme (see below)
* [ ] ? need to add something to the 2701 pref or 2700 header

```
  blah blah...
  3. If you skipped steps 1 and 2 above (shame on you), then here is the absolute minimum
     * Auto-installing updates for Firefox and extensions are disabled (section 0302's)
     * Some user data is erased on close (section 2800), namely history (browsing, form, download)
<new bit start>
     * Cookies control access to local storage and indexedDB. Cookies are denied by default (2701).
       Extensions that use local storage and/or indexedDB **will break**
       - Either allow first party cookies (and use an extension)
       - Or deny all cookies and set exceptions including on **extensions** that need it
       To set an extension cookie exception, see the wiki (link to come)
<new bit end>
     * EACH RELEASE check:
      blah blah
```

note: this line would be removed
```
     * Cookies (and thus logins) are denied by default (2701). Use site exceptions or an extension
```

**Comment by Atavic** [comment]
`Webextensions Whitelisting` ?

**Comment by Thorin-Oakenpants** [comment]
Changed it - see first post

> What are `Webextensions`? I know about `Extensions` and `Legacy Extensions` .. but wot is this magic wizardry black arts you speak of? - *[PC Principal](https://en.wikipedia.org/wiki/PC_Principal#PC_Principal) Pants*

**Comment by Thorin-Oakenpants** [comment]
FYI: I use FVD Speedial - i updated it today to a webext hybrid.  Because I was thinking ahead, before I updated, I allowed first party cookies, disabled the setting in user.js, and after the update had to restart to complete. On restart, the update continued and migrated all my dials etc into a moz-extension-uuid IDB entry

... the about:debugging shows no manifest, it is still a LEGACY marked app - the IDB is being used (rather than the old fvd folder - I know because I have been making some changes since updating)

Anyway .. as I said, there is no manifest URL in about:debugging - I changed cookies to deny all, added an exception based on the IDB folder name entry, re-enabled the cookie setting in my user,js .. and all is groovey

PS: If you are unsure if your extensions need IDB, I guess you can allow all cookies and browse around for a few hours etc. Then just check your storage/default folder for moz-extension+++ entries

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Setting-Extension-Permission-Exceptions

^^ nits please. I have done a few edits and added some pics. Have I missed anything? Can anything be worded better? Is anything factually incorrect? etc. I'm not Shakespeare and I hate writing these things, and I'm crap at them, so feedback required

**Comment by Thorin-Oakenpants** [comment]
Here is a pic of me [hard at work](https://upload.wikimedia.org/wikipedia/commons/3/3c/Chimpanzee_seated_at_typewriter.jpg)

**Comment by Atavic** [comment]
Just read the wiki. It's OK, just a very minor typo: custom settings

Maybe make it to: Custom Settings ...as the rest of the text under the second point [here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Setting-Extension-Permission-Exceptions#small_orange_diamond-note).

**Comment by Thorin-Oakenpants** [comment]
Guess we'll see what happens - maybe by 58, more likely 59
- https://bugzilla.mozilla.org/show_bug.cgi?id=1406675

**Comment by grauenwolfe** [comment]
For anyone using New Tab Override, just recently found out that it needs to have an exception as well. Exactly the same way as uBo - simply adding the `moz-extension://UUID` to your exceptions.

**Comment by Thorin-Oakenpants** [comment]
All done - added/re-jinked implementation page, added info to readme in user.js
