### ISSUE TITLE
ToDo: format change

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#30]
Just using a new issue to deal with this rather than OT elsewhere.

[Here](http://pastebin.com/9bJs6sWc) is a pastebin which expires in 24hrs.

Because every single non user_pref line is modified, I have taken the opportunity to do more than that. All up:

* formatted as discussed earlier which creates foldable preference numbers
* where a numbered item had user_pref lines punctuated by comments, I did something about it (eg all the current 3021 items) so that every single foldable item has a number
* acronyms are expanded eg DHE, DRM, CDM etc where needed
* all version notations are now (xx) for deprecated and (FFxx) for introduced
* removed all instances of "i" and "author" and used 1st person plural (if indeed even needed anymore)
* removed ghacks html <font> tags
* reviewed/checked all warning tags (got rid of some) and added setup tags: they now use  `[WARNING]` and `[SETUP]`
* removed all the rubbish from the doc header section and rewrote a quick readme to make some things painfully clear. PS: the readme is not done, but the little readme in the user.js covers all the really important stuff, is seriously short, simple, and easy to read
* did away with the troubleshooting list, you'll see why (hated maintaining that list)
* those painfully clear things are also made painfully clear in those sections or preferences, some rewording.
* a few descriptions were slightly reworded, or two liners moved into one
* made a few other words/phrases etc uniform
* went over it a half dozen times

The idea, without going overboard, with the `[WARNING]` and `[SETUP]` tags is that warning is more about (major) site breaking etc and setup is stuff that is optional or should be looked at when setting up - doh! By that, I mean that 90% of the 270+ numbered items cause zero breakage or issues, 5% are optional i.e the user can make an informed decision and knows the drawbacks (eg keeping history), and the rest are items that cause site breakage or are bad to implement etc. The two tags can be used in conjunction (i.e more than one tag per item), they can be at the end of a section title, at the end of a preference number title, in a comment at the end of a user_pref line, in the middle of a section description, or at the start of a item's warning section etc.

@earthlng I have tested it for syntax, etc. Do one of your compares to make sure no pref values got changed, or prefs switched between active/inactive. And then make any changes you want and pastebin me back a version. Make any changes you want (ignore passwords/referrers sections), because this is a one time deal since 70% of the lines are going to change. Take your time.

@everyone else - if you want to proof-read it when you have some time, or offer suggestions, go for it. I can do the commit when we're all happy.

**Comment by Just-me-ghacks** [comment]
- replace "Covenience" with "Convenience"
- replace "surpises" with "surprises"
- replace "shoulder surfers,forensics" with "shoulder surfers, forensics"
- remove double space "disable URLbar autofill -  PRIVACY"
- capital letter? "then also make sure 0806"
- "Try it You are not missing" - you?
- and impacts video imperformance ???
- replace "signifcant" with "significant"
- remove the space at the end of line 976.
- Facebook but youtube, microsoft - why capital F?

**Comment by earthlng** [comment]
http://pasted.co/5c0cfcc1

Only 1 change from my comparison: 2703 was commented out in master, active in your pastebin

Apart from a few other things, I changed the numbers under 0410, not a fan of things like 0410b2, but feel free to change it back or do a mix , or whatever you think is best

some of the things Just Me noticed are corrected in my pastebin, but not everything. (only the first 2 I think)

**Comment by Roman-Nopantski** [comment]
@earthlng 

Will do compare with mine after Just-me fixes. And yeah that numbering annoys me too, but I do not want to change numbers if at all ever. I will see what you came up with

==2703
That was exactly the one area I was playing with yesterday, Flicking the use custom history settings and toggling the allow/block all cookies. I think we should enable this pref but not in this ticket. That is in Options>Privacy>History>use custom I want the settings here to set

- [ ] accept cookies from sites (unchecked)
  - [ ] Accept third party cookies - Never
  - [ ] Keep until - they expire

Until they expire is default anyway. Oxymoronic I know, block all but keep forever, but I have my reasons. Getting OT

**Comment by Just-me-ghacks** [comment]
capital letter? "then also make sure 0806" - My bad, ignore it. I didn't see the comma before "then".

**Comment by Roman-Nopantski** [comment]
@Just-me-ghacks The old team+authors from ghacks get invited as "collaborators" - go to https://github.com/ghacksuserjs/ghacks-user.js/invitations and you will see an invite to accept. It also adds you to the @ list when we are typing

**Comment by Roman-Nopantski** [comment]
yes or no? (it's already explained in the header section)
/* 0410: disable safe browsing -> /* 0410: disable Safe Browsing (SB)
/* 0420: disable tracking protection -> /* 0420: disable Tracking Protection (TP)

**Comment by earthlng** [comment]
IMO we should always use 0410a, b, c, etc. for "meta"-numbers. I allows for more than just 041[1-9] prefs in one group.

**Comment by Roman-Nopantski** [comment]
@earthlng am not changing numbers in 410, i have a semi-solution, we can deal with that in another separate issue

**Comment by Just-me-ghacks** [comment]
* [] replace ` with '

**Comment by earthlng** [comment]
> yes or no?

dude, you can't get our thumbs-up first and then add more items later, wtf ;)

**Comment by Roman-Nopantski** [comment]
huh, I saw two thumbs up so actioned them

**Comment by earthlng** [comment]
maybe slightly OT, but hear me out ;)

I still like the idea of making this overall more modular by using a preferences folder.
But we would only use a separate file IF we can really isolate certain prefs for a certain feature, SB + TP come to mind.
We could release with `safebrowsing-trackerprotection.js.prefs` and without needing to edit anything, users could just rename the file to disable SB + TP. 
Since you plan to enable SB+TP by default anyway, I think this would be a neat way to handle it.
Of course this would only work when we want to ship with a feature completely on it's default values.

> Restore video settings

If we had multiple files, we could consider using 'pref' instead of 'user_pref' for certain files (fe media)
I know it has a lot of downsides, but one major advantage is that the file could simply be renamed or deleted and the original defaults would be restored.

**Comment by Roman-Nopantski** [comment]
"Since you plan to enable SB+TP by default anyway" - no i don't now, read the readme in the new upcoming js, also first post #18 has been updated. Like I said those 3 things SB+TP+Auto-updates (or notifications) at least are, AFAIK, the ONLY things that put someone at risk, and only if they ignore all the warnings and advice plastered everywhere - in the js readme, in the github readme, on the wiki plugins list, in the js section headers, and in some pref descriptions. I gave em tags to search for. If people choose to ignore it all that and put themselves at risk, it's not in my head.

Not into modular right now. Bring it up in 3 months :)

**Comment by Roman-Nopantski** [comment]
Thanks everyone, really appreciated. @Just-me-ghacks (I knew I could rely on you to find all those grammar mistakes)

Here is the revised pastebin: http://pastebin.com/E1jeUWhU
Give it one last pass if you can :)

@earthlng  Lots of those little descriptions edits are great. Merged most of yours. 
* [ ] we could look at wrapping all preference names in ` or ' chars, or not, to be consistent. I think they are all currently with nothing. Whatever, as long as its consistent
* [ ] first line of each numbered item to be clean/succinct - I think I undid one of yours, can't backtrack to find it, but I see what you were doing pushing extra info into a secondary line, so when doc is folded it's awesome
* [ ] 0402: you changed the meaning?
  * [yours] `Here you can remove the collection name to disable each specific list`
  * [current] `Here you can remove the collection name to disable each specific list updating`
  * Which is it, does it stop that list being applied at all (you will have local files) or just the updating of said local files.

==
- didn't do, the re-number of 410 for now. I just re-used the letter. If mozilla keep changing the wording and the pref names, we'll just keep re-using the number. Isn't this all going to move to kinto?
- didn't incorporate the pref value changes for your `"data:, "` changes, we have that in another issue and should do it as a separate commit

**Comment by earthlng** [comment]
> no i don't now, read the readme

ROFL you change your mind + the readme every day and each new day you tell me to RTFM, wtf xD

> Bring it up in 3 months

yeah, I'll bring it up tomorrow and reckon I have good chances you love it

**Comment by Roman-Nopantski** [comment]
End of discussion on this please: I didn't PLAN to, it was for discussion brought up by the diff in values vs pyllyukko's. It highlighted a potential problem with 2 solutions - either strengthen warnings or flip the settings in our `template`. I was arguing the merits of the second option. That was all. There is also the future of branches.

**Comment by earthlng** [comment]
> Give it one last pass if you can :)

- 0410a - F48 instead of FF48 (?)
- 0410b - exists twice
- 2672 - move the "than sorry" on the previous line. it's still shorter than the title line
- 3021b - why do you insist on removing the line `[NOTE] does not apply to middle-click or Ctrl-clicking links.` ? imo that's valuable information and nice to know
- 3021c - no space between /* and number

IMO it's always good to have an empty newline at EOF

**Comment by Atavic** [comment]
Use FF.
Use empty line, Github does it.

**Comment by Roman-Nopantski** [comment]
- done - F48->FF48
- done - 3021c
- new line at EOF .. soz I usually do, must have been the copypasta or because I edited some lines in the diff app. copypasta into github wyswig I will be careful to check that.

- no change - 0410b already explained, am not redoing all those numbers and 0410b1 looks silly. not my fault mozilla played changing wording in option and tweaked urls - they are the same preference. We can always bring it up later, especially if that section expands with more and more changes.
- no change - 2672 - the first line for every number is the "title", like a sub-heading. The next three line(s) are the information, like a paragraph - I evened those out
- no change - 3021b - it doesn't make sense to include it. Its about closing tab behaviour, so we're talking about middle or ctrl clicking a "close this window" link? I even think I may have added it byb mistake it seems so silly. Who has close this window links anymore? People who middle or ctrl click know what they're doing

3021b, if you can find a close this window link and test the middle and ctrl-click and confirm it, i'll add it back

I'll leave it for another 24 hrs for any more comments

**Comment by Just-me-ghacks** [comment]
* [ ] 0410d: disable mozilla safebrowsing // mozilla or Mozilla?
(0410c: disable Google safebrowsing & 0440: disable Mozilla's blocklist)

* [ ] 0810: disable css querying page history - css history leak // CSS?

* [ ] 1405: disable woff2 - expand to WOFF (Web Open Font Format)

* [ ] This will break some sites eg Dropbox, Google Docs? gmail? // dropbox, google docs or Gmail?

* [ ] Roboform // RoboForm

* [ ] lastest ESR // latest

* [ ] site funtionality // functionality

Pants, I like your writing style and the original user.js. Please don't approve everything and don't change things just for the sake of changing something. Just saying...

**Comment by earthlng** [comment]
* [ ] 1200 - start the sentence after the URL on a new line
* [ ] 1208 - 0=disabled instead of 0-disabled
* [ ] 1215 - should be 0 = blabla, 1 = blabla -- same as 1211
* [ ] browser.usedOnWindows10.introURL // removed in FF50 (was in my diff) => 0 results in DXR for 'usedOnWindows10'
* [ ] 2617 - says disable in title but enables it
* [ ] add comment `// Form & Search History` to `privacy.clearOnShutdown.formdata`
* [ ] uppercase first letter `// Active Logins` for `privacy.clearOnShutdown.sessions`
* [ ] 3021b - I think it applies when you close a tab with middle-clicking the tab

**Comment by Roman-Nopantski** [comment]
OK .. WTF is that site meant to do. If I allow all JS, I get a spaceship, I see nothing else except the box, start button. I click around clicking on invisible things and sometimes I get 100 points. Eventually, I get a game over, try again. Very rarely, I get a popup that just makes guesses and lists two sites I have been too (and it is totally wrong), and a also lists a bunch of sites I haven't been to (any fraudster and confidence man could pull that out of his arse).

**Comment by earthlng** [comment]
testsite: you need to enable `layout.css.visited_links_enabled` and test it in a Normal Window. PB doesn't seem to work. Check the source and visit a few of the URLs from the list and then start the test. It uses a lot of http sites instead of https, so it can't detect some of the sites anymore because they moved to https.
But I just did the test and apart from one, it correctly identified all other sites I visited (fe. didn't detect http://reddit.com/r/conspiracy, because that's https nowadays)

**Comment by Just-me-ghacks** [comment]
* [ ] replace "non-priviledged" with "non-privileged"

**Comment by Roman-Nopantski** [comment]
too late
