### ISSUE TITLE
ToDo: diffs FF61-FF62.blah.blah

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#459]
FF62 is [scheduled](https://wiki.mozilla.org/Release_Management/Calendar) for release 5th Sept

### other

* [ ] remove [SETTING-ESR52] lines
* [ ] consider turning on 1700s (containers)
* [ ] FF63: [1409664](https://bugzilla.mozilla.org/show_bug.cgi?id=1409664) `media.mediacapabilities.enabled` - don't want to lose track of this, so dumping here

**Comment by Forsaked** [comment]
Go turn on containers!

But be aware of the fact that custom search plugins which use POST instead of GET (like StartPage or DuckDuckGo) gonna end up with the blank search pages instead of results, if the search result opens in a new container tab.
This seems to be an (WebExtension) bug, which should have been fixed in 61.0 but is also still existing in the 63.0 nightly.
Since they deprecated `browser.newtabpage.activity-stream.enabled` in 60.0 there is no workaround for this.

Since activating containers don't open search results automaticly in a container, this is no problem for this user.js, but for people who use [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/) or [Temporary Containers](https://addons.mozilla.org/firefox/addon/temporary-containers/).

I would recommend to write a comment in the Wiki for this behaviour.

**Comment by Thorin-Oakenpants** [comment]
^^ Thanks. Now that ESR52.x reaches end-of-life, we can revisit some things. Earthlng may have a better handle on what prefs will make a difference, but containers is one of them for sure (FF61 flipped the master switch for containers from false to true, so IDK if that means it wasn't really ready for 60 branch?).

**Comment by Forsaked** [comment]
It was ready since they ended the Multi-Account Containers Testpilot, which ended on the 10th October 2017.
Im not sure why they didn't flipped the switch earlier.

**Comment by earthlng** [comment]
> FF61 flipped the master switch for containers from false to true

No it did not

**Comment by Thorin-Oakenpants** [comment]
^^ my bad - got mixed up with `privacy.usercontext.about_newtab_segregation.enabled` which was flipped to true in 61
