### ISSUE TITLE
ToDo: diffs FF75-FF76

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#932]
FF76 is [scheduled](https://wiki.mozilla.org/Release_Management/Calendar) for release May 5th

[FF76 release notes](https://www.mozilla.org/firefox/76.0/releasenotes/) [when ready]
[FF76 for developers](https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/76)
[FF76 compatibility](https://www.fxsitecompat.dev/en-CA/versions/76/)
[FF76 security advisories](https://www.mozilla.org/en-US/security/advisories/mfsa2020-16/)

---

75 diffs ( 36 new, 17 gone, 22 different )

### new in v76.0:

* [x] pref("dom.security.https_only_mode", false); - https://github.com/ghacksuserjs/ghacks-user.js/commit/27d72eda9eed2c065cc6397e4e9b03c86ffa6424

### removed, renamed or hidden in  v76.0:
* [x] pref("extensions.blocklist.url", "**h**ttps://blocklists.settings.services.mozilla.com/v1/blocklist/3/%APP_ID%/%APP_VERSION%/%PRODUCT%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%PING_COUNT%/%TOTAL_PING_COUNT%/%DAYS_SINCE_LAST_PING%/");
   - `0401` - [1618188](https://bugzilla.mozilla.org/1618188) - https://github.com/ghacksuserjs/ghacks-user.js/commit/14aaec71fb192eaab78365d54b0b76a2d5845860

### changed in  v76.0:
* [x] `2605` pref("browser.tabs.remote.allowLinkedWebInFileUriProcess", false); // prev: true - https://github.com/ghacksuserjs/ghacks-user.js/commit/0ea1605642e67db9f930cb79680a3b1b78a74b62

---

### ignore

<details><summary>click me for details</summary><p>

==NEW
```js
pref("apz.zoom-to-focused-input.enabled", true);
pref("browser.osKeyStore.loglevel", "Warn");
pref("browser.ssb.enabled", false);
 // ^ SSB = Site Specific Browser
 // ^ https://www.maketecheasier.com/enable-site-specific-browser-firefox/
pref("devtools.performance.recording.duration.remote", 0);
pref("devtools.performance.recording.entries.remote", 10000000);
pref("devtools.performance.recording.features.remote", "[\"js\",\"leaf\",\"stackwalk\",\"screenshots\",\"java\"]");
pref("devtools.performance.recording.interval.remote", 1000);
pref("devtools.performance.recording.objdirs.remote", "[]");
pref("devtools.performance.recording.preset.remote", "web-developer");
pref("devtools.performance.recording.threads.remote", "[\"GeckoMain\",\"Compositor\",\"Renderer\"]");
pref("devtools.performance.popup.feature-flag", false);
pref("devtools.responsive.touchGestureSimulation.enabled", false);
pref("dom.animations.mainthread-synchronization-with-geometric-animations", true);
pref("dom.arena_allocator.enabled", false);
pref("dom.events.compress.touchmove", true);
pref("dom.no_unknown_protocol_error.enabled", true);
pref("dom.quotaManager.useDOSDevicePathSyntax", false);
pref("dom.security.secFetch.enabled", false);
 // ^ https://github.com/w3c/webappsec-fetch-metadata
pref("dom.workers.serialized-sab-access", false);
 // ^ sab = shared array buffer
pref("gfx.vsync.use-waitforvblank", false);
pref("gfx.webrender.compositor.force-enabled", false);
pref("layout.css.image-orientation.initial-from-image", false);
pref("media.getusermedia.hpf_enabled", true);
 // ^ hpf = high pass filter
pref("media.navigator.video.use_transport_cc", false);
pref("media.videocontrols.picture-in-picture.video-toggle.min-video-secs", 45);
pref("messaging-system.log", "warn");
pref("messaging-system.rsexperimentloader.enabled", true);
pref("network.cookie.rejectForeignWithExceptions.enabled", false);
pref("network.cookie.sameSite.laxByDefault.disabledHosts", "");
pref("network.http.http3.recvBufferSize", 1048576);
pref("privacy.purge_trackers.logging.level", "Warn");
pref("security.sandbox.socket.process.level", 0);
pref("signon.generation.confidenceThreshold", "0.75");
pref("signon.management.page.os-auth.enabled", true);
pref("signon.management.page.vulnerable-passwords.enabled", true);
```

==REMOVED or HIDDEN
```js
pref("app.update.url", "https://aus5.mozilla.org/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml");
pref("browser.in-content.dark-mode", true);
pref("browser.tabs.remote.useCORP", true);
pref("dom.manifest.onappinstalled", false);
pref("dom.registerContentHandler.enabled", false);
pref("extensions.blocklist.interval", 86400);
pref("extensions.blocklist.useXML", false);
pref("gfx.webrender.split-render-roots", false);
pref("javascript.options.experimental.await_fix", true);
pref("javascript.options.experimental.fields", true);
pref("javascript.options.strict", false);
pref("media.videocontrols.picture-in-picture.video-toggle.flyout-enabled", false);
pref("media.videocontrols.picture-in-picture.video-toggle.flyout-wait-ms", 5000);
pref("network.predictor.cleaned-up", false);
pref("pdfjs.eventBusDispatchToDOM", false);
pref("security.insecure_password.ui.enabled", true);
```

==CHANGED
```js
pref("browser.aboutwelcome.enabled", true); // prev: false
pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "https://%LOCALE%.malware-error.mozilla.com/?url="); // prev: "https://%LOCALE%.malware-error.mozilla.com/?hl=%LOCALE%&url="
pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "https://%LOCALE%.phish-error.mozilla.com/?url="); // prev: "https://%LOCALE%.phish-error.mozilla.com/?hl=%LOCALE%&url="
pref("browser.safebrowsing.provider.google.reportURL", "https://safebrowsing.google.com/safebrowsing/diagnostic?client=%NAME%&site="); // prev: "https://safebrowsing.google.com/safebrowsing/diagnostic?client=%NAME%&hl=%LOCALE%&site="
pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "https://%LOCALE%.malware-error.mozilla.com/?url="); // prev: "https://%LOCALE%.malware-error.mozilla.com/?hl=%LOCALE%&url="
pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "https://%LOCALE%.phish-error.mozilla.com/?url="); // prev: "https://%LOCALE%.phish-error.mozilla.com/?hl=%LOCALE%&url="
pref("browser.safebrowsing.provider.google4.reportURL", "https://safebrowsing.google.com/safebrowsing/diagnostic?client=%NAME%&site="); // prev: "https://safebrowsing.google.com/safebrowsing/diagnostic?client=%NAME%&hl=%LOCALE%&site="
pref("browser.safebrowsing.reportPhishURL", "https://%LOCALE%.phish-report.mozilla.com/?url="); // prev: "https://%LOCALE%.phish-report.mozilla.com/?hl=%LOCALE%&url="
pref("devtools.performance.recording.features", "[\"js\",\"leaf\",\"stackwalk\",\"screenshots\"]"); // prev: "[\"js\",\"leaf\",\"stackwalk\"]"
pref("dom.audioworklet.enabled", true); // prev: false
pref("dom.IntersectionObserverExplicitDocumentRoot.enabled", true); // prev: false
pref("dom.worklet.enabled", true); // prev: false
pref("gfx.webrender.max-partial-present-rects", 1); // prev: 0
pref("layout.css.serialize-grid-implicit-tracks", true); // prev: false
pref("media.cubeb.sandbox", true); // prev: false
pref("security.sandbox.content.level", 6); // prev: 5
pref("services.sync.extension-storage.skipPercentageChance", 50); // prev: 20
pref("signon.passwordEditCapture.enabled", true); // prev: false
pref("trailhead.firstrun.branches", "join-dynamic"); // prev: ""
pref("webgl.max-contexts", 1000); // prev: 32
pref("webgl.max-contexts-per-principal", 300); // prev: 16
```

</p></details>

**Comment by earthlng** [comment]
<details><summary>some bugzilla tickets</summary><p>

* app.update.url
Bug [1568994](https://bugzilla.mozilla.org/show_bug.cgi?id=1568994) - Convert usage of app.update.url pref to Services.appinfo.updateURL

* apz.zoom-to-focused-input.enabled
Bug [1623476](https://bugzilla.mozilla.org/show_bug.cgi?id=1623476) - Disable zoom-to-focused-input behaviour in clipboard tests.

* browser.aboutwelcome.enabled
Bug [1622474](https://bugzilla.mozilla.org/show_bug.cgi?id=1622474) - Enabled new About:Welcome experience by default; turned on dynamic triplets
Bug [1617783](https://bugzilla.mozilla.org/show_bug.cgi?id=1617783) - Add JSWindowActors to about:welcome

* browser.in-content.dark-mode
Bug [1626619](https://bugzilla.mozilla.org/show_bug.cgi?id=1626619) - Remove `browser.in-content.dark-mode` preference.

* browser.osKeyStore.loglevel
Bug [1194529](https://bugzilla.mozilla.org/show_bug.cgi?id=1194529) - Update OSKeyStore pref names now that the module is moved.

* browser.safebrowsing.provider.google.reportMalwareMistakeURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.provider.google.reportPhishMistakeURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.provider.google.reportURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.provider.google4.reportMalwareMistakeURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.provider.google4.reportPhishMistakeURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.provider.google4.reportURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.safebrowsing.reportPhishURL
Bug [1408779](https://bugzilla.mozilla.org/show_bug.cgi?id=1408779) - link to report why page has been classified as malicious/deceptive/... should have variables %NAME% and %LOCALE% replaced  

* browser.ssb.enabled
Bug [1620304](https://bugzilla.mozilla.org/show_bug.cgi?id=1620304): Make the SSB pref visible in about:config.

* browser.tabs.remote.allowLinkedWebInFileUriProcess
Bug [1626583](https://bugzilla.mozilla.org/show_bug.cgi?id=1626583) - Always disable allowLinkedWebInFileUriProcess
Bug [1603006](https://bugzilla.mozilla.org/show_bug.cgi?id=1603006) - Ignore allowLinkedWebInFile when documentChannel is enabled

* browser.tabs.remote.useCORP
Bug [1609078](https://bugzilla.mozilla.org/show_bug.cgi?id=1609078) - Removed browser.tabs.remote.useCORP
Bug [1602363](https://bugzilla.mozilla.org/show_bug.cgi?id=1602363) - Also pref on Cross-Origin-Resource-Policy for Android

* devtools.performance.popup.feature-flag
Bug [1621022](https://bugzilla.mozilla.org/show_bug.cgi?id=1621022) - Change the workflow of enabling the profiler menu button;

* devtools.performance.recording.duration.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.entries.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.features
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;
Bug [1602800](https://bugzilla.mozilla.org/show_bug.cgi?id=1602800) - Move profiler recording preferences from firefox.js to all.js
Bug [1599745](https://bugzilla.mozilla.org/show_bug.cgi?id=1599745) - Update default values of profiler recording preferences.
Bug [1599745](https://bugzilla.mozilla.org/show_bug.cgi?id=1599745) - Register all performance panel recording preferences and move their default values there.

* devtools.performance.recording.features.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.interval.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.objdirs.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.preset.remote
Bug [1621650](https://bugzilla.mozilla.org/show_bug.cgi?id=1621650) - Make Firefox Platform the default profiler preset on Nightly and Local builds;
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.performance.recording.threads.remote
Bug [1594798](https://bugzilla.mozilla.org/show_bug.cgi?id=1594798) - Store remote prefs on the client under a separate pref branch;

* devtools.responsive.touchGestureSimulation.enabled
Bug [1489653](https://bugzilla.mozilla.org/show_bug.cgi?id=1489653) - Simulate double-tap gestures in RDM

* dom.animations.mainthread-synchronization-with-geometric-animations
Bug [1616725](https://bugzilla.mozilla.org/show_bug.cgi?id=1616725) - Set dom.audioworklet.enabled and dom.worklet.enabled for Beta and Release.
bug [1616723](https://bugzilla.mozilla.org/show_bug.cgi?id=1616723) set dom.audioworklet.enabled and dom.worklet.enabled on Nightly
Bug [1623469](https://bugzilla.mozilla.org/show_bug.cgi?id=1623469) - Add a pref to disable synchronization transform animations with geometric animations.

* dom.arena_allocator.enabled
Bug [1624321](https://bugzilla.mozilla.org/show_bug.cgi?id=1624321) - Enable DOM node arena allocation
Bug [1377999](https://bugzilla.mozilla.org/show_bug.cgi?id=1377999) - Add the capability to do DOM node Arena allocation

* dom.audioworklet.enabled
Bug [1616725](https://bugzilla.mozilla.org/show_bug.cgi?id=1616725) - Set dom.audioworklet.enabled and dom.worklet.enabled for Beta and Release.
bug [1616723](https://bugzilla.mozilla.org/show_bug.cgi?id=1616723) set dom.audioworklet.enabled and dom.worklet.enabled on Nightly

* dom.events.compress.touchmove
Bug [1502529](https://bugzilla.mozilla.org/show_bug.cgi?id=1502529), compress touchmoves on IPC layer,

* dom.IntersectionObserverExplicitDocumentRoot.enabled
Bug [1623623](https://bugzilla.mozilla.org/show_bug.cgi?id=1623623) - Enable dom.IntersectionObserverExplicitDocumentRoot by default
Bug [1617154](https://bugzilla.mozilla.org/show_bug.cgi?id=1617154) - [intersection-observer] Accept a Document as an explicit root.

* dom.manifest.onappinstalled
Bug [1625384](https://bugzilla.mozilla.org/show_bug.cgi?id=1625384) - Remove window.onappinstalled event, as it was never used or shipped

* dom.no_unknown_protocol_error.enabled
Bug [1528305](https://bugzilla.mozilla.org/show_bug.cgi?id=1528305) - Don't show an error page for unknown protocols for page-triggered navigations that replace a document.

* dom.quotaManager.useDOSDevicePathSyntax
Bug [1626846](https://bugzilla.mozilla.org/show_bug.cgi?id=1626846) - Disable useDOSDevicePathSyntax for QuotaStorage on Windows;

* dom.registerContentHandler.enabled
Bug [1597268](https://bugzilla.mozilla.org/show_bug.cgi?id=1597268) - Remove Navigator#registerContentHandler

* dom.security.https_only_mode
Bug [1620242](https://bugzilla.mozilla.org/show_bug.cgi?id=1620242) - Basic implementation for HTTPS Only Mode.

* dom.security.secFetch.enabled
Bug [1508292](https://bugzilla.mozilla.org/show_bug.cgi?id=1508292): Implement Sec-Fetch-*.

* dom.workers.serialized-sab-access
Bug [1563335](https://bugzilla.mozilla.org/show_bug.cgi?id=1563335) - Part 2: Add a pref for serializing all JS threads that access shared SABs.

* dom.worklet.enabled
Bug [1616725](https://bugzilla.mozilla.org/show_bug.cgi?id=1616725) - Set dom.audioworklet.enabled and dom.worklet.enabled for Beta and Release.
bug [1616723](https://bugzilla.mozilla.org/show_bug.cgi?id=1616723) set dom.audioworklet.enabled and dom.worklet.enabled on Nightly

* extensions.blocklist.interval
Bug [1618188](https://bugzilla.mozilla.org/show_bug.cgi?id=1618188) - remove XML backend for plugin and add-on blocklisting,

* extensions.blocklist.url
Bug [1618188](https://bugzilla.mozilla.org/show_bug.cgi?id=1618188) - remove XML backend for plugin and add-on blocklisting,

* extensions.blocklist.useXML
Bug [1618188](https://bugzilla.mozilla.org/show_bug.cgi?id=1618188) - remove XML backend for plugin and add-on blocklisting,
Bug [1603072](https://bugzilla.mozilla.org/show_bug.cgi?id=1603072) - Re-enable extensions.blocklist.useXML for 72 release.
Bug [1594521](https://bugzilla.mozilla.org/show_bug.cgi?id=1594521) - enable remote settings blocklist on nightly,

* gfx.vsync.use-waitforvblank
Bug [1628137](https://bugzilla.mozilla.org/show_bug.cgi?id=1628137) - Switch to using WaitForVBlank for vsync on Windows.

* gfx.webrender.compositor.force-enabled
Bug [1625002](https://bugzilla.mozilla.org/show_bug.cgi?id=1625002) - Add pref to allow force enabled the WebRender compositor.

* gfx.webrender.max-partial-present-rects
Bug [1593179](https://bugzilla.mozilla.org/show_bug.cgi?id=1593179) - Enable gfx.webrender.max-partial-present-rects by default on Windows

* gfx.webrender.split-render-roots
Bug [1622360](https://bugzilla.mozilla.org/show_bug.cgi?id=1622360) - Remove the split_render_roots pref and immediate codepaths that depend on it.
Bug [1592509](https://bugzilla.mozilla.org/show_bug.cgi?id=1592509) - Re-enable gfx.webrender.compositor by default on Windows

* javascript.options.experimental.await_fix
Bug [1616882](https://bugzilla.mozilla.org/show_bug.cgi?id=1616882) - Part 1: Remove the 'await_fix' option.

* javascript.options.experimental.fields
Bug [1616882](https://bugzilla.mozilla.org/show_bug.cgi?id=1616882) - Part 2: Remove class fields option.

* javascript.options.strict
Bug [1619177](https://bugzilla.mozilla.org/show_bug.cgi?id=1619177) - Remove remaining extra warnings code.

* layout.css.image-orientation.initial-from-image
Bug [1623820](https://bugzilla.mozilla.org/show_bug.cgi?id=1623820) - Part 2: Make image-orientation initial value change be Nightly only.

* layout.css.serialize-grid-implicit-tracks
Bug [1619538](https://bugzilla.mozilla.org/show_bug.cgi?id=1619538) - Ship layout.css.serialize-grid-implicit-tracks=false everywhere.

* media.cubeb.sandbox
Bug [1585732](https://bugzilla.mozilla.org/show_bug.cgi?id=1585732) - use staticprefs for media.cubeb.sandbox,
Bug [1590249](https://bugzilla.mozilla.org/show_bug.cgi?id=1590249) - Enable AudioIPC on Windows in Nightly builds. 
Bug [1623798](https://bugzilla.mozilla.org/show_bug.cgi?id=1623798) - Enable AudioIPC for Windows 64-bit in Fx76.
Bug [1625008](https://bugzilla.mozilla.org/show_bug.cgi?id=1625008) - Make AudioIPC for Windows nightly/early-beta only. 
Bug [1625008](https://bugzilla.mozilla.org/show_bug.cgi?id=1625008) - Disable AudioIPC on Windows in beta. 
Bug [1623793](https://bugzilla.mozilla.org/show_bug.cgi?id=1623793) - Disable AudioIPC on 32-bit Windows in beta. 
Bug [1432303](https://bugzilla.mozilla.org/show_bug.cgi?id=1432303) - Let Windows AudioIPC ride the trains. 

* media.getusermedia.hpf_enabled
Bug [1627313](https://bugzilla.mozilla.org/show_bug.cgi?id=1627313) - Activate an HPF on getUserMedia microphone input, when processing is enabled.

* media.navigator.video.use_transport_cc
Bug [1606823](https://bugzilla.mozilla.org/show_bug.cgi?id=1606823) - Add support for WebRTC transport-cc extension.

* media.videocontrols.picture-in-picture.video-toggle.flyout-enabled
Bug [1624702](https://bugzilla.mozilla.org/show_bug.cgi?id=1624702) - Get rid of some dead Picture-in-Picture prefs.

* media.videocontrols.picture-in-picture.video-toggle.flyout-wait-ms
Bug [1624702](https://bugzilla.mozilla.org/show_bug.cgi?id=1624702) - Get rid of some dead Picture-in-Picture prefs.

* media.videocontrols.picture-in-picture.video-toggle.min-video-secs
Bug [1624702](https://bugzilla.mozilla.org/show_bug.cgi?id=1624702) - Add a preference to control the minimum video length for displaying the Picture-in-Picture toggle.

* messaging-system.log
Bug [1620021](https://bugzilla.mozilla.org/show_bug.cgi?id=1620021) - Integrate aboutwelcome with ExperimentManager.

* messaging-system.rsexperimentloader.enabled
Bug [1620021](https://bugzilla.mozilla.org/show_bug.cgi?id=1620021) - Integrate aboutwelcome with ExperimentManager.

* network.cookie.rejectForeignWithExceptions.enabled
Bug [1625568](https://bugzilla.mozilla.org/show_bug.cgi?id=1625568) - Add compatibility heuristics to third-party cookie blocking - part 1 - pref to add heuristics and storage access API to cookie behavior REJECT_FOREIGN,

* network.cookie.sameSite.laxByDefault.disabledHosts
Bug [1623313](https://bugzilla.mozilla.org/show_bug.cgi?id=1623313) - disable cookie sameSite=laxByDefault for a list of hosts by pref,

* network.http.http3.recvBufferSize
Bug [1625284](https://bugzilla.mozilla.org/show_bug.cgi?id=1625284) - Increase receive buffer size of QUIC socket

* network.predictor.cleaned-up
Bug [1544868](https://bugzilla.mozilla.org/show_bug.cgi?id=1544868) - Remove network predictor code  and network.predictor.cleaned-up preference

* privacy.purge_trackers.logging.level
Bug [1624863](https://bugzilla.mozilla.org/show_bug.cgi?id=1624863) - Rewrite PurgeTrackerService.jsm logging to use console.createInstance

* security.insecure_password.ui.enabled
Bug [1567827](https://bugzilla.mozilla.org/show_bug.cgi?id=1567827) Get rid of security.insecure_password.ui.enabled

* security.sandbox.content.level
Bug [1557282](https://bugzilla.mozilla.org/show_bug.cgi?id=1557282) Part 3: Use SetLockdownDefaultDacl and AddRestrictingRandomSid in sandbox policies.

* security.sandbox.socket.process.level
Bug [1608558](https://bugzilla.mozilla.org/show_bug.cgi?id=1608558) - pt4 - use security.sandbox.socket.process.level for linux socket process sandbox.

* services.sync.extension-storage.skipPercentageChance
Bug [1630222](https://bugzilla.mozilla.org/show_bug.cgi?id=1630222) - Decrease webextension sync frequency.
Bug [1621806](https://bugzilla.mozilla.org/show_bug.cgi?id=1621806) - Reduce frequency of client-side extension-storage syncs.

* signon.generation.confidenceThreshold
Bug [1595244](https://bugzilla.mozilla.org/show_bug.cgi?id=1595244) - Use field labels and attributes to determine new-password field types
Bug [1625601](https://bugzilla.mozilla.org/show_bug.cgi?id=1625601) - Make improvements to new-password heuristics for accuracy and performance

* signon.management.page.os-auth.enabled
Bug [1626138](https://bugzilla.mozilla.org/show_bug.cgi?id=1626138) - Add a temporary pref to disable the OS auth prompt.

* signon.management.page.vulnerable-passwords.enabled
Bug [1626107](https://bugzilla.mozilla.org/show_bug.cgi?id=1626107) - Enable vulnerable password alerts by default.
Bug [1569848](https://bugzilla.mozilla.org/show_bug.cgi?id=1569848) - Mark logins as vulnerable if they use a password shared with a breached login by the same user.

* signon.passwordEditCapture.enabled
Bug [1618696](https://bugzilla.mozilla.org/show_bug.cgi?id=1618696) - Enable signon.passwordEditCapture.enabled by default.
Bug [1536728](https://bugzilla.mozilla.org/show_bug.cgi?id=1536728) - Show dismissed save/update doorhanger when password value is changed.

* trailhead.firstrun.branches
Bug [1622474](https://bugzilla.mozilla.org/show_bug.cgi?id=1622474) - Enabled new About:Welcome experience by default; turned on dynamic triplets

* webgl.max-contexts
Bug [1628193](https://bugzilla.mozilla.org/show_bug.cgi?id=1628193) - Increase max webgl contexts (per principal) to 1000 (300).

* webgl.max-contexts-per-principal
Bug [1628193](https://bugzilla.mozilla.org/show_bug.cgi?id=1628193) - Increase max webgl contexts (per principal) to 1000 (300).

</p></details>

**Comment by earthlng** [comment]
I cannot add any labels because Pants kicked me out of the Org (by accident?)

**Comment by Thorin-Oakenpants** [comment]
@earthlng ... FYI - https://bugzilla.mozilla.org/show_bug.cgi?id=1632279

**Comment by earthlng** [comment]
Thanks for the FYI

**Comment by Thorin-Oakenpants** [comment]
some notes / thoughts:
- [1613063](https://bugzilla.mozilla.org/show_bug.cgi?id=1613063) meta https only mode
- to lookup: telemetry for `http only` and `mixed`
- confirm what happens: i think it's:
   - top level = error page with override - is this override session only?
   - sub-resource silently fail
- any outstanding bugs
- ref to get: Firefox security blog post on it (if they have one)

**maybe** make it active `true` ( **might** depend on some of the above answers ) ... my logic goes as follows
- active + passive mixed content (1241,1243) is already set to true
- if the top level doc is secure, all that matters is that the rest (sub-resources, 3rd party) is secure: and with `1241`, `1243` we're already silently failing on them
- the new pref would automatically try to upgrade some of them (but not sub-resources maybe) <-- **I think this is the only real benefit of this pref for now**
- the reverse (insecure top doc) is already covered for things that matter (like logins, service workers, etc: a **lot** of APIs are limited to secure context). I would have to check, but I don't think an insecure site blocks secure passive consent with 1241. Active content with 1243 I'm not so sure about. But it's probably a moot point
- having the new pref active doesn't actually block being able to load an insecure site, but might be annoying <-- **so it's not really a benefit**: i.e. we already get a red padlock for insecure, and this is just a "bigger padlock"

Personally, over the last three or four years, every so often, I check which of my insecure speed dials / bookmarks can be changed to HTTPS. About a year ago I dead-ended at about 20 left. Then suddenly, a week ago I got down to three sites (out of about 300): so I deleted those three insecure dials - fuck em. I am so ready to move to secure only.

Class, discuss!

**Comment by earthlng** [comment]
> having the new pref active doesn't actually block being able to load an insecure site

I guess you're basing this on that 1 sentence in the 1st comment in 1613063, namely:

> For top-level loads which encounter a time-out we could provide some kind of error page with a button which would allow the end user to load the requested page using http.

note the word "could" (and "would"). They're actually still working on that error page in [1625156](https://bugzilla.mozilla.org/show_bug.cgi?id=1625156) and FF76 presumably doesn't have an easy way yet to load an insecure site other than toggling the pref in about:config.

We should definitely add the pref to the user.js for people to try but I'd keep it inactive for now.

**Comment by Thorin-Oakenpants** [comment]
"confirm what happens: i think it's" .. and yes, the basis was from that first sentence ... so the idea was to read more, test it, etc. If it doesn't allow an single click override per site (hopefully session only) then it will be inactive

**Comment by rusty-snake** [comment]
`dom.security.https_only_mode=true`:
- https://http.badssl.com/ Can not be loaded without hom=false because it has a valid cert and supports https, but redirects (301 Moved Permanently) to its http version, ending in a redirect-error.
- https://neverssl.com/, https://http.rip/, https://zombo.com/ Can be loaded over https using exceptions.
 This is one click with `browser.xul.error_pages.expert_bad_cert=true` (default in user.js)

_tested with firefox-beta_

**Comment by rusty-snake** [comment]
With `privacy.clearOnShutdown.siteSettings=true` this is session only.

**Comment by Thorin-Oakenpants** [comment]
OK, I've had a bit more time to read some related tickets: and it's clearly in an experimental stage: so inactive for sure - and it'll just have a `[warning] experimental`

we don't clear site permissions by default: but that's interesting that it's using that mechanism. Can you inspect the sqlite in your test to see what it adds?

**Comment by rusty-snake** [comment]
good test sites:
- top-level http: `neverssl.com`
- top-level https: `badssl.com`
  - https-http redirect: `http.badssl.com`
  - http js: `mixed-script.badssl.com`
  - http jpg: `mixed.badssl.com`

**Comment by rusty-snake** [comment]
The exceptions are stored in `cert_override.txt` with a format that looks like
`domain.tld:port ???? SHA-256-Fingerprint some-bas64-encoded-data`.

**Comment by Thorin-Oakenpants** [comment]
Hmmm .. seems like shortened bugzilla links currently don't work
- https://bugzilla.mozilla.org/1613063
- https://bugzilla.mozilla.org/show_bug.cgi?id=1613063

**Comment by Thorin-Oakenpants** [comment]
- [1508292](https://bugzilla.mozilla.org/show_bug.cgi?id=1508292) implement Sec-Fetch
- https://github.com/mikewest/sec-metadata - from comment 0
- w3c - https://w3c.github.io/webappsec-fetch-metadata/

It default false, so we don't need to worry about it for now. And AFAICT it would only be a good thing : "gives websites additional context to protect themselves against cross-site attacks" - [source - very last sentence](https://wiki.mozilla.org/Firefox_Security_Newsletter/FSN-2020-Q1)

**Comment by geeknik** [comment]
> The exceptions are stored in `cert_override.txt` with a format that looks like
> `domain.tld:port ???? SHA-256-Fingerprint some-bas64-encoded-data`.

In case anyone cares what all of that stuff means... cert_override.txt fields are separated by a tab character. Each line is terminated by a line feed character (UNIX format).

1. domainname:port 
2. hash algorithm OID
        SHA1-256: OID.2.16.840.1.101.3.4.2.1 (most used)
        SHA-384: OID.2.16.840.1.101.3.4.2.2
        SHA-512: OID.2.16.840.1.101.3.4.2.3
3. Certificate fingerprint using previous hash algorithm
4. One or more characters for override type:
        M : allow mismatches in the hostname
        U : allow untrusted certs (whether it's self signed cert or a missing or invalid issuer cert)
        T : allow errors in the validity time, for example, for expired or not yet valid certs
5. Certificate's serial number and the issuer name as a base64 encoded string
